package uk.gov.mrtm.api.emissionsmonitoringplan.domain.emissions.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FlagState {

    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AG("Antigua and Barbuda"),
    AI("Anguilla, UK"),
    AL("Albania"),
    AM("Armenia"),
    AO("Angola"),
    AR("Argentina"),
    AS("American Samoa (USA)"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba (NL)"),
    AZ("Azerbaijan"),
    BA("Bosnia and Herzegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgium"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BJ("Benin"),
    BM("Bermuda, UK"),
    BN("Brunei"),
    BO("Bolivia"),
    BQ("Bonaire, Sint Eustatius and Saba"),
    BR("Brazil"),
    BS("Bahamas"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CD("Congo, the Democratic Republic of the"),
    CG("Congo"),
    CH("Switzerland"),
    CI("Cote d'Ivoire"),
    CK("Canada"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CU("Cuba"),
    CV("Cape Verde"),
    CW("Curacao"),
    CY("Cyprus"),
    CZ("Czechia"),
    DE("Germany"),
    DJ("Djibouti"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egypt"),
    ER("Eritrea"),
    ES("Spain"),
    ET("Ethiopia"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falkland Islands, UK (Malvinas)"),
    FM("Micronesia, Federated States of"),
    FO("Faroe Islands"),
    FR("France"),
    GA("Gabon"),
    GB("United Kingdom"),
    GD("Grenada"),
    GE("Georgia"),
    GG("Guernsey, UK"),
    GH("Ghana"),
    GI("Gibraltar, UK"),
    GM("The Gambia"),
    GN("Guinea"),
    GQ("Equatorial Guinea"),
    GR("Greece"),
    GT("Guatemala"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong, China"),
    HN("Honduras"),
    HR("Croatia"),
    HT("Haiti"),
    HU("Hungary"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IM("Isle of Man, UK"),
    IN("India"),
    IQ("Iraq"),
    IR("Iran, Islamic Republic of"),
    IS("Iceland"),
    IT("Italy"),
    JE("Jersey, UK"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KI("Kiribati"),
    KM("Comoros"),
    KN("Saint Kitts and Nevis"),
    KP("Korea, Democratic People's Republic of"),
    KR("Korea, Republic of"),
    KW("Kuwait"),
    KY("Cayman Islands, UK"),
    KZ("Kazakhstan"),
    LA("Lao People's Democratic Republic"),
    LB("Lebanon"),
    LC("Saint Lucia"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova, Republic of"),
    ME("Montenegro"),
    MG("Madagascar"),
    MH("Marshall Islands"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao, China"),
    MR("Mauritania"),
    MS("Montserrat, UK"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldives"),
    MX("Mexico"),
    MY("Malaysia"),
    MZ("Mozambique"),
    NA("Namibia"),
    NE("Niger"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Netherlands"),
    NO("Norway"),
    NR("Nauru"),
    NZ("New Zealand"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PF("French Polynesia (FR)"),
    PG("Papua New Guinea"),
    PH("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PT("Portugal"),
    PW("Palau"),
    PY("Paraguay"),
    QA("Qatar"),
    RO("Romania"),
    RS("Serbia"),
    RU("Russian Federation"),
    SA("Saudi Arabia"),
    SB("Solomon Islands"),
    SC("Seychelles"),
    SL("Sierra Leone"),
    SD("Sudan"),
    SE("Sweden"),
    SG("Singapore"),
    SH("St. Helena, Ascension and Tristan Da Cunha, UK"),
    SI("Slovenia"),
    SK("Slovakia"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Suriname"),
    SS("South Sudan"),
    ST("Sao Tome and Principe"),
    SV("El Salvador"),
    SX("Sint Maarten (Dutch Part)"),
    SY("Syrian Arab Republic"),
    TC("Turks and Caicos Islands, UK"),
    TF("French Southern Territories (FR)"),
    TG("Togo"),
    TH("Thailand"),
    TJ("Tajikistan"),
    TM("Turkmenistan"),
    TN("Tunisia"),
    TO("Tonga"),
    TR("Turkey"),
    TT("Trinidad and Tobago"),
    TV("Tuvalu"),
    TW("Taiwan, Province of China"),
    TZ("Tanzania, United Republic of"),
    UA("Ukraine"),
    UG("Uganda"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VC("Saint Vincent and the Grenadines"),
    VE("Venezuela (Bolivarian Republic of)"),
    VG("British Virgin Islands"),
    VI("??"),
    VN("Viet Nam"),
    VU("Vanuatu"),
    WS("Samoa"),
    YE("Yemen"),
    ZA("South Africa"),
    ZW("Zimbabwe");

    private final String description;
}
