import {
  AER_VERIFIER_FINDINGS_STEP_EXIST_FORM,
  AER_VERIFIER_FINDINGS_STEP_ITEM_DELETE,
  AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_ADD,
  AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_EDIT,
  AER_VERIFIER_FINDINGS_STEP_ITEMS_LIST,
} from '@requests/common/aer/aer.consts';

export const UNCORRECTED_NON_CONFORMITIES_SUB_TASK = 'uncorrectedNonConformities';

export const UNCORRECTED_NON_CONFORMITIES_SUB_TASK_PATH = 'uncorrected-non-conformities';

export enum UncorrectedNonConformitiesStep {
  SUMMARY = '../',
  EXIST_FORM = AER_VERIFIER_FINDINGS_STEP_EXIST_FORM,
  ITEMS_LIST = AER_VERIFIER_FINDINGS_STEP_ITEMS_LIST,
  ITEM_FORM_ADD = AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_ADD,
  ITEM_FORM_EDIT = AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_EDIT,
  ITEM_DELETE = AER_VERIFIER_FINDINGS_STEP_ITEM_DELETE,
  PRIOR_YEAR_ISSUES_EXIST_FORM = 'prior-year-issues-exist',
  PRIOR_YEAR_ISSUES_LIST = 'prior-year-issues-list',
  PRIOR_YEAR_ISSUE_FORM_ADD = 'prior-year-issue-add',
  PRIOR_YEAR_ISSUE_FORM_EDIT = 'prior-year-issue-edit',
  PRIOR_YEAR_ISSUE_DELETE = 'prior-year-issue-remove',
}
