import {
  AER_VERIFIER_FINDINGS_STEP_EXIST_FORM,
  AER_VERIFIER_FINDINGS_STEP_ITEM_DELETE,
  AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_ADD,
  AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_EDIT,
  AER_VERIFIER_FINDINGS_STEP_ITEMS_LIST,
} from '@requests/common/aer/aer.consts';

export const UNCORRECTED_NON_COMPLIANCES_SUB_TASK = 'uncorrectedNonCompliances';

export const UNCORRECTED_NON_COMPLIANCES_SUB_TASK_PATH = 'uncorrected-non-compliances';

export enum UncorrectedNonCompliancesStep {
  SUMMARY = '../',
  EXIST_FORM = AER_VERIFIER_FINDINGS_STEP_EXIST_FORM,
  ITEMS_LIST = AER_VERIFIER_FINDINGS_STEP_ITEMS_LIST,
  ITEM_FORM_ADD = AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_ADD,
  ITEM_FORM_EDIT = AER_VERIFIER_FINDINGS_STEP_ITEM_FORM_EDIT,
  ITEM_DELETE = AER_VERIFIER_FINDINGS_STEP_ITEM_DELETE,
}
