import {
  EmissionsSources,
  EmpFuelsAndEmissionsFactors,
  FuelOriginTypeName,
  ShipDetails,
  UncertaintyLevel,
} from '@mrtm/api';

import { GovukSelectOption } from '@netz/govuk-components';

import { FuelsAndEmissionsFactors, FuelType } from '@shared/types';

export const SHIP_TYPE_SELECT_ITEMS: GovukSelectOption<ShipDetails['type']>[] = [
  { value: 'PAX', text: 'Passenger Ship' },
  { value: 'RORO', text: 'Ro-ro ship' },
  { value: 'CONT', text: 'Container Ship' },
  { value: 'OIL', text: 'Oil tanker' },
  { value: 'CHEM', text: 'Chemical tanker' },
  { value: 'LNG', text: 'LNG Carrier' },
  { value: 'GAS', text: 'Gas Carrier' },
  { value: 'BULK', text: 'Bulk carrier' },
  { value: 'GENERAL', text: 'General cargo ship' },
  { value: 'RCV', text: 'Refrigerated cargo ship' },
  { value: 'VEH', text: 'Vehicle carrier' },
  { value: 'COMB', text: 'Combination carrier' },
  { value: 'ROPAX', text: 'Ro-pax ship' },
  { value: 'CONT_RORO', text: 'Container/ro-ro cargo ship' },
  { value: 'CRUISE', text: 'Cruise passenger ship' },
  { value: 'OFFSHORE', text: 'Offshore support vessel' },
  { value: 'OTHER', text: 'Other ship types' },
];

export const EMP_SHIP_REPORTING_RESPONSIBILITY_SELECT_ITEMS: GovukSelectOption<
  ShipDetails['natureOfReportingResponsibility']
>[] = [
  { value: 'SHIPOWNER', text: 'Registered Owner' },
  { value: 'ISM_COMPANY', text: 'ISM Company' },
];

export const SHIP_ICE_CLASS_SELECT_ITEMS: GovukSelectOption<ShipDetails['iceClass']>[] = [
  { value: 'PC1', text: 'PC1' },
  { value: 'PC2', text: 'PC2' },
  { value: 'PC3', text: 'PC3' },
  { value: 'PC4', text: 'PC4' },
  { value: 'PC5', text: 'PC5' },
  { value: 'PC6', text: 'PC6' },
  { value: 'PC7', text: 'PC7' },
  { value: 'IC', text: 'IC' },
  { value: 'IB', text: 'IB' },
  { value: 'IA', text: 'IA' },
  { value: 'IA_SUPER', text: 'IA Super' },
  { value: 'NA', text: 'Not applicable' },
];

export const SHIP_FLAG_SELECT_ITEMS: GovukSelectOption<ShipDetails['flagState']>[] = [
  { value: 'AE', text: 'United Arab Emirates' },
  { value: 'AF', text: 'Afghanistan' },
  { value: 'AG', text: 'Antigua and Barbuda' },
  { value: 'AI', text: 'Anguilla, UK' },
  { value: 'AL', text: 'Albania' },
  { value: 'AM', text: 'Armenia' },
  { value: 'AO', text: 'Angola' },
  { value: 'AR', text: 'Argentina' },
  { value: 'AS', text: 'American Samoa (USA)' },
  { value: 'AT', text: 'Austria' },
  { value: 'AU', text: 'Australia' },
  { value: 'AW', text: 'Aruba (NL)' },
  { value: 'AZ', text: 'Azerbaijan' },
  { value: 'BA', text: 'Bosnia and Herzegovina' },
  { value: 'BB', text: 'Barbados' },
  { value: 'BD', text: 'Bangladesh' },
  { value: 'BE', text: 'Belgium' },
  { value: 'BG', text: 'Bulgaria' },
  { value: 'BH', text: 'Bahrain' },
  { value: 'BJ', text: 'Benin' },
  { value: 'BM', text: 'Bermuda, UK' },
  { value: 'BN', text: 'Brunei Darussalam' },
  { value: 'BO', text: 'Bolivia' },
  { value: 'BQ', text: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BR', text: 'Brazil' },
  { value: 'BS', text: 'Bahamas' },
  { value: 'BY', text: 'Belarus' },
  { value: 'BZ', text: 'Belize' },
  { value: 'CA', text: 'Canada' },
  { value: 'CD', text: 'Congo, the Democratic Republic of the' },
  { value: 'CG', text: 'Congo' },
  { value: 'CH', text: 'Switzerland' },
  { value: 'CI', text: "Cote d'Ivoire" },
  { value: 'CK', text: 'Cook Islands' },
  { value: 'CL', text: 'Chile' },
  { value: 'CM', text: 'Cameroon' },
  { value: 'CN', text: 'China' },
  { value: 'CO', text: 'Colombia' },
  { value: 'CR', text: 'Costa Rica' },
  { value: 'CU', text: 'Cuba' },
  { value: 'CV', text: 'Cape Verde' },
  { value: 'CW', text: 'Curacao' },
  { value: 'CY', text: 'Cyprus' },
  { value: 'CZ', text: 'Czech Republic' },
  { value: 'DE', text: 'Germany' },
  { value: 'DJ', text: 'Djibouti' },
  { value: 'DK', text: 'Denmark' },
  { value: 'DM', text: 'Dominica' },
  { value: 'DO', text: 'Dominican Republic' },
  { value: 'DZ', text: 'Algeria' },
  { value: 'EC', text: 'Ecuador' },
  { value: 'EE', text: 'Estonia' },
  { value: 'EG', text: 'Egypt' },
  { value: 'ER', text: 'Eritrea' },
  { value: 'ES', text: 'Spain' },
  { value: 'ET', text: 'Ethiopia' },
  { value: 'FI', text: 'Finland' },
  { value: 'FJ', text: 'Fiji' },
  { value: 'FK', text: 'Falkland Islands, UK (Malvinas)' },
  { value: 'FM', text: 'Micronesia, Federated States of' },
  { value: 'FO', text: 'Faroe Islands' },
  { value: 'FR', text: 'France' },
  { value: 'GA', text: 'Gabon' },
  { value: 'GB', text: 'United Kingdom' },
  { value: 'GD', text: 'Grenada' },
  { value: 'GE', text: 'Georgia' },
  { value: 'GG', text: 'Guernsey, UK' },
  { value: 'GH', text: 'Ghana' },
  { value: 'GI', text: 'Gibraltar, UK' },
  { value: 'GM', text: 'Gambia' },
  { value: 'GN', text: 'Guinea' },
  { value: 'GQ', text: 'Equatorial Guinea' },
  { value: 'GR', text: 'Greece' },
  { value: 'GT', text: 'Guatemala' },
  { value: 'GW', text: 'Guinea-Bissau' },
  { value: 'GY', text: 'Guyana' },
  { value: 'HK', text: 'Hong Kong, China' },
  { value: 'HN', text: 'Honduras' },
  { value: 'HR', text: 'Croatia' },
  { value: 'HT', text: 'Haiti' },
  { value: 'HU', text: 'Hungary' },
  { value: 'ID', text: 'Indonesia' },
  { value: 'IE', text: 'Ireland' },
  { value: 'IL', text: 'Israel' },
  { value: 'IM', text: 'Isle of Man, UK' },
  { value: 'IN', text: 'India' },
  { value: 'IQ', text: 'Iraq' },
  { value: 'IR', text: 'Iran, Islamic Republic of' },
  { value: 'IS', text: 'Iceland' },
  { value: 'IT', text: 'Italy' },
  { value: 'JE', text: 'Jersey, UK' },
  { value: 'JM', text: 'Jamaica' },
  { value: 'JO', text: 'Jordan' },
  { value: 'JP', text: 'Japan' },
  { value: 'KE', text: 'Kenya' },
  { value: 'KG', text: 'Kyrgyzstan' },
  { value: 'KH', text: 'Cambodia' },
  { value: 'KI', text: 'Kiribati' },
  { value: 'KM', text: 'Comoros' },
  { value: 'KN', text: 'Saint Kitts and Nevis' },
  { value: 'KP', text: "Korea, Democratic People's Republic of" },
  { value: 'KR', text: 'Korea, Republic of' },
  { value: 'KW', text: 'Kuwait' },
  { value: 'KY', text: 'Cayman Islands, UK' },
  { value: 'KZ', text: 'Kazakhstan' },
  { value: 'LA', text: "Lao People's Democratic Republic" },
  { value: 'LB', text: 'Lebanon' },
  { value: 'LC', text: 'Saint Lucia' },
  { value: 'LK', text: 'Sri Lanka' },
  { value: 'LR', text: 'Liberia' },
  { value: 'LT', text: 'Lithuania' },
  { value: 'LU', text: 'Luxembourg' },
  { value: 'LV', text: 'Latvia' },
  { value: 'LY', text: 'Libya' },
  { value: 'MA', text: 'Morocco' },
  { value: 'MC', text: 'Monaco' },
  { value: 'MD', text: 'Moldova, Republic of' },
  { value: 'ME', text: 'Montenegro' },
  { value: 'MG', text: 'Madagascar' },
  { value: 'MH', text: 'Marshall Islands' },
  { value: 'ML', text: 'Mali' },
  { value: 'MM', text: 'Myanmar' },
  { value: 'MN', text: 'Mongolia' },
  { value: 'MO', text: 'Macao, China' },
  { value: 'MR', text: 'Mauritania' },
  { value: 'MS', text: 'Montserrat, UK' },
  { value: 'MT', text: 'Malta' },
  { value: 'MU', text: 'Mauritius' },
  { value: 'MV', text: 'Maldives' },
  { value: 'MX', text: 'Mexico' },
  { value: 'MY', text: 'Malaysia' },
  { value: 'MZ', text: 'Mozambique' },
  { value: 'NA', text: 'Namibia' },
  { value: 'NE', text: 'Niger' },
  { value: 'NG', text: 'Nigeria' },
  { value: 'NI', text: 'Nicaragua' },
  { value: 'NL', text: 'Netherlands' },
  { value: 'NO', text: 'Norway' },
  { value: 'NR', text: 'Nauru' },
  { value: 'NZ', text: 'New Zealand' },
  { value: 'OM', text: 'Oman' },
  { value: 'PA', text: 'Panama' },
  { value: 'PE', text: 'Peru' },
  { value: 'PF', text: 'French Polynesia (FR)' },
  { value: 'PG', text: 'Papua New Guinea' },
  { value: 'PH', text: 'Philippines' },
  { value: 'PK', text: 'Pakistan' },
  { value: 'PL', text: 'Poland' },
  { value: 'PT', text: 'Portugal' },
  { value: 'PW', text: 'Palau' },
  { value: 'PY', text: 'Paraguay' },
  { value: 'QA', text: 'Qatar' },
  { value: 'RO', text: 'Romania' },
  { value: 'RS', text: 'Serbia' },
  { value: 'RU', text: 'Russian Federation' },
  { value: 'SA', text: 'Saudi Arabia' },
  { value: 'SB', text: 'Solomon Islands' },
  { value: 'SC', text: 'Seychelles' },
  { value: 'SL', text: 'Sierra Leone' },
  { value: 'SD', text: 'Sudan' },
  { value: 'SE', text: 'Sweden' },
  { value: 'SG', text: 'Singapore' },
  { value: 'SH', text: 'St. Helena, Ascension and Tristan Da Cunha, UK' },
  { value: 'SI', text: 'Slovenia' },
  { value: 'SK', text: 'Slovakia' },
  { value: 'SN', text: 'Senegal' },
  { value: 'SO', text: 'Somalia' },
  { value: 'SR', text: 'Suriname' },
  { value: 'SS', text: 'South Sudan' },
  { value: 'ST', text: 'Sao Tome and Principe' },
  { value: 'SV', text: 'El Salvador' },
  { value: 'SX', text: 'Sint Maarten (Dutch Part)' },
  { value: 'SY', text: 'Syrian Arab Republic' },
  { value: 'TC', text: 'Turks and Caicos Islands, UK' },
  { value: 'TF', text: 'French Southern Territories (FR)' },
  { value: 'TG', text: 'Togo' },
  { value: 'TH', text: 'Thailand' },
  { value: 'TJ', text: 'Tajikistan' },
  { value: 'TM', text: 'Turkmenistan' },
  { value: 'TN', text: 'Tunisia' },
  { value: 'TO', text: 'Tonga' },
  { value: 'TR', text: 'Turkey' },
  { value: 'TT', text: 'Trinidad and Tobago' },
  { value: 'TV', text: 'Tuvalu' },
  { value: 'TW', text: 'Taiwan, Province of China' },
  { value: 'TZ', text: 'Tanzania, United Republic of' },
  { value: 'UA', text: 'Ukraine' },
  { value: 'UG', text: 'Uganda' },
  { value: 'US', text: 'United States' },
  { value: 'UY', text: 'Uruguay' },
  { value: 'UZ', text: 'Uzbekistan' },
  { value: 'VC', text: 'Saint Vincent and the Grenadines' },
  { value: 'VE', text: 'Venezuela' },
  { value: 'VG', text: 'Virgin Islands British, UK' },
  { value: 'VI', text: 'Virgin Islands  USA' },
  { value: 'VN', text: 'Viet Nam' },
  { value: 'VU', text: 'Vanuatu' },
  { value: 'WS', text: 'Samoa' },
  { value: 'YE', text: 'Yemen' },
  { value: 'ZA', text: 'South Africa' },
  { value: 'ZW', text: 'Zimbabwe' },
];

export const FUEL_ORIGIN_TITLE: Record<FuelsAndEmissionsFactors['origin'], string> = {
  FOSSIL: 'Fossil fuel',
  BIOFUEL: 'Biofuels',
  RFNBO: 'RFNBO e-fuels',
};

export const FUEL_TYPE_SELECT_ITEMS: GovukSelectOption<FuelType>[] = [
  { value: 'HFO', text: 'Heavy Fuel Oil (HFO)' },
  { value: 'LFO', text: 'Light Fuel Oil (LFO)' },
  { value: 'MDO', text: 'Diesel Oil (MDO)' },
  { value: 'MGO', text: 'Gas Oil (MGO)' },
  { value: 'LNG', text: 'Liquified Natural Gas (LNG)' },
  { value: 'LPG_BUTANE', text: 'Liquified Petroleum Gas (Butane, LPG)' },
  { value: 'LPG_PROPANE', text: 'Liquified Petroleum Gas (Propane, LPG)' },
  { value: 'H2', text: 'H2 (Fossil)' },
  { value: 'NH3', text: 'NH3 (Fossil)' },
  { value: 'METHANOL', text: 'Methanol (Fossil)' },
  { value: 'ETHANOL', text: 'Ethanol' },
  { value: 'BIO_DIESEL', text: 'Bio-diesel' },
  { value: 'HVO', text: 'Hydro Treated Vegetable Oil (HVO)' },
  { value: 'BIO_LNG', text: 'Liquified bio-methane as transport fuel (Bio-LNG)' },
  { value: 'BIO_METHANOL', text: 'Bio-methanol' },
  { value: 'BIO_H2', text: 'Bio-H2' },
  { value: 'E_DIESEL', text: 'e-diesel' },
  { value: 'E_METHANOL', text: 'e-methanol' },
  { value: 'E_LNG', text: 'e-LNG' },
  { value: 'E_H2', text: 'e-H2' },
  { value: 'E_NH3', text: 'e-NH3' },
  { value: 'E_LPG', text: 'e-LPG' },
  { value: 'E_DME', text: 'e-DME' },
];

export const FUEL_TYPES_BY_ORIGIN: Record<FuelOriginTypeName['origin'], GovukSelectOption<FuelType>[]> = {
  FOSSIL: [
    ...FUEL_TYPE_SELECT_ITEMS.filter((item) =>
      ['HFO', 'LFO', 'MDO', 'MGO', 'LNG', 'LPG_BUTANE', 'LPG_PROPANE', 'H2', 'NH3', 'METHANOL'].includes(item.value),
    ),
    {
      value: 'OTHER',
      text: 'Other Fossil Fuel',
    },
  ],
  RFNBO: [
    ...FUEL_TYPE_SELECT_ITEMS.filter((item) =>
      ['E_DIESEL', 'E_METHANOL', 'E_LNG', 'E_H2', 'E_NH3', 'E_LPG', 'E_DME'].includes(item.value),
    ),
    {
      value: 'OTHER',
      text: 'Other e-fuel',
    },
  ],
  BIOFUEL: [
    ...FUEL_TYPE_SELECT_ITEMS.filter((item) =>
      ['ETHANOL', 'BIO_DIESEL', 'HVO', 'BIO_LNG', 'BIO_METHANOL', 'BIO_H2'].includes(item.value),
    ),
    {
      value: 'OTHER',
      text: 'Other Biofuel',
    },
  ],
};

export const DENSITY_METHOD_BUNKER_SELECT_ITEMS: GovukSelectOption<
  EmpFuelsAndEmissionsFactors['densityMethodBunker']
>[] = [
  { value: 'NA', text: 'Not applicable' },
  { value: 'ON_BOARD_MEASUREMENT_SYSTEMS', text: 'On-board measurement equipment' },
  { value: 'FUEL_SUPPLIER', text: 'Fuel supplier' },
  { value: 'LABORATORY_TEST', text: 'Laboratory test' },
];

export const DENSITY_METHOD_TANK_SELECT_ITEMS: GovukSelectOption<EmpFuelsAndEmissionsFactors['densityMethodTank']>[] = [
  { value: 'NA', text: 'Not applicable' },
  { value: 'MEASUREMENT_SYSTEMS', text: 'Measurement equipment' },
  { value: 'FUEL_SUPPLIER', text: 'Fuel supplier' },
  { value: 'LABORATORY_TEST', text: 'Laboratory test' },
];

export const monitoringMethodMap: Record<
  'BDN' | 'BUNKER_TANK' | 'FLOW_METERS' | 'DIRECT',
  {
    text: string;
    hint: string;
  }
> = {
  BDN: { text: 'Method A', hint: 'Bunker Delivery Note (BDN) and periodic stocktakes of fuel tanks' },
  BUNKER_TANK: { text: 'Method B', hint: 'Bunker fuel tank monitoring on-board' },
  FLOW_METERS: { text: 'Method C', hint: 'Flow meters for applicable combustion processes' },
  DIRECT: { text: 'Method D', hint: 'Direct CO2 emissions measurement' },
};

export const EMISSION_SOURCES_TYPE_SELECT_ITEMS: GovukSelectOption<EmissionsSources['type']>[] = [
  { value: 'MAIN_ENGINE', text: 'Main engines' },
  { value: 'AUX_ENGINE', text: 'Auxiliary engines' },
  { value: 'GAS_TURBINE', text: 'Gas turbines' },
  { value: 'BOILER', text: 'Boilers' },
  { value: 'INERT_GAS_GENERATOR', text: 'Inert gas generators' },
  { value: 'FUEL_CELLS', text: 'Fuel cells' },
  { value: 'WASTE_INCINERATOR', text: 'Waste incinerators' },
  { value: 'OTHER', text: 'Other' },
];

export const EMISSION_SOURCES_METHANE_SLIP_SELECT_ITEMS: GovukSelectOption<
  FuelOriginTypeName['methaneSlip'] | FuelOriginTypeName['methaneSlipValueType']
>[] = [
  { value: '0', text: '0' },
  { value: '3.1', text: '3.1' },
  { value: '1.7', text: '1.7' },
  { value: '0.2', text: '0.2' },
  { value: '2.6', text: '2.6' },
  { value: 'OTHER', text: 'Other' },
];

export const EMISSION_SOURCES_SOURCE_CLASS_SELECT_ITEMS: GovukSelectOption<EmissionsSources['sourceClass']>[] = [
  { value: 'BOILERS', text: 'Boilers' },
  { value: 'FUEL_CELLS', text: 'Fuel Cells' },
  { value: 'GAS_TURBINE', text: 'Gas Turbine' },
  { value: 'ICE', text: 'ICE' },
  { value: 'INERT_GAS_GENERATOR', text: 'Inert gas generators' },
  { value: 'LNG_DIESEL_DFSS', text: 'LNG Diesel (DFSS)' },
  { value: 'LNG_LBSI', text: 'LNG (LBSI)' },
  { value: 'LNG_OTTO_DFMS', text: 'LNG Otto (DFMS)' },
  { value: 'LNG_OTTO_DFSS', text: 'LNG Otto (DFSS)' },
  { value: 'WASTE_INCINERATORS', text: 'Waste incinerators' },
];

export const METHOD_APPROACH_SELECT_OPTIONS: GovukSelectOption<UncertaintyLevel['methodApproach']>[] = [
  {
    value: 'DEFAULT',
    text: 'Default',
  },
  {
    value: 'SHIP_SPECIFIC',
    text: 'Ship specific',
  },
];
