import { MrtmRequestTaskActionType, MrtmRequestTaskType } from '@shared/types';

export const taskActionTypeToUploadSectionTaskActionTypeMap: Record<MrtmRequestTaskType, MrtmRequestTaskActionType> = {
  EMP_ISSUANCE_APPLICATION_SUBMIT: 'EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT',
  EMP_ISSUANCE_APPLICATION_REVIEW: 'EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT',
  EMP_VARIATION_APPLICATION_SUBMIT: 'EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT',
  EMP_VARIATION_APPLICATION_REVIEW: 'EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT',
  EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT: 'EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT',
  EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT: 'EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT',
  EMP_VARIATION_APPLICATION_AMENDS_SUBMIT: 'EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT',
  AER_APPLICATION_SUBMIT: 'AER_UPLOAD_SECTION_ATTACHMENT',
  DOE_APPLICATION_SUBMIT: 'DOE_UPLOAD_ATTACHMENT',
  VIR_APPLICATION_SUBMIT: 'VIR_UPLOAD_ATTACHMENT',
  VIR_APPLICATION_REVIEW: 'VIR_UPLOAD_ATTACHMENT',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE: 'NON_COMPLIANCE_UPLOAD_ATTACHMENT',
  NON_COMPLIANCE_NOTICE_OF_INTENT: 'NON_COMPLIANCE_UPLOAD_ATTACHMENT',
  AER_APPLICATION_AMENDS_SUBMIT: 'AER_UPLOAD_SECTION_ATTACHMENT',
  // TODO proper resolve with requestTypeUploadActionMap
  // TODO proper mapping for the following MrtmRequestTaskActionType
  //   'EMP_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT'
  //   'EMP_NOTIFICATION_UPLOAD_SECTION_ATTACHMENT'
  //   'EMP_NOTIFICATION_FOLLOW_UP_UPLOAD_ATTACHMENT'
  //   'EMP_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT'
};
