export enum EmissionSourceClassCodeEnum {
  BOILERS = 'BOILERS',
  FUEL_CELLS = 'FUEL_CELLS',
  GAS_TURBINE = 'GAS_TURBINE',
  ICE = 'ICE',
  INERT_GAS_GENERATOR = 'INERT_GAS_GENERATOR',
  LNG_DIESEL_DFSS = 'LNG_DIESEL_DFSS',
  LNG_LBSI = 'LNG_LBSI',
  LNG_OTTO_DFMS = 'LNG_OTTO_DFMS',
  LNG_OTTO_DFSS = 'LNG_OTTO_DFSS',
  WASTE_INCINERATORS = 'WASTE_INCINERATORS',
}
