export enum EmissionSourceTypeCodeEnum {
  MAIN_ENGINE = 'MAIN_ENGINE',
  AUX_ENGINE = 'AUX_ENGINE',
  GAS_TURBINE = 'GAS_TURBINE',
  BOILER = 'BOILER',
  INERT_GAS_GENERATOR = 'INERT_GAS_GENERATOR',
  FUEL_CELLS = 'FUEL_CELLS',
  WASTE_INCINERATOR = 'WASTE_INCINERATOR',
  OTHER = 'OTHER',
}
