export enum FuelTypeCodeEnum {
  HFO = 'HFO',
  LFO = 'LFO',
  MDO = 'MDO',
  MGO = 'MGO',
  LNG = 'LNG',
  LPG_BUTANE = 'LPG_BUTANE',
  LPG_PROPANE = 'LPG_PROPANE',
  H2 = 'H2',
  NH3 = 'NH3',
  METHANOL = 'METHANOL',
  ETHANOL = 'ETHANOL',
  BIO_DIESEL = 'BIO_DIESEL',
  HVO = 'HVO',
  BIO_LNG = 'BIO_LNG',
  BIO_METHANOL = 'BIO_METHANOL',
  BIO_H2 = 'BIO_H2',
  E_DIESEL = 'E_DIESEL',
  E_METHANOL = 'E_METHANOL',
  E_LNG = 'E_LNG',
  E_H2 = 'E_H2',
  E_NH3 = 'E_NH3',
  E_LPG = 'E_LPG',
  E_DME = 'E_DME',
  OTHER = 'OTHER',
}
