export enum ShipTypeEnum {
  BULK = 'BULK',
  RORO = 'RORO',
  CONT = 'CONT',
  OIL = 'OIL',
  CHEM = 'CHEM',
  LNG = 'LNG',
  GAS = 'GAS',
  PAX = 'PAX',
  GENERAL = 'GENERAL',
  RCV = 'RCV',
  VEH = 'VEH',
  COMB = 'COMB',
  ROPAX = 'ROPAX',
  CONT_RORO = 'CONT_RORO',
  CRUISE = 'CRUISE',
  OFFSHORE = 'OFFSHORE',
  OTHER = 'OTHER',
}
