package uk.gov.mrtm.api.reporting.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.mrtm.api.reporting.domain.ports.AerPortVisit;

@AllArgsConstructor
public enum PortCountries {
    AF("Afghanistan", PortType.INTERNATIONAL, false),
    AL("Albania", PortType.INTERNATIONAL, false),
    DZ("Algeria", PortType.INTERNATIONAL, true),
    AS("American Samoa (USA)", PortType.INTERNATIONAL, false),
    AD("Andorra", PortType.INTERNATIONAL, false),
    AO("Angola", PortType.INTERNATIONAL, false),
    AI("Anguilla, UK", PortType.INTERNATIONAL, false),
    AG("Antigua and Barbuda", PortType.INTERNATIONAL, false),
    AR("Argentina", PortType.INTERNATIONAL, false),
    AM("Armenia", PortType.INTERNATIONAL, false),
    AW("Aruba (NL)", PortType.INTERNATIONAL, false),
    AU("Australia", PortType.INTERNATIONAL, false),
    AT("Austria", PortType.EU, false),
    AZ("Azerbaijan", PortType.INTERNATIONAL, false),
    BS("Bahamas", PortType.INTERNATIONAL, false),
    BH("Bahrain", PortType.INTERNATIONAL, false),
    BD("Bangladesh", PortType.INTERNATIONAL, false),
    BB("Barbados", PortType.INTERNATIONAL, false),
    BY("Belarus", PortType.INTERNATIONAL, false),
    BE("Belgium", PortType.EU, true),
    BZ("Belize", PortType.INTERNATIONAL, false),
    BJ("Benin", PortType.INTERNATIONAL, false),
    BM("Bermuda, UK", PortType.INTERNATIONAL, true),
    BO("Bolivia", PortType.INTERNATIONAL, false),
    BA("Bosnia and Herzegovina", PortType.INTERNATIONAL, false),
    BR("Brazil", PortType.INTERNATIONAL, false),
    VG("British Virgin Islands, UK", PortType.INTERNATIONAL, false),
    BN("Brunei Darussalam", PortType.INTERNATIONAL, false),
    BG("Bulgaria", PortType.EU, true),
    BI("Burundi", PortType.INTERNATIONAL, false),
    KH("Cambodia", PortType.INTERNATIONAL, false),
    CM("Cameroon", PortType.INTERNATIONAL, false),
    CA("Canada", PortType.INTERNATIONAL, true),
    CV("Cape Verde", PortType.INTERNATIONAL, false),
    KY("Cayman Islands, UK", PortType.INTERNATIONAL, false),
    CL("Chile", PortType.INTERNATIONAL, false),
    CN("China", PortType.INTERNATIONAL, false),
    CO("Colombia", PortType.INTERNATIONAL, false),
    KM("Comoros", PortType.INTERNATIONAL, false),
    CG("Congo", PortType.INTERNATIONAL, false),
    CD("Congo, the Democratic Republic of the", PortType.INTERNATIONAL, false),
    CK("Cook Islands", PortType.INTERNATIONAL, false),
    CR("Costa Rica", PortType.INTERNATIONAL, false),
    CI("Cote d'Ivoire", PortType.INTERNATIONAL, false),
    HR("Croatia", PortType.EU, true),
    CU("Cuba", PortType.INTERNATIONAL, true),
    AN("Curacao", PortType.INTERNATIONAL, false),
    CY("Cyprus", PortType.EU, true),
    CZ("Czech Republic", PortType.EU, false),
    DK("Denmark", PortType.EU, true),
    DJ("Djibouti", PortType.INTERNATIONAL, false),
    DM("Dominica", PortType.INTERNATIONAL, false),
    DO("Dominican Republic", PortType.INTERNATIONAL, false),
    EC("Ecuador", PortType.INTERNATIONAL, false),
    EG("Egypt", PortType.INTERNATIONAL, true),
    SV("El Salvador", PortType.INTERNATIONAL, false),
    GQ("Equatorial Guinea", PortType.INTERNATIONAL, false),
    ER("Eritrea", PortType.INTERNATIONAL, false),
    EE("Estonia", PortType.EU, true),
    ET("Ethiopia", PortType.INTERNATIONAL, false),
    FK("Falkland Islands, UK (Malvinas)", PortType.INTERNATIONAL, false),
    FO("Faroe Islands", PortType.INTERNATIONAL, false),
    FJ("Fiji", PortType.INTERNATIONAL, false),
    FI("Finland", PortType.EU, true),
    FR("France", PortType.EU, true),
    PF("French Polynesia (FR)", PortType.INTERNATIONAL, false),
    GA("Gabon", PortType.INTERNATIONAL, false),
    GM("Gambia", PortType.INTERNATIONAL, false),
    GE("Georgia", PortType.INTERNATIONAL, true),
    DE("Germany", PortType.EU, true),
    GH("Ghana", PortType.INTERNATIONAL, false),
    GI("Gibraltar, UK", PortType.INTERNATIONAL, true),
    GR("Greece", PortType.EU, true),
    GD("Grenada", PortType.INTERNATIONAL, false),
    GT("Guatemala", PortType.INTERNATIONAL, false),
    GG("Guernsey, UK", PortType.INTERNATIONAL, false),
    GN("Guinea", PortType.INTERNATIONAL, false),
    GW("Guinea-Bissau", PortType.INTERNATIONAL, false),
    GY("Guyana", PortType.INTERNATIONAL, false),
    HT("Haiti", PortType.INTERNATIONAL, false),
    HN("Honduras", PortType.INTERNATIONAL, false),
    HU("Hungary", PortType.EU, false),
    IS("Iceland", PortType.INTERNATIONAL, true),
    IN("India", PortType.INTERNATIONAL, false),
    ID("Indonesia", PortType.INTERNATIONAL, false),
    IR("Iran, Islamic Republic of", PortType.INTERNATIONAL, false),
    IQ("Iraq", PortType.INTERNATIONAL, false),
    IE("Ireland", PortType.EU, true),
    IM("Isle of Man, UK", PortType.INTERNATIONAL, true),
    IL("Israel", PortType.INTERNATIONAL, false),
    IT("Italy", PortType.EU, true),
    JM("Jamaica", PortType.INTERNATIONAL, false),
    JP("Japan", PortType.INTERNATIONAL, false),
    JE("Jersey, UK", PortType.INTERNATIONAL, false),
    JO("Jordan", PortType.INTERNATIONAL, false),
    KZ("Kazakhstan", PortType.INTERNATIONAL, false),
    KE("Kenya", PortType.INTERNATIONAL, false),
    KI("Kiribati", PortType.INTERNATIONAL, false),
    KP("Korea, Democratic People's Republic of", PortType.INTERNATIONAL, false),
    KR("Korea, Republic of", PortType.INTERNATIONAL, false),
    KW("Kuwait", PortType.INTERNATIONAL, false),
    KG("Kyrgyzstan", PortType.INTERNATIONAL, false),
    LA("Lao People's Democratic Republic", PortType.INTERNATIONAL, false),
    LV("Latvia", PortType.EU, true),
    LB("Lebanon", PortType.INTERNATIONAL, false),
    LR("Liberia", PortType.INTERNATIONAL, false),
    LY("Libya", PortType.INTERNATIONAL, false),
    LI("Liechtenstein", PortType.INTERNATIONAL, false),
    LT("Lithuania", PortType.EU, true),
    LU("Luxembourg", PortType.EU, false),
    MK("Macedonia, Former Yugoslav Republic of", PortType.INTERNATIONAL, false),
    MG("Madagascar", PortType.INTERNATIONAL, false),
    MW("Malawi", PortType.INTERNATIONAL, false),
    MY("Malaysia", PortType.INTERNATIONAL, false),
    MV("Maldives", PortType.INTERNATIONAL, false),
    ML("Mali", PortType.INTERNATIONAL, false),
    MT("Malta", PortType.EU, true),
    MH("Marshall Islands", PortType.INTERNATIONAL, false),
    MR("Mauritania", PortType.INTERNATIONAL, false),
    MU("Mauritius", PortType.INTERNATIONAL, false),
    MX("Mexico", PortType.INTERNATIONAL, false),
    FM("Micronesia, Federated States of", PortType.INTERNATIONAL, false),
    MD("Moldova, Republic of", PortType.INTERNATIONAL, false),
    MC("Monaco", PortType.INTERNATIONAL, false),
    MN("Mongolia", PortType.INTERNATIONAL, false),
    ME("Montenegro", PortType.INTERNATIONAL, true),
    MS("Montserrat, UK", PortType.INTERNATIONAL, false),
    MA("Morocco", PortType.INTERNATIONAL, true),
    MZ("Mozambique", PortType.INTERNATIONAL, false),
    MM("Myanmar", PortType.INTERNATIONAL, false),
    NA("Namibia", PortType.INTERNATIONAL, false),
    NR("Nauru", PortType.INTERNATIONAL, false),
    NL("Netherlands", PortType.EU, true),
    NZ("New Zealand", PortType.INTERNATIONAL, false),
    NI("Nicaragua", PortType.INTERNATIONAL, false),
    NE("Niger", PortType.INTERNATIONAL, false),
    NG("Nigeria", PortType.INTERNATIONAL, false),
    NU("Niue", PortType.INTERNATIONAL, false),
    NO("Norway", PortType.INTERNATIONAL, true),
    OM("Oman", PortType.INTERNATIONAL, false),
    PK("Pakistan", PortType.INTERNATIONAL, false),
    PW("Palau", PortType.INTERNATIONAL, false),
    PS("Palestine, State of", PortType.INTERNATIONAL, false),
    PA("Panama", PortType.INTERNATIONAL, false),
    PG("Papua New Guinea", PortType.INTERNATIONAL, false),
    PY("Paraguay", PortType.INTERNATIONAL, false),
    PE("Peru", PortType.INTERNATIONAL, false),
    PH("Philippines", PortType.INTERNATIONAL, false),
    PL("Poland", PortType.EU, true),
    PT("Portugal", PortType.EU, true),
    QA("Qatar", PortType.INTERNATIONAL, false),
    RO("Romania", PortType.EU, true),
    RU("Russian Federation", PortType.INTERNATIONAL, true),
    RW("Rwanda", PortType.INTERNATIONAL, false),
    BL("Saint Barthélemy", PortType.INTERNATIONAL, false),
    KN("Saint Kitts and Nevis", PortType.INTERNATIONAL, false),
    LC("Saint Lucia", PortType.INTERNATIONAL, false),
    PM("Saint Pierre and Miquelon", PortType.INTERNATIONAL, false),
    VC("Saint Vincent and the Grenadines", PortType.INTERNATIONAL, false),
    WS("Samoa", PortType.INTERNATIONAL, false),
    ST("Sao Tome and Principe", PortType.INTERNATIONAL, false),
    SA("Saudi Arabia", PortType.INTERNATIONAL, true),
    SN("Senegal", PortType.INTERNATIONAL, false),
    RS("Serbia", PortType.INTERNATIONAL, false),
    SC("Seychelles", PortType.INTERNATIONAL, false),
    SL("Sierra Leone", PortType.INTERNATIONAL, false),
    SG("Singapore", PortType.INTERNATIONAL, false),
    SK("Slovakia", PortType.EU, false),
    SI("Slovenia", PortType.EU, true),
    SB("Solomon Islands", PortType.INTERNATIONAL, false),
    SO("Somalia", PortType.INTERNATIONAL, false),
    ZA("South Africa", PortType.INTERNATIONAL, false),
    SS("South Sudan", PortType.INTERNATIONAL, false),
    ES("Spain", PortType.EU, true),
    LK("Sri Lanka", PortType.INTERNATIONAL, false),
    SX("St Maarten", PortType.INTERNATIONAL, false),
    SH("St. Helena, Ascension and Tristan Da Cunha, UK", PortType.INTERNATIONAL, false),
    SD("Sudan", PortType.INTERNATIONAL, false),
    SR("Suriname", PortType.INTERNATIONAL, false),
    SE("Sweden", PortType.EU, true),
    CH("Switzerland", PortType.INTERNATIONAL, false),
    SY("Syrian Arab Republic", PortType.INTERNATIONAL, false),
    TW("Taiwan, Province of China", PortType.INTERNATIONAL, false),
    TJ("Tajikistan", PortType.INTERNATIONAL, false),
    TZ("Tanzania, United Republic of", PortType.INTERNATIONAL, false),
    TH("Thailand", PortType.INTERNATIONAL, false),
    TL("Timor-Leste", PortType.INTERNATIONAL, false),
    TG("Togo", PortType.INTERNATIONAL, false),
    TO("Tonga", PortType.INTERNATIONAL, false),
    TT("Trinidad and Tobago", PortType.INTERNATIONAL, false),
    TN("Tunisia", PortType.INTERNATIONAL, true),
    TR("Turkey", PortType.INTERNATIONAL, false),
    TM("Turkmenistan", PortType.INTERNATIONAL, false),
    TC("Turks and Caicos Islands, UK", PortType.INTERNATIONAL, false),
    TV("Tuvalu", PortType.INTERNATIONAL, false),
    UG("Uganda", PortType.INTERNATIONAL, false),
    UA("Ukraine", PortType.INTERNATIONAL, false),
    AE("United Arab Emirates", PortType.INTERNATIONAL, false),
    GB("United Kingdom", PortType.GB, true),
    US("United States", PortType.INTERNATIONAL, true),
    UY("Uruguay", PortType.INTERNATIONAL, false),
    UZ("Uzbekistan", PortType.INTERNATIONAL, false),
    VU("Vanuatu", PortType.INTERNATIONAL, false),
    VE("Venezuela", PortType.INTERNATIONAL, false),
    VN("Vietnam", PortType.INTERNATIONAL, false),
    YE("Yemen", PortType.INTERNATIONAL, false),
    ZM("Zambia", PortType.INTERNATIONAL, false),
    ZW("Zimbabwe", PortType.INTERNATIONAL, false);

    @Getter
    private final String name;
    private final PortType type;
    @Getter
    private final boolean hasPorts;

    public PortType getType(AerPortVisit visit) {
        PortCodesNorthernIreland portCodeNI = PortCodesNorthernIreland.fromString(visit.getPort());

        if (portCodeNI != null) {
            return PortType.NI;
        }

        return visit.getCountry().type;
    }

}
