package uk.gov.mrtm.api.reporting.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PortCodes2 {
    GRAMR("Agia Marina Aiginas", PortCountries.GR),
    GRAND("Andros", PortCountries.GR),
    GRANI("Agios Nikolaos, Kriti", PortCountries.GR),
    GRANL("Agnontas Skopelou", PortCountries.GR),
    GRANP("Antiparos", PortCountries.GR),
    GRANT("Andirrion", PortCountries.GR),
    GRAOK("Karpathos", PortCountries.GR),
    GRAOR("Agiokampos Oreon", PortCountries.GR),
    GRAPE("Agia Pelagia", PortCountries.GR),
    GRAPL("Amaliapolis", PortCountries.GR),
    GRARD("Arkioi Dodekanissou", PortCountries.GR),
    GRARK("Arkitsa", PortCountries.GR),
    GRARM("Argostolion", PortCountries.GR),
    GRARS("Astros", PortCountries.GR),
    GRASS("Aspropirgos", PortCountries.GR),
    GRAST("Astakos", PortCountries.GR),
    GRATK("Antikyra", PortCountries.GR),
    GRATL("Atherinolakos Siteias", PortCountries.GR),
    GRAVA("Avlida", PortCountries.GR),
    GRAXD("Alexandroupolis", PortCountries.GR),
    GRCFU("Kerkira (Corfu)", PortCountries.GR),
    GRCHQ("Chanea", PortCountries.GR),
    GRCLK("Chalkida", PortCountries.GR),
    GRCSF("Khora Sfakion", PortCountries.GR),
    GRDAF("Dafni", PortCountries.GR),
    GRDIA("Diafani", PortCountries.GR),
    GRDIK("Diakofti Kythiron", PortCountries.GR),
    GRDON("Donousa Kykladon", PortCountries.GR),
    GRDOS("Delos", PortCountries.GR),
    GRDRE("Drepanon", PortCountries.GR),
    GREDI("Edipsos", PortCountries.GR),
    GREEU("Eleusis", PortCountries.GR),
    GRELE("Eleusina (Elefsis)", PortCountries.GR),
    GRELN("Elafonissos Lakonias", PortCountries.GR),
    GRELT("Eleftheres", PortCountries.GR),
    GREPI("Epidavros", PortCountries.GR),
    GRERE("Eretria", PortCountries.GR),
    GRERK("Ereikousses Diapontioi Islands", PortCountries.GR),
    GRERM("Ermioni", PortCountries.GR),
    GREYD("Eydilos", PortCountries.GR),
    GRFAM("Farmakonissi Dodekanissou", PortCountries.GR),
    GRFIS("Fiskardo", PortCountries.GR),
    GRFLS("Eleusis", PortCountries.GR),
    GRFOL("Folegandros", PortCountries.GR),
    GRFOU("Fournoi", PortCountries.GR),
    GRGAD("Gavdos", PortCountries.GR),
    GRGAV("Gavrion", PortCountries.GR),
    GRGFD("Glyfada", PortCountries.GR),
    GRGLO("Glossa", PortCountries.GR),
    GRGLX("Galaxidi", PortCountries.GR),
    GRGLY("Glyfa Fthiotidas", PortCountries.GR),
    GRGMA("Agia Marina Grammatikou", PortCountries.GR),
    GRGPA("Patras", PortCountries.GR),
    GRGYT("Gythion", PortCountries.GR),
    GRHAL("Halki", PortCountries.GR),
    GRHER("Heraclion (Crete)", PortCountries.GR),
    GRHRK("Herakleia Kykladon", PortCountries.GR),
    GRHYD("Hydra", PortCountries.GR),
    GRIER("Ierapetra", PortCountries.GR),
    GRIGO("Igoumenitsa", PortCountries.GR),
    GRINO("Inousses", PortCountries.GR),
    GRIOS("Ios", PortCountries.GR),
    GRIRA("Iráklia", PortCountries.GR),
    GRITA("Itea", PortCountries.GR),
    GRITH("Ithaki (Ithaca)", PortCountries.GR),
    GRJKH("Chios", PortCountries.GR),
    GRJMK("Mykonos", PortCountries.GR),
    GRJNX("Naxos", PortCountries.GR),
    GRJSH("Siteia", PortCountries.GR),
    GRJSI("Skiathos", PortCountries.GR),
    GRJSY("Syros (Syra)", PortCountries.GR),
    GRJTR("Thira", PortCountries.GR),
    GRJTY("Astypalaia", PortCountries.GR),
    GRKAG("Karkinagri Samou", PortCountries.GR),
    GRKAI("Kalamos Island (Lefkada)", PortCountries.GR),
    GRKAK("Katakolon", PortCountries.GR),
    GRKAP("Kapsalion (Kythira)", PortCountries.GR),
    GRKAR("Neon Karlovasion", PortCountries.GR),
    GRKAS("Kastellorizou (ex Megisti)", PortCountries.GR),
    GRKDM("Kardamyla", PortCountries.GR),
    GRKEA("Kea", PortCountries.GR),
    GRKEF("Kefalos Ko", PortCountries.GR),
    GRKEI("Skala Katerinis", PortCountries.GR),
    GRKEM("Kosta Ermionidas", PortCountries.GR),
    GRKER("Keramoti", PortCountries.GR),
    GRKGS("Kos", PortCountries.GR),
    GRKIM("Kimi", PortCountries.GR),
    GRKIN("Koilas Ermionidos", PortCountries.GR),
    GRKIO("Kiato", PortCountries.GR),
    GRKIP("Kiparissia", PortCountries.GR),
    GRKIS("Kastelli Kissamou", PortCountries.GR),
    GRKLD("Kalathos Rodou", PortCountries.GR),
    GRKLL("Kalilimenes", PortCountries.GR),
    GRKLM("Kalamaki", PortCountries.GR),
    GRKLX("Kalamata", PortCountries.GR),
    GRKMI("Kalymnos", PortCountries.GR),
    GRKMS("Kimolos", PortCountries.GR),
    GRKOF("Koufonissia Kykladon", PortCountries.GR),
    GRKRE("Kamares Sifnos", PortCountries.GR),
    GRKRM("Kardamaina Kos", PortCountries.GR),
    GRKRT("Korinthos", PortCountries.GR),
    GRKSI("Katsos Island", PortCountries.GR),
    GRKSJ("Kassos", PortCountries.GR),
    GRKSK("Kamiros Skala", PortCountries.GR),
    GRKST("Karystos", PortCountries.GR),
    GRKTP("Katapola", PortCountries.GR),
    GRKVA("Kavala", PortCountries.GR),
    GRKYL("Killini", PortCountries.GR),
    GRKYM("Kymassi Mantoudiou", PortCountries.GR),
    GRKYT("Kythnos", PortCountries.GR),
    GRLAR("Lardos", PortCountries.GR),
    GRLAV("Lavrion (Laurium)", PortCountries.GR),
    GRLDR("Lindos Rodou", PortCountries.GR),
    GRLEF("Lefkandi", PortCountries.GR),
    GRLEV("Lefkada (Lefkas)", PortCountries.GR),
    GRLFK("Lefkimmi", PortCountries.GR),
    GRLGA("Lagkada", PortCountries.GR),
    GRLIA("Skiros (Linaria)", PortCountries.GR),
    GRLII("Limni", PortCountries.GR),
    GRLIN("Linoperamata Hrakliou", PortCountries.GR),
    GRLIP("Lipsoi", PortCountries.GR),
    GRLIX("Lixuri", PortCountries.GR),
    GRLND("Leonidion", PortCountries.GR),
    GRLRY("Larymna", PortCountries.GR),
    GRLTR("Loutro Chanion", PortCountries.GR),
    GRLVR("Aliverio", PortCountries.GR),
    GRMDR("Moudros", PortCountries.GR),
    GRMEA("Methana", PortCountries.GR),
    GRMEL("Mesolongion", PortCountries.GR),
    GRMEN("Menidi", PortCountries.GR),
    GRMGN("Meganisi", PortCountries.GR),
    GRMHI("Mesta Hiou", PortCountries.GR),
    GRMJT("Mytilene", PortCountries.GR),
    GRMKP("Marathokampos Samou", PortCountries.GR),
    GRMLO("Milos", PortCountries.GR),
    GRMOL("Molyvos", PortCountries.GR),
    GRMON("Monemvasia", PortCountries.GR),
    GRMRM("Marmari", PortCountries.GR),
    GRMRN("Marmárion", PortCountries.GR),
    GRMTR("Mathraki Diapontioi Island", PortCountries.GR),
    GRMXK("Mastichari Kos", PortCountries.GR),
    GRMYL("Mylaki", PortCountries.GR),
    GRMYR("Mirina", PortCountries.GR),
    GRNAF("Nafplion", PortCountries.GR),
    GRNAR("Nea Artaki", PortCountries.GR),
    GRNAS("Naoussa Parou", PortCountries.GR),
    GRNEA("Neapolis", PortCountries.GR),
    GRNID("Nidhrion", PortCountries.GR),
    GRNIS("Nisiros", PortCountries.GR),
    GRNKV("Nea Karvali", PortCountries.GR),
    GRNMA("Nea Moudhania", PortCountries.GR),
    GRNPK("Navpaktos", PortCountries.GR),
    GRNST("Nea Stira", PortCountries.GR),
    GRORE("Orei", PortCountries.GR),
    GRORO("Oropos", PortCountries.GR),
    GROTH("Othonoi", PortCountries.GR),
    GROUR("Ouranopolis", PortCountries.GR),
    GRPAA("Palaia Psara", PortCountries.GR),
    GRPAR("Parga", PortCountries.GR),
    GRPAS("Paros", PortCountries.GR),
    GRPAX("Paxi", PortCountries.GR),
    GRPCH("Paleochora", PortCountries.GR),
    GRPER("Perama", PortCountries.GR),
    GRPFA("Palaia Fokaia", PortCountries.GR),
    GRPGM("Perama Geras Mytilinis", PortCountries.GR),
    GRPHE("Porto Heli", PortCountries.GR),
    GRPIL("Agia Galini", PortCountries.GR),
    GRPIR("Piraeus", PortCountries.GR),
    GRPIS("Pisaetos Ithakis", PortCountries.GR),
    GRPKE("Poros Kefallinias", PortCountries.GR),
    GRPKK("Lakkion", PortCountries.GR),
    GRPLC("Polychnitos Lesvou", PortCountries.GR),
    GRPLG("Playgiali Etoloakarnanias", PortCountries.GR),
    GRPLM("Plomarion", PortCountries.GR),
    GRPME("Pachi", PortCountries.GR),
    GRPMS("Patmos", PortCountries.GR),
    GRPOA("Potamos Antikithera", PortCountries.GR),
    GRPPI("Prinos Thassou", PortCountries.GR),
    GRPRE("Petries Evvoias", PortCountries.GR),
    GRPSA("Psakhna", PortCountries.GR),
    GRPSE("Phserimos Dodekanisou", PortCountries.GR),
    GRPSK("Pessada Keffalinias", PortCountries.GR),
    GRPTI("Plataria", PortCountries.GR),
    GRPTL("Porto Lagos", PortCountries.GR),
    GRPTR("Poros Trizinias", PortCountries.GR),
    GRPVK("Preveza/Lefkas", PortCountries.GR),
    GRPYL("Pylos", PortCountries.GR),
    GRPYT("Pythagoreion", PortCountries.GR),
    GRPYV("Peyki Evvoias", PortCountries.GR),
    GRQKG("Chalkis", PortCountries.GR),
    GRRAF("Rafina", PortCountries.GR),
    GRRET("Rethimnon", PortCountries.GR),
    GRREV("Revithousa", PortCountries.GR),
    GRRHO("Rhodes", PortCountries.GR),
    GRRIO("Rio", PortCountries.GR),
    GRROU("Agia Roumeli", PortCountries.GR),
    GRSAI("Sami", PortCountries.GR),
    GRSAL("Salamis", PortCountries.GR),
    GRSAM("Samothraki", PortCountries.GR),
    GRSAT("Frikes Ithakis", PortCountries.GR),
    GRSDH("Souda", PortCountries.GR),
    GRSER("Seriphos", PortCountries.GR),
    GRSGR("Sigri Lesvou", PortCountries.GR),
    GRSGT("Sagiada Thesprotias", PortCountries.GR),
    GRSHA("Stavros Halkidikis", PortCountries.GR),
    GRSHC("Schinousa Kykladon", PortCountries.GR),
    GRSHI("Shinari Zakynthou (Agios Nikolaos)", PortCountries.GR),
    GRSII("Sikinos", PortCountries.GR),
    GRSKA("Skaramangas", PortCountries.GR),
    GRSKG("Thessaloniki", PortCountries.GR),
    GRSKO("Skopelos", PortCountries.GR),
    GRSLA("Souvala", PortCountries.GR),
    GRSMI("Samos", PortCountries.GR),
    GRSOG("Sougia Chanion", PortCountries.GR),
    GRSOI("Soroni", PortCountries.GR),
    GRSOU("Soussaki", PortCountries.GR),
    GRSPE("Spetsai", PortCountries.GR),
    GRSTI("Stratoni", PortCountries.GR),
    GRSTN("Saint Nicolas", PortCountries.GR),
    GRSYM("Symi", PortCountries.GR),
    GRSYS("Stylis", PortCountries.GR),
    GRSYV("Syvota", PortCountries.GR),
    GRTHI("Thísvi", PortCountries.GR),
    GRTHM("Thymaina Island", PortCountries.GR),
    GRTHP("Thisvi", PortCountries.GR),
    GRTIL("Tilos", PortCountries.GR),
    GRTIN("Tinos", PortCountries.GR),
    GRTLA("Tolo Argolidos", PortCountries.GR),
    GRTRY("Trypiti Chalkidikis", PortCountries.GR),
    GRTSI("Tsiggelion", PortCountries.GR),
    GRTSO("Thasos", PortCountries.GR),
    GRVAT("Vathi", PortCountries.GR),
    GRVLC("Volissos (Limnia) Chios", PortCountries.GR),
    GRVLM("Vouliagmeni", PortCountries.GR),
    GRVOL("Volos", PortCountries.GR),
    GRVOM("Voudia Milou", PortCountries.GR),
    GRVSS("Vassiliki Leykadas", PortCountries.GR),
    GRVTH("Vathy", PortCountries.GR),
    GRYER("Yerakini", PortCountries.GR),
    GRYLI("Yali Island", PortCountries.GR),
    GRZTH("Zakynthos (Zante)", PortCountries.GR),
    HRATL("Antenal", PortCountries.HR),
    HRBAK("Bakar", PortCountries.HR),
    HRBAS("Baska", PortCountries.HR),
    HRBLE("Blace", PortCountries.HR),
    HRBNM("Biograd", PortCountries.HR),
    HRBOL("Bol", PortCountries.HR),
    HRBRB("Brbinj/Lucina", PortCountries.HR),
    HRBRI("Brioni", PortCountries.HR),
    HRBVO("Baska Voda", PortCountries.HR),
    HRBZA("Bozava", PortCountries.HR),
    HRCRA("Crikvenica", PortCountries.HR),
    HRCRS("Cres", PortCountries.HR),
    HRCVT("Cavtat", PortCountries.HR),
    HRDAL("Dalmacia", PortCountries.HR),
    HRDBV("Dubrovnik", PortCountries.HR),
    HRDNC("Donje Celo", PortCountries.HR),
    HRDRK("Drvenik", PortCountries.HR),
    HRDUR("Dugi Rat", PortCountries.HR),
    HRFIL("Filipjakov", PortCountries.HR),
    HRFNA("Fazana", PortCountries.HR),
    HRGNA("Gazenica", PortCountries.HR),
    HRHVA("Hvar", PortCountries.HR),
    HRIST("Ist", PortCountries.HR),
    HRJAB("Jablanac", PortCountries.HR),
    HRJDR("Jadrija", PortCountries.HR),
    HRJSA("Jelsa", PortCountries.HR),
    HRKAB("Karlobag", PortCountries.HR),
    HRKAL("Kali", PortCountries.HR),
    HRKLK("Klek", PortCountries.HR),
    HRKMN("Klimno", PortCountries.HR),
    HRKMZ("Komiza", PortCountries.HR),
    HRKOR("Korcula", PortCountries.HR),
    HRKOS("Kostrena", PortCountries.HR),
    HRKPR("Kaprije", PortCountries.HR),
    HRKRA("Kraljevica", PortCountries.HR),
    HRKRK("Krk", PortCountries.HR),
    HRKRM("Koromacno", PortCountries.HR),
    HRKUK("Kukljica", PortCountries.HR),
    HRLAM("Lamjane", PortCountries.HR),
    HRLKR("Lokrum", PortCountries.HR),
    HRLPD("Lopud", PortCountries.HR),
    HRLPR("Lopar", PortCountries.HR),
    HRLST("Lastovo", PortCountries.HR),
    HRLSZ("Mali Losinj", PortCountries.HR),
    HRMAK("Makarska", PortCountries.HR),
    HRMAL("Malinska", PortCountries.HR),
    HRMAS("Maslenica", PortCountries.HR),
    HRMET("Metkovic", PortCountries.HR),
    HRMIL("Milna", PortCountries.HR),
    HRMIZ("Iz Mali", PortCountries.HR),
    HRMNK("Misnjak", PortCountries.HR),
    HRMOD("Moscenicka draga", PortCountries.HR),
    HRMRG("Merag", PortCountries.HR),
    HRMRJ("Muna na Zirju", PortCountries.HR),
    HRMTA("Martinscica", PortCountries.HR),
    HRMUR("Murter", PortCountries.HR),
    HRNRZ("Nerezine", PortCountries.HR),
    HRNVD("Novi Vinodolski", PortCountries.HR),
    HRNVG("Novigrad", PortCountries.HR),
    HRNVL("Novalja", PortCountries.HR),
    HROMI("Omisalj", PortCountries.HR),
    HROMS("Omis", PortCountries.HR),
    HRONJ("Obonjan", PortCountries.HR),
    HROPA("Opatija", PortCountries.HR),
    HRORB("Orebic", PortCountries.HR),
    HRPAG("Pag", PortCountries.HR),
    HRPAS("Pasman", PortCountries.HR),
    HRPCA("Pucisca", PortCountries.HR),
    HRPLA("Polace", PortCountries.HR),
    HRPLE("Ploce", PortCountries.HR),
    HRPLM("Plomin", PortCountries.HR),
    HRPMN("Pomena", PortCountries.HR),
    HRPNT("Punat", PortCountries.HR),
    HRPOR("Porec", PortCountries.HR),
    HRPRE("Preko", PortCountries.HR),
    HRPRI("Primosten", PortCountries.HR),
    HRPRN("Prizna", PortCountries.HR),
    HRPRP("Prapratno", PortCountries.HR),
    HRPRS("Prvic Sepurine", PortCountries.HR),
    HRPRV("Prvic", PortCountries.HR),
    HRPRZ("Porozina", PortCountries.HR),
    HRPUY("Pula", PortCountries.HR),
    HRRAB("Rab", PortCountries.HR),
    HRRAS("Rasa", PortCountries.HR),
    HRRBC("Rabac", PortCountries.HR),
    HRRGC("Rogac", PortCountries.HR),
    HRRGN("Rogoznica", PortCountries.HR),
    HRRJK("Rijeka", PortCountries.HR),
    HRROG("Rogotin", PortCountries.HR),
    HRROV("Rovinj", PortCountries.HR),
    HRSAL("Sali", PortCountries.HR),
    HRSBC("Stobrec", PortCountries.HR),
    HRSBR("Sobra", PortCountries.HR),
    HRSDR("Sudurad", PortCountries.HR),
    HRSEN("Senj", PortCountries.HR),
    HRSGD("Stari Grad", PortCountries.HR),
    HRSGR("Starigard", PortCountries.HR),
    HRSIB("Sibenik", PortCountries.HR),
    HRSIL("Silba", PortCountries.HR),
    HRSLA("Slano", PortCountries.HR),
    HRSLC("Selce", PortCountries.HR),
    HRSLO("Silo", PortCountries.HR),
    HRSLT("Slatine", PortCountries.HR),
    HRSMN("Sumartin", PortCountries.HR),
    HRSPL("Splitska", PortCountries.HR),
    HRSPU("Split", PortCountries.HR),
    HRSRD("Skradin", PortCountries.HR),
    HRSSK("Susak", PortCountries.HR),
    HRSTM("Stomorska", PortCountries.HR),
    HRSTO("Ston", PortCountries.HR),
    HRSTP("Sustjepan", PortCountries.HR),
    HRSUC("Sucuraj", PortCountries.HR),
    HRSUP("Supetar", PortCountries.HR),
    HRSUR("Kastela", PortCountries.HR),
    HRSUS("Susak", PortCountries.HR),
    HRSUT("Sutivan", PortCountries.HR),
    HRSVJ("Sveti Juraj", PortCountries.HR),
    HRSVK("Sveti Kajo", PortCountries.HR),
    HRTKN("Tkon", PortCountries.HR),
    HRTNO("Tisno", PortCountries.HR),
    HRTNR("Tunarica", PortCountries.HR),
    HRTRI("Tribunj", PortCountries.HR),
    HRTRJ("Trpanj", PortCountries.HR),
    HRTRK("Trstenik", PortCountries.HR),
    HRTRO("Trogir", PortCountries.HR),
    HRUBL("Ubli", PortCountries.HR),
    HRUGL("Ugljan", PortCountries.HR),
    HRUMG("Umag", PortCountries.HR),
    HRUNJ("Unije", PortCountries.HR),
    HRUVM("Uvala Mir", PortCountries.HR),
    HRVDC("Vodice", PortCountries.HR),
    HRVGN("Viganj", PortCountries.HR),
    HRVIS("Vis", PortCountries.HR),
    HRVIZ("Veli Iz", PortCountries.HR),
    HRVLB("Valbiska", PortCountries.HR),
    HRVLK("Vela Luka", PortCountries.HR),
    HRVLN("Veli Losinj", PortCountries.HR),
    HRVRA("Vranjic", PortCountries.HR),
    HRVRG("Vrgada", PortCountries.HR),
    HRVRK("Vrbnik", PortCountries.HR),
    HRVRR("Vrsar", PortCountries.HR),
    HRVRS("Vrboska", PortCountries.HR),
    HRZAD("Zadar", PortCountries.HR),
    HRZAG("Zagreb", PortCountries.HR),
    HRZGL("Zigljen", PortCountries.HR),
    HRZLR("Zlarin", PortCountries.HR),
    HRZUT("Zut Marina", PortCountries.HR),
    IEALQ("Alexandra Quay", PortCountries.IE),
    IEARK("Arklow", PortCountries.IE),
    IEAUG("Aughinish", PortCountries.IE),
    IEBTM("Baltimore", PortCountries.IE),
    IEBYT("Bantry", PortCountries.IE),
    IECBR("Coomhola Bridge", PortCountries.IE),
    IECOB("Cobh", PortCountries.IE),
    IECTB("Castletown bear haven", PortCountries.IE),
    IEDDK("Dundalk", PortCountries.IE),
    IEDFA("Dublin-Ferryport Terminal 1", PortCountries.IE),
    IEDFB("Dublin-Ferryport Terminal 2", PortCountries.IE),
    IEDFC("Dublin-Ferryport Terminal 3", PortCountries.IE),
    IEDFT("Dublin-Dublin Ferryport Terminals", PortCountries.IE),
    IEDIN("Dingle", PortCountries.IE),
    IEDLG("Dun laoghaire", PortCountries.IE),
    IEDMF("Drogheda Maxol Facility", PortCountries.IE),
    IEDPP("Drogheda Premiere Periclase", PortCountries.IE),
    IEDRO("Drogheda", PortCountries.IE),
    IEDUB("Dublin", PortCountries.IE),
    IEFCW("Frank Cassin Wharf", PortCountries.IE),
    IEFEN("Fenit", PortCountries.IE),
    IEFOV("Foynes", PortCountries.IE),
    IEFRW("Ford's Wharf (Topaz Energy Terminal)", PortCountries.IE),
    IEGGA("Glengarriff", PortCountries.IE),
    IEGRE("Greencastle", PortCountries.IE),
    IEGRN("Greenore", PortCountries.IE),
    IEGWY("Galway", PortCountries.IE),
    IEHAU("Haulbowline", PortCountries.IE),
    IEKBS("Killybegs", PortCountries.IE),
    IEKLN("Kinsale", PortCountries.IE),
    IELMK("Limerick", PortCountries.IE),
    IEMAP("Marino Point", PortCountries.IE),
    IEMAR("Marshmeadows/New Ross", PortCountries.IE),
    IEMOT("Moneypoint", PortCountries.IE),
    IEMOV("Moville", PortCountries.IE),
    IEMTL("Dublin-Marine Terminal", PortCountries.IE),
    IENRR("New Ross-Raheen/Roberscon", PortCountries.IE),
    IENRS("New Ross", PortCountries.IE),
    IEORK("Cork including Whitegate", PortCountries.IE),
    IEPAW("Passage West", PortCountries.IE),
    IERDT("Ringaskiddy Deepwater Terminal", PortCountries.IE),
    IERIN("Ringaskiddy", PortCountries.IE),
    IEROE("Rosslare harbour", PortCountries.IE),
    IEROS("Rosslare Harbour", PortCountries.IE),
    IERPT("Ringaskiddy Passenger Terminal", PortCountries.IE),
    IERSM("Rossavael", PortCountries.IE),
    IESLI("Sligo", PortCountries.IE),
    IESNN("Shannon", PortCountries.IE),
    IESNR("Stokestown/New Ross", PortCountries.IE),
    IETAR("Tarbert", PortCountries.IE),
    IETIV("Tivoli", PortCountries.IE),
    IETQY("Town Quays/Drogheda", PortCountries.IE),
    IETRP("Tom Roes Point Terminal/Drogheda", PortCountries.IE),
    IEWAT("Waterford &amp; Bellview", PortCountries.IE),
    IEWCQ("Waterford City Quays", PortCountries.IE),
    IEWGI("Waterford Great Island (ESB)", PortCountries.IE),
    IEWHI("Whitegate", PortCountries.IE),
    IEWIC("Wicklow", PortCountries.IE),
    IEYOU("Youghal", PortCountries.IE),
    IMPEL("Peel", PortCountries.IM),
    ISAKR("Akranes", PortCountries.IS),
    ISAKU("Akureyri", PortCountries.IS),
    ISBIL("Bildudalur", PortCountries.IS),
    ISBLO("Blondos", PortCountries.IS),
    ISBOL("Bolungavik", PortCountries.IS),
    ISBOR("Borgarnes", PortCountries.IS),
    ISDAL("Dalvikurhofn", PortCountries.IS),
    ISDJU("Djupivogur", PortCountries.IS),
    ISESK("Eskifjordur", PortCountries.IS),
    ISFAS("Faskrudsfjordur", PortCountries.IS),
    ISFLA("Flateyri", PortCountries.IS),
    ISGRE("Grenivik", PortCountries.IS),
    ISGRF("Grundarfjordur", PortCountries.IS),
    ISGRI("Grindavik", PortCountries.IS),
    ISGRT("Grundartangi", PortCountries.IS),
    ISGRY("Grimsey", PortCountries.IS),
    ISHAF("Hafnarfjordur", PortCountries.IS),
    ISHEL("Helguvik", PortCountries.IS),
    ISHFN("Hofn", PortCountries.IS),
    ISHUS("Husavik", PortCountries.IS),
    ISHVK("Holmavik", PortCountries.IS),
    ISHVM("Hvammstangi", PortCountries.IS),
    ISHVR("Hvalfjordur & Midsandur", PortCountries.IS),
    ISISA("Isafjordur", PortCountries.IS),
    ISKEV("Keflavik", PortCountries.IS),
    ISKOV("Kopavogur", PortCountries.IS),
    ISLSA("Litli Sandur", PortCountries.IS),
    ISMJH("Mjoeyrarhofn", PortCountries.IS),
    ISNES("Neskaupstadur", PortCountries.IS),
    ISNJA("Njardvik", PortCountries.IS),
    ISOLF("Olafsfjordur", PortCountries.IS),
    ISOLV("Snaefellsbaer - olafsvik", PortCountries.IS),
    ISPAT("Patreksfjordur", PortCountries.IS),
    ISRAU("Raufarhofn", PortCountries.IS),
    ISREY("Reykjavik", PortCountries.IS),
    ISRFJ("Reydarfjordur", PortCountries.IS),
    ISRHA("Reykholar", PortCountries.IS),
    ISRIF("Rifshofn", PortCountries.IS),
    ISSAN("Sandgerdi", PortCountries.IS),
    ISSAU("Saudarkrokur", PortCountries.IS),
    ISSEY("Seydisfjordur", PortCountries.IS),
    ISSIG("Siglufjordur", PortCountries.IS),
    ISSKA("Skagastrond", PortCountries.IS),
    ISSTR("Straumsvik", PortCountries.IS),
    ISSTY("Stykkisholmur", PortCountries.IS),
    ISTAL("Talknafjordur/Sveinseyri", PortCountries.IS),
    ISTEY("Thingeyri", PortCountries.IS),
    ISTHH("Thorlakshofn", PortCountries.IS),
    ISTHO("Thorshofn", PortCountries.IS),
    ISVES("Vestmannaeyjar", PortCountries.IS),
    ISVPN("Vopnafjordur", PortCountries.IS),
    ITAGP("Agropoli", PortCountries.IT),
    ITAHO("Alghero", PortCountries.IT),
    ITALS("Alassio", PortCountries.IT),
    ITAMA("Amalfi", PortCountries.IT),
    ITANZ("Anzio", PortCountries.IT),
    ITAOI("Ancona", PortCountries.IT),
    ITAOR("Caorle", PortCountries.IT),
    ITATX("Arbatax", PortCountries.IT),
    ITAUG("Augusta", PortCountries.IT),
    ITBDS("Brindisi", PortCountries.IT),
    ITBLT("Barletta", PortCountries.IT),
    ITBOA("Bosa", PortCountries.IT),
    ITBRI("Bari", PortCountries.IT),
    ITCAG("Cagliari", PortCountries.IT),
    ITCAS("Castellammare di stabia", PortCountries.IT),
    ITCCQ("Cetraro", PortCountries.IT),
    ITCGC("Corigliano calabro", PortCountries.IT),
    ITCHI("Chioggia", PortCountries.IT),
    ITCLF("Carloforte", PortCountries.IT),
    ITCLS("Calasetta", PortCountries.IT),
    ITCML("Casamicciola", PortCountries.IT),
    ITCNT("Cesenatico", PortCountries.IT),
    ITCPA("Capraia", PortCountries.IT),
    ITCRV("Crotone", PortCountries.IT),
    ITCTA("Catania", PortCountries.IT),
    ITCVV("Civitavecchia", PortCountries.IT),
    ITCVX("Cavo", PortCountries.IT),
    ITFAL("Falconara", PortCountries.IT),
    ITFAO("Fano", PortCountries.IT),
    ITFAV("Favignana", PortCountries.IT),
    ITFCO("Fiumicino", PortCountries.IT),
    ITFOL("Follonica", PortCountries.IT),
    ITFOM("Formia", PortCountries.IT),
    ITFOR("Isolotto Formica", PortCountries.IT),
    ITGAE("Gaeta", PortCountries.IT),
    ITGAI("Golfo aranci", PortCountries.IT),
    ITGAL("Gallipoli", PortCountries.IT),
    ITGEA("Gela", PortCountries.IT),
    ITGHE("Porto Marghera", PortCountries.IT),
    ITGIA("Giardini Naxos", PortCountries.IT),
    ITGIT("Gioia tauro", PortCountries.IT),
    ITGOA("Genova", PortCountries.IT),
    ITGRD("Grado", PortCountries.IT),
    ITGUI("Giulianova Marche", PortCountries.IT),
    ITIDG("Isola del Giglio", PortCountries.IT),
    ITIMP("Imperia(p-m)", PortCountries.IT),
    ITIOA("Civitanova marche", PortCountries.IT),
    ITISH("Ischia", PortCountries.IT),
    ITISN("Isola Asinara", PortCountries.IT),
    ITJLO("Jesolo", PortCountries.IT),
    ITLEV("Levanzo", PortCountries.IT),
    ITLIC("Licata", PortCountries.IT),
    ITLIP("Lipari", PortCountries.IT),
    ITLIV("Livorno", PortCountries.IT),
    ITLMP("LAMPEDUSA", PortCountries.IT),
    ITMAZ("Mazara del vallo", PortCountries.IT),
    ITMDA("La Maddalena", PortCountries.IT),
    ITMDC("Marina di carrara", PortCountries.IT),
    ITMFR("Manfredonia", PortCountries.IT),
    ITMLZ("Milazzo", PortCountries.IT),
    ITMMO("Marettimo", PortCountries.IT),
    ITMNF("Monfalcone", PortCountries.IT),
    ITMNP("Monopoli", PortCountries.IT),
    ITMOL("Molfetta", PortCountries.IT),
    ITMRA("Marsala", PortCountries.IT),
    ITMSN("Messina", PortCountries.IT),
    ITNAP("Naples", PortCountries.IT),
    ITNTA("Sant'Antioco", PortCountries.IT),
    ITOLB("Olbia", PortCountries.IT),
    ITORL("Porticello", PortCountries.IT),
    ITOTN("Ortona", PortCountries.IT),
    ITOTO("Otranto", PortCountries.IT),
    ITPAN("Panarea", PortCountries.IT),
    ITPAU("Palau", PortCountries.IT),
    ITPAZ("Porto Azzurro", PortCountries.IT),
    ITPCE("Porto Cervo", PortCountries.IT),
    ITPEM("Porto Empedocle", PortCountries.IT),
    ITPES("Pesaro", PortCountries.IT),
    ITPFE("Porto Ferraio", PortCountries.IT),
    ITPFX("Sarroch", PortCountries.IT),
    ITPGA("Porto Garibaldi", PortCountries.IT),
    ITPIO("Piombino", PortCountries.IT),
    ITPLN("Palinuro", PortCountries.IT),
    ITPMA("Marghera", PortCountries.IT),
    ITPMO("Palermo", PortCountries.IT),
    ITPNG("Porto Nogaro", PortCountries.IT),
    ITPNL("Pantellaria", PortCountries.IT),
    ITPNZ("Ponza", PortCountries.IT),
    ITPOQ("Porto Viro", PortCountries.IT),
    ITPOS("Positano", PortCountries.IT),
    ITPOZ("Pozzuoli", PortCountries.IT),
    ITPRJ("Capri", PortCountries.IT),
    ITPRL("Priolo Gargallo", PortCountries.IT),
    ITPRO("Procida", PortCountries.IT),
    ITPRW("Portovenere", PortCountries.IT),
    ITPSR("Pescara", PortCountries.IT),
    ITPSS("Porto Santo Stefano", PortCountries.IT),
    ITPTF("Portofino", PortCountries.IT),
    ITPTO("Porto Torres", PortCountries.IT),
    ITPVE("Portoscuso", PortCountries.IT),
    ITPVT("Porto Levante", PortCountries.IT),
    ITPZL("Pozzallo", PortCountries.IT),
    ITQOS("Oristano", PortCountries.IT),
    ITRAN("Ravenna", PortCountries.IT),
    ITREG("Reggio Calabria", PortCountries.IT),
    ITRMA("Rio Marina", PortCountries.IT),
    ITRMI("Rimini", PortCountries.IT),
    ITROC("Roccella Jonica", PortCountries.IT),
    ITROM("Roma (Fiumicino)", PortCountries.IT),
    ITRPT("Riposto", PortCountries.IT),
    ITRRO("Sorrento", PortCountries.IT),
    ITSAG("Sant'Agata Di Militello", PortCountries.IT),
    ITSAL("Salerno", PortCountries.IT),
    ITSCK("Sciacca", PortCountries.IT),
    ITSDB("San benedetto del tronto", PortCountries.IT),
    ITSIG("Porto San Giorgio", PortCountries.IT),
    ITSIR("Siracusa - Santa Panagia", PortCountries.IT),
    ITSLA("Santa Marta Salina", PortCountries.IT),
    ITSML("Santa Margherita Ligure", PortCountries.IT),
    ITSOO("Soverato", PortCountries.IT),
    ITSPA("Santa Panagia", PortCountries.IT),
    ITSPE("La Spezia", PortCountries.IT),
    ITSRE("Sanremo", PortCountries.IT),
    ITSTE("Santa Teresa di Gallura", PortCountries.IT),
    ITSTR("Stromboli", PortCountries.IT),
    ITSVN("Savona", PortCountries.IT),
    ITTAL("Talamone", PortCountries.IT),
    ITTAR("Taranto", PortCountries.IT),
    ITTDG("Torre del Greco", PortCountries.IT),
    ITTEA("Maratea", PortCountries.IT),
    ITTMI("Termoli", PortCountries.IT),
    ITTMT("Tremiti", PortCountries.IT),
    ITTOA("Torre annunziata", PortCountries.IT),
    ITTPS("Trapani", PortCountries.IT),
    ITTRC("Terracina", PortCountries.IT),
    ITTRI("Termini imerese", PortCountries.IT),
    ITTRS("Trieste", PortCountries.IT),
    ITUST("Ustica", PortCountries.IT),
    ITVCE("Venice", PortCountries.IT),
    ITVDA("Vada", PortCountries.IT),
    ITVDL("Vado Ligure", PortCountries.IT),
    ITVIA("Viareggio", PortCountries.IT),
    ITVIE("Vieste", PortCountries.IT),
    ITVNC("Vallenoncello", PortCountries.IT),
    ITVSG("Villa San Giovanni", PortCountries.IT),
    ITVSO("Vasto", PortCountries.IT),
    ITVTI("Voltri Terminal", PortCountries.IT),
    ITVUL("Vulcano", PortCountries.IT),
    ITVVA("Vibo valentia marina", PortCountries.IT),
    LTBOT("Botinge", PortCountries.LT),
    LTKLJ("Klaipeda", PortCountries.LT),
    LVEGE("Engure", PortCountries.LV),
    LVLPX("Liepaja", PortCountries.LV),
    LVMRX("Mersrags", PortCountries.LV),
    LVRIX("Riga", PortCountries.LV),
    LVROJ("Roja", PortCountries.LV),
    LVSAL("Salacgriva", PortCountries.LV),
    LVSKU("Skulte", PortCountries.LV),
    LVVNT("Ventspils", PortCountries.LV),
    MA6KN("Souq Larb'A Al Gharb", PortCountries.MA),
    MAAGA("Agadir", PortCountries.MA),
    MAAHU("Al Hoceïma", PortCountries.MA),
    MAANZ("Anza", PortCountries.MA),
    MAASI("Asilah", PortCountries.MA),
    MAAZE("Azemmour", PortCountries.MA),
    MABJD("Bir-Jdid", PortCountries.MA),
    MACAS("Casablanca", PortCountries.MA),
    MAD2V("Ar Rommani", PortCountries.MA),
    MAELJ("El Jadida", PortCountries.MA),
    MAESS("Essaouira", PortCountries.MA),
    MAEUN("Laayoune", PortCountries.MA),
    MAJFL("Jorf Lasfar", PortCountries.MA),
    MALAR("Larache", PortCountries.MA),
    MAMOH("Mohammedia", PortCountries.MA),
    MANDR("Nador", PortCountries.MA),
    MANNA("Kenitra", PortCountries.MA),
    MAPTM("Tanger Med", PortCountries.MA),
    MARBA("Rabat", PortCountries.MA),
    MAREM("Ras El Ma", PortCountries.MA),
    MARNA("Roches Noires", PortCountries.MA),
    MASAL("Sale", PortCountries.MA),
    MASFI("Safi", PortCountries.MA),
    MASII("Sidi Ifni", PortCountries.MA),
    MASMD("Ait Melloul", PortCountries.MA),
    MATEM("Temara", PortCountries.MA),
    MATNG("Tangier", PortCountries.MA),
    MATTU("Tetouan", PortCountries.MA),
    MAVIL("Dakhla", PortCountries.MA),
    MEBAR("Bar", PortCountries.ME),
    MEBIJ("Bijela", PortCountries.ME),
    MEBUD("Budva", PortCountries.ME),
    MEHNO("Hercegnovi", PortCountries.ME),
    MEIGL("Igalo", PortCountries.ME),
    MEKOT("Kotor", PortCountries.ME),
    MEPVC("Petrovac", PortCountries.ME),
    MERSN("Risan", PortCountries.ME),
    METIV("Tivat", PortCountries.ME),
    MEULC("Ulcinj", PortCountries.ME),
    MEZEL("Zelenika", PortCountries.ME),
    MFGES("Galisbay", null),
    MFMAR("Marigot", null),
    MQFDF("Fort-de-France", null),
    MQQMR("Le Marin", null),
    MQQPC("Port de Fort-de-France Pt.", null),
    MTDIS("Malta Freeport Distripark", PortCountries.MT),
    MTMAR("Marsaxlokk", PortCountries.MT),
    MTMGZ("Mgarr Gozo", PortCountries.MT),
    MTMLA("Valletta", PortCountries.MT),
    MTMSX("Marsamxett", PortCountries.MT),
    NLAMS("Amsterdam", PortCountries.NL),
    NLANK("Everingen", PortCountries.NL),
    NLBEV("Beverwijk", PortCountries.NL),
    NLBOR("Borssele", PortCountries.NL),
    NLBRS("Breskens", PortCountries.NL),
    NLDHR("Den Helder", PortCountries.NL),
    NLDOR("Dordrecht", PortCountries.NL),
    NLDZL("Delfzijl", PortCountries.NL),
    NLEEM("Eemshaven", PortCountries.NL),
    NLEUR("Europoort", PortCountries.NL),
    NLGOR("Gorinchem", PortCountries.NL),
    NLHAN("Hansweert", PortCountries.NL),
    NLHAR("Harlingen", PortCountries.NL),
    NLHVH("Hoek van Holland", PortCountries.NL),
    NLIJM("Ijmuiden", PortCountries.NL),
    NLLAN("Lauwersoog", PortCountries.NL),
    NLMID("Middelburg", PortCountries.NL),
    NLMOE("Moerdijk", PortCountries.NL),
    NLMSL("Maassluis", PortCountries.NL),
    NLPER("Pernis", PortCountries.NL),
    NLRTM("Rotterdam", PortCountries.NL),
    NLSCE("Scheveningen", PortCountries.NL),
    NLSCI("Schiedam", PortCountries.NL),
    NLSLU("Sluiskil", PortCountries.NL),
    NLSMV("Sint Maartensvlotbrug", PortCountries.NL),
    NLSVG("Sas van gent", PortCountries.NL),
    NLSWK("Sleeuwijk", PortCountries.NL),
    NLTEX("Texel", PortCountries.NL),
    NLTNZ("Terneuzen", PortCountries.NL),
    NLVEL("Velsen", PortCountries.NL),
    NLVLA("Vlaardingen", PortCountries.NL),
    NLVLI("Vlissingen", PortCountries.NL),
    NLVSN("Velsen-Noord", PortCountries.NL),
    NLWDP("Westdorpe", PortCountries.NL),
    NLZAA("Zaandam", PortCountries.NL),
    NOAAA("A i Lofoten", PortCountries.NO),
    NOAAF("Afjord", PortCountries.NO),
    NOAAN("Ardal", PortCountries.NO),
    NOAAV("Alvik", PortCountries.NO),
    NOABE("Abelnes", PortCountries.NO),
    NOABV("Abelvar", PortCountries.NO),
    NOADN("Andenes", PortCountries.NO),
    NOADY("Andoy", PortCountries.NO),
    NOAES("Alesund", PortCountries.NO),
    NOAFS("Anfinnsletta", PortCountries.NO),
    NOAFT("Agnefest", PortCountries.NO),
    NOAGK("Agskardet", PortCountries.NO),
    NOAGO("Agotnes", PortCountries.NO),
    NOAHM("Aheim", PortCountries.NO),
    NOAKM("Akrehamn", PortCountries.NO),
    NOALE("Alefjar", PortCountries.NO),
    NOALF("Alta", PortCountries.NO),
    NOALG("Algard", PortCountries.NO),
    NOALS("Alstahaug", PortCountries.NO),
    NOALV("Alvika", PortCountries.NO),
    NOAND("Andalsnes", PortCountries.NO),
    NOARD("Ardalstangen", PortCountries.NO),
    NOARE("Arendal", PortCountries.NO),
    NOARF("Arnafjord", PortCountries.NO),
    NOARH("Ardal - Hjelmeland", PortCountries.NO),
    NOARS("Arstein", PortCountries.NO),
    NOASH("Austrheim", PortCountries.NO),
    NOASL("Askvoll", PortCountries.NO),
    NOASR("Ana-Sira", PortCountries.NO),
    NOASV("Austevoll", PortCountries.NO),
    NOASY("Askoy", PortCountries.NO),
    NOATA("Atangen", PortCountries.NO),
    NOATL("Vilnes - Askvoll", PortCountries.NO),
    NOAUE("Aure", PortCountries.NO),
    NOAUK("Aukra", PortCountries.NO),
    NOAUL("Aurland", PortCountries.NO),
    NOAUS("Austvika", PortCountries.NO),
    NOAVA("Avaldsnes", PortCountries.NO),
    NOAVE("Averoy", PortCountries.NO),
    NOBAF("Balsfjord", PortCountries.NO),
    NOBAL("Baly", PortCountries.NO),
    NOBAM("Bamble", PortCountries.NO),
    NOBAR("Barum", PortCountries.NO),
    NOBEL("Bellvika", PortCountries.NO),
    NOBFJ("Bergsfjord", PortCountries.NO),
    NOBGN("Bergneset", PortCountries.NO),
    NOBGO("Bergen", PortCountries.NO),
    NOBIN("Bindal", PortCountries.NO),
    NOBJD("Bjordal", PortCountries.NO),
    NOBJF("Baatsjord", PortCountries.NO),
    NOBJO("Bjoa", PortCountries.NO),
    NOBJU("Bjugn", PortCountries.NO),
    NOBJX("Bjorkas", PortCountries.NO),
    NOBJY("Bjarkoy", PortCountries.NO),
    NOBKS("Brekstad", PortCountries.NO),
    NOBKV("Bjerkvik", PortCountries.NO),
    NOBLK("Bleik", PortCountries.NO),
    NOBLL("Ballangen", PortCountries.NO),
    NOBLO("Blokken", PortCountries.NO),
    NOBLS("Balestrand", PortCountries.NO),
    NOBLV("Blomvag", PortCountries.NO),
    NOBNN("Bronnoysund", PortCountries.NO),
    NOBOE("Boneset - Karmoy", PortCountries.NO),
    NOBOG("Bogen", PortCountries.NO),
    NOBOK("Bokn", PortCountries.NO),
    NOBOM("Bomlo", PortCountries.NO),
    NOBON("Bognes", PortCountries.NO),
    NOBOO("Bodo", PortCountries.NO),
    NOBOS("Borkenes", PortCountries.NO),
    NOBOV("Bovagen", PortCountries.NO),
    NOBRE("Bremanger", PortCountries.NO),
    NOBRH("Brensholmen", PortCountries.NO),
    NOBRK("Breivika - Tromso", PortCountries.NO),
    NOBRS("Barstrand", PortCountries.NO),
    NOBRV("Brattvag", PortCountries.NO),
    NOBRY("Bryne", PortCountries.NO),
    NOBSD("Ballstad", PortCountries.NO),
    NOBTH("Botnhamn", PortCountries.NO),
    NOBTN("Botnaneset", PortCountries.NO),
    NOBTS("Brettesnes", PortCountries.NO),
    NOBUF("Burfjord", PortCountries.NO),
    NOBUG("Bugoynes", PortCountries.NO),
    NOBUV("Buvika", PortCountries.NO),
    NOBVB("Breivikbotn", PortCountries.NO),
    NOBVG("Berlevag", PortCountries.NO),
    NOBVK("Brevik", PortCountries.NO),
    NOBVR("Breiviga", PortCountries.NO),
    NOBXK("Bjerkreim", PortCountries.NO),
    NOBYN("Bygnes - Karmoy", PortCountries.NO),
    NOBYS("Bygstad", PortCountries.NO),
    NODDY("Espenesbogen", PortCountries.NO),
    NODFJ("Dalfjord", PortCountries.NO),
    NODGR("Digernes", PortCountries.NO),
    NODIM("Dimmelsvik", PortCountries.NO),
    NODIR("Dirdal", PortCountries.NO),
    NODJU("Djupvik", PortCountries.NO),
    NODNS("Dommersnes - Vindafjord", PortCountries.NO),
    NODON("Donna", PortCountries.NO),
    NODRG("Drag", PortCountries.NO),
    NODRK("Drobak", PortCountries.NO),
    NODRM("Drammen", PortCountries.NO),
    NODSF("Dale", PortCountries.NO),
    NODUS("Dusavik", PortCountries.NO),
    NODYD("Dyrstad", PortCountries.NO),
    NODYL("Dyroyhamn", PortCountries.NO),
    NODYR("Dyrvik", PortCountries.NO),
    NOEDD("Eidsdal", PortCountries.NO),
    NOEDE("Eide", PortCountries.NO),
    NOEDF("Eidfjord", PortCountries.NO),
    NOEDS("Eide Sotra", PortCountries.NO),
    NOEDT("Eidet", PortCountries.NO),
    NOEFD("Eresfjord", PortCountries.NO),
    NOEGD("Egersund", PortCountries.NO),
    NOEGE("Egersund", PortCountries.NO),
    NOEGG("Eggesbones", PortCountries.NO),
    NOEIF("Eidangerfjorden", PortCountries.NO),
    NOEIK("Eikefjord", PortCountries.NO),
    NOEIL("Eidslandet, Vaksdal", PortCountries.NO),
    NOEKF("Eikefet", PortCountries.NO),
    NOELL("Ellingsoy", PortCountries.NO),
    NOELN("Elnesvagen", PortCountries.NO),
    NOELO("Eikelandsosen", PortCountries.NO),
    NOENG("Engene", PortCountries.NO),
    NOERF("Erfjord", PortCountries.NO),
    NOESP("Espevik", PortCountries.NO),
    NOETN("Etne", PortCountries.NO),
    NOEVT("Evenestangen", PortCountries.NO),
    NOEVV("Eivindvik", PortCountries.NO),
    NOEYD("Eydehavn", PortCountries.NO),
    NOFAN("Farsund", PortCountries.NO),
    NOFAU("Fauske", PortCountries.NO),
    NOFAX("Fagerstrand", PortCountries.NO),
    NOFBL("Fiskebol", PortCountries.NO),
    NOFDE("Forde", PortCountries.NO),
    NOFED("Fedje", PortCountries.NO),
    NOFFB("Finnfjordbotn", PortCountries.NO),
    NOFFD("Flekkefjord", PortCountries.NO),
    NOFIN("Finneidfjord", PortCountries.NO),
    NOFIS("Fiska", PortCountries.NO),
    NOFIT("Fitjar", PortCountries.NO),
    NOFJA("Fjaler", PortCountries.NO),
    NOFJE("Fjell", PortCountries.NO),
    NOFJL("Fjelldal", PortCountries.NO),
    NOFKG("Frekhaug", PortCountries.NO),
    NOFKS("Flakstad", PortCountries.NO),
    NOFLA("Flam", PortCountries.NO),
    NOFLE("Flekkeroy", PortCountries.NO),
    NOFLM("Flem", PortCountries.NO),
    NOFLO("Florvag", PortCountries.NO),
    NOFLT("Flatanger", PortCountries.NO),
    NOFLY("Flatoy", PortCountries.NO),
    NOFND("Finneid", PortCountries.NO),
    NOFNE("Finnsnes", PortCountries.NO),
    NOFNN("Fonnes", PortCountries.NO),
    NOFNS("Fornes", PortCountries.NO),
    NOFNY("Finnoy", PortCountries.NO),
    NOFOE("Forneselva", PortCountries.NO),
    NOFOI("Fossing", PortCountries.NO),
    NOFOL("Follafoss", PortCountries.NO),
    NOFON("Foroy", PortCountries.NO),
    NOFOR("Forsand", PortCountries.NO),
    NOFOS("Fosnavag", PortCountries.NO),
    NOFRA("Froya", PortCountries.NO),
    NOFRI("Frier", PortCountries.NO),
    NOFRJ("Frei", PortCountries.NO),
    NOFRK("Fredrikstad", PortCountries.NO),
    NOFRO("Floro", PortCountries.NO),
    NOFRS("Forus", PortCountries.NO),
    NOFSD("Fjellstrand", PortCountries.NO),
    NOFSK("Fiskabygd - Vanylven", PortCountries.NO),
    NOFSL("Forsol", PortCountries.NO),
    NOFSN("Fosnes", PortCountries.NO),
    NOFST("Fiskarstrand", PortCountries.NO),
    NOFSV("Festvag", PortCountries.NO),
    NOFUS("Fusa", PortCountries.NO),
    NOFYS("Fjarland", PortCountries.NO),
    NOGAM("Gamvik", PortCountries.NO),
    NOGAU("Gaular", PortCountries.NO),
    NOGHV("Gunhildvagen", PortCountries.NO),
    NOGIK("Gismarvik", PortCountries.NO),
    NOGIL("Gildeskal", PortCountries.NO),
    NOGIS("Giske", PortCountries.NO),
    NOGJD("Gjosundet", PortCountries.NO),
    NOGJM("Gjemnes", PortCountries.NO),
    NOGJS("Gjesdal", PortCountries.NO),
    NOGJV("Gjesvar", PortCountries.NO),
    NOGLO("Glomfjord", PortCountries.NO),
    NOGLP("Gloppen", PortCountries.NO),
    NOGNR("Geiranger", PortCountries.NO),
    NOGOT("Grotavar", PortCountries.NO),
    NOGPN("Gaupne", PortCountries.NO),
    NOGRD("Gravdal", PortCountries.NO),
    NOGRE("Greaker", PortCountries.NO),
    NOGRF("Grovfjord", PortCountries.NO),
    NOGRI("Granerudstoa", PortCountries.NO),
    NOGRL("Grenland", PortCountries.NO),
    NOGRP("Grip", PortCountries.NO),
    NOGRR("Grytoya", PortCountries.NO),
    NOGRT("Gratangen", PortCountries.NO),
    NOGRV("Granvin", PortCountries.NO),
    NOGRY("Gryllefjord", PortCountries.NO),
    NOGTD("Grimstad", PortCountries.NO),
    NOGUD("Gudvangen", PortCountries.NO),
    NOGUL("Gulen", PortCountries.NO),
    NOGUR("Gursken", PortCountries.NO),
    NOHAD("Hadsel", PortCountries.NO),
    NOHAE("Hansnes", PortCountries.NO),
    NOHAL("Halden", PortCountries.NO),
    NOHAM("Halsa Meloy", PortCountries.NO),
    NOHAN("Halvorshavn", PortCountries.NO),
    NOHAU("Haugesund", PortCountries.NO),
    NOHAV("Havoysund", PortCountries.NO),
    NOHAY("Haroy", PortCountries.NO),
    NOHAZ("Halsnoy", PortCountries.NO),
    NOHBT("Hamnbukt - Porsanger", PortCountries.NO),
    NOHDD("Haddal", PortCountries.NO),
    NOHED("Herdla", PortCountries.NO),
    NOHEF("Herfjord", PortCountries.NO),
    NOHEK("Hekkelstrand", PortCountries.NO),
    NOHEL("Hellvik", PortCountries.NO),
    NOHEM("Haeim", PortCountries.NO),
    NOHEN("Henningsvar", PortCountries.NO),
    NOHER("Hermansverk", PortCountries.NO),
    NOHES("Hestvika", PortCountries.NO),
    NOHET("Heroysundet", PortCountries.NO),
    NOHEV("Helligvar", PortCountries.NO),
    NOHFF("Hafrsfjord", PortCountries.NO),
    NOHFL("Hammerfall", PortCountries.NO),
    NOHFT("Hammerfest", PortCountries.NO),
    NOHHA("Hufthammar", PortCountries.NO),
    NOHIT("Hitra", PortCountries.NO),
    NOHJJ("Hjelset", PortCountries.NO),
    NOHJL("Hjelmeland", PortCountries.NO),
    NOHJO("Hjorungavag", PortCountries.NO),
    NOHKR("Helle - Kragero", PortCountries.NO),
    NOHKV("Gjermundshavn", PortCountries.NO),
    NOHLA("Holla", PortCountries.NO),
    NOHLB("Hoylandsbygda", PortCountries.NO),
    NOHLE("Helle", PortCountries.NO),
    NOHLL("Hollen", PortCountries.NO),
    NOHLS("Halsa", PortCountries.NO),
    NOHLT("Hoylandet", PortCountries.NO),
    NOHLV("Halsvik", PortCountries.NO),
    NOHMS("Hemnes", PortCountries.NO),
    NOHMV("Hummelvik", PortCountries.NO),
    NOHMY("Hamaroy", PortCountries.NO),
    NOHND("Hornindal", PortCountries.NO),
    NOHNE("Hemnesberget", PortCountries.NO),
    NOHOA("Holla", PortCountries.NO),
    NOHOG("Hogset", PortCountries.NO),
    NOHOI("Horten Inner Harbour", PortCountries.NO),
    NOHOK("Hommelvik", PortCountries.NO),
    NOHOL("Holmestrand", PortCountries.NO),
    NOHOO("Horsoy", PortCountries.NO),
    NOHOP("Hopen", PortCountries.NO),
    NOHOR("Horten", PortCountries.NO),
    NOHOT("Hanoytangen", PortCountries.NO),
    NOHOY("Husoy", PortCountries.NO),
    NOHRD("Harstad", PortCountries.NO),
    NOHRI("Hareid", PortCountries.NO),
    NOHRO("Heroy", PortCountries.NO),
    NOHRR("Herre", PortCountries.NO),
    NOHRS("Haroysundet", PortCountries.NO),
    NOHRV("Hordvik", PortCountries.NO),
    NOHRY("Heroya", PortCountries.NO),
    NOHSA("Halsa &ndash; Meloy", PortCountries.NO),
    NOHSL("Hovland", PortCountries.NO),
    NOHSO("Husoy-Karmoy", PortCountries.NO),
    NOHSS("Husoy - Lenvik", PortCountries.NO),
    NOHSU("Haroysund", PortCountries.NO),
    NOHSV("Hausvikstrand", PortCountries.NO),
    NOHSY("Hellesylt", PortCountries.NO),
    NOHUD("Hundeid", PortCountries.NO),
    NOHUR("Hurum", PortCountries.NO),
    NOHUS("Husnes", PortCountries.NO),
    NOHVA("Hoyevarde", PortCountries.NO),
    NOHVG("Honningsvag", PortCountries.NO),
    NOHVI("Havik", PortCountries.NO),
    NOHVK("Hasvik", PortCountries.NO),
    NOHVN("Haakonsvern", PortCountries.NO),
    NOHVR("Kolvereid", PortCountries.NO),
    NOHYE("Hyen", PortCountries.NO),
    NOHYL("Hyllestad", PortCountries.NO),
    NOHYR("Hoyanger", PortCountries.NO),
    NOIBE("Ibestad", PortCountries.NO),
    NOIDR("Inndyr", PortCountries.NO),
    NOIGE("Igeroy", PortCountries.NO),
    NOIGL("Iglandsvik", PortCountries.NO),
    NOIKA("Vikan", PortCountries.NO),
    NOIKR("Ikornes", PortCountries.NO),
    NOINN("Innhavet", PortCountries.NO),
    NOINV("Innvik", PortCountries.NO),
    NOISY("Ingoy", PortCountries.NO),
    NOJAN("Jakobsnes", PortCountries.NO),
    NOJEL("Jelsa", PortCountries.NO),
    NOJLD("Jorpeland", PortCountries.NO),
    NOJON("Jondal", PortCountries.NO),
    NOJOS("Jossingfjord", PortCountries.NO),
    NOJOV("Jovik", PortCountries.NO),
    NOJOY("Jarlsoy", PortCountries.NO),
    NOJSS("Jossingham", PortCountries.NO),
    NOKAB("Kabelvag", PortCountries.NO),
    NOKAF("Kafjord", PortCountries.NO),
    NOKAH("Karvikhamn", PortCountries.NO),
    NOKAN("Kalvneset", PortCountries.NO),
    NOKAR("Karsto", PortCountries.NO),
    NOKAY("Karlsoy", PortCountries.NO),
    NOKBV("Kobbvågen", PortCountries.NO),
    NOKDF("Kaldfjord", PortCountries.NO),
    NOKDL("Kvanndal", PortCountries.NO),
    NOKGF("Kongsfjord", PortCountries.NO),
    NOKIA("Kvithylla", PortCountries.NO),
    NOKIO("Killingoy", PortCountries.NO),
    NOKIV("Kinsarvik", PortCountries.NO),
    NOKJB("Kjorebonn", PortCountries.NO),
    NOKJE("Kjerringoy", PortCountries.NO),
    NOKJF("Kjollefjord", PortCountries.NO),
    NOKJK("Kjopsvik", PortCountries.NO),
    NOKKN("Kirkenes", PortCountries.NO),
    NOKLE("Kleppesto", PortCountries.NO),
    NOKMN("Karhamn", PortCountries.NO),
    NOKMO("Kambo", PortCountries.NO),
    NOKMS("Kjopmannskjar", PortCountries.NO),
    NOKMV("Kamoyvar", PortCountries.NO),
    NOKMY("Hydro Karmoy", PortCountries.NO),
    NOKNA("Knarrdalstranda", PortCountries.NO),
    NOKOB("Kobbvagen", PortCountries.NO),
    NOKOL("Kollsnes East", PortCountries.NO),
    NOKON("Kollsnes", PortCountries.NO),
    NOKOP("Kopervik", PortCountries.NO),
    NOKPG("Kaupanger", PortCountries.NO),
    NOKRA("Kragero", PortCountries.NO),
    NOKRS("Kristiansand", PortCountries.NO),
    NOKRV("Knarrevik", PortCountries.NO),
    NOKRY("Kraakeroy", PortCountries.NO),
    NOKSU("Kristiansund", PortCountries.NO),
    NOKSY("Kvitsoy", PortCountries.NO),
    NOKUV("Kuvika", PortCountries.NO),
    NOKVA("Kalvag", PortCountries.NO),
    NOKVD("Kvinesdal", PortCountries.NO),
    NOKVH("Kvinnherad", PortCountries.NO),
    NOKVK("Kilvik", PortCountries.NO),
    NOKVL("Kristoffervalen", PortCountries.NO),
    NOKVM("Kvam", PortCountries.NO),
    NOKVN("Kvanangen", PortCountries.NO),
    NOKVR("Kvafjord", PortCountries.NO),
    NOKVS("Kvalsund", PortCountries.NO),
    NOKVV("Kvalvika", PortCountries.NO),
    NOKYR("Kyrksaterora", PortCountries.NO),
    NOLAD("Langesund", PortCountries.NO),
    NOLAG("Langevag, Bomlo", PortCountries.NO),
    NOLAN("Langevag", PortCountries.NO),
    NOLAO("Langoya", PortCountries.NO),
    NOLAR("Larvik", PortCountries.NO),
    NOLAS("Leangen Sondre", PortCountries.NO),
    NOLAV("Lavangen", PortCountries.NO),
    NOLAY("Lenangsoyra", PortCountries.NO),
    NOLDS("Lindesnes", PortCountries.NO),
    NOLEA("Leirvik i Hyllestad", PortCountries.NO),
    NOLEF("Leirfjord", PortCountries.NO),
    NOLEK("Leikanger", PortCountries.NO),
    NOLEN("Lensvik", PortCountries.NO),
    NOLEP("Leirpollen", PortCountries.NO),
    NOLEV("Levanger", PortCountries.NO),
    NOLFF("Listraumen", PortCountries.NO),
    NOLGS("Langstein", PortCountries.NO),
    NOLIA("Liavag", PortCountries.NO),
    NOLID("Liland", PortCountries.NO),
    NOLIE("Lier", PortCountries.NO),
    NOLIL("Lillesand", PortCountries.NO),
    NOLIN("Lindas", PortCountries.NO),
    NOLIS("Lierstranda", PortCountries.NO),
    NOLIT("Litangen", PortCountries.NO),
    NOLKA("Skei-Leka", PortCountries.NO),
    NOLKN("Leknes", PortCountries.NO),
    NOLKV("Leksvik", PortCountries.NO),
    NOLND("Lyngdal", PortCountries.NO),
    NOLNE("Leines", PortCountries.NO),
    NOLOD("Lodingen", PortCountries.NO),
    NOLOE("Loen", PortCountries.NO),
    NOLON("Lonevag", PortCountries.NO),
    NOLOP("Loppa", PortCountries.NO),
    NOLOV("Lovund", PortCountries.NO),
    NOLRA("Lura", PortCountries.NO),
    NOLRD("Lardal", PortCountries.NO),
    NOLRE("Lessremman", PortCountries.NO),
    NOLRI("Leirvik (stord)", PortCountries.NO),
    NOLRK("Larkollen", PortCountries.NO),
    NOLSU("Lys&oslash;ysund", PortCountries.NO),
    NOLUL("Lutelandet", PortCountries.NO),
    NOLUR("Luroy", PortCountries.NO),
    NOLUS("Luster", PortCountries.NO),
    NOLVG("Laksevag", PortCountries.NO),
    NOLVK("Laukvik - Vagan", PortCountries.NO),
    NOLYD("Lyngseidet", PortCountries.NO),
    NOLYF("Lysebotn", PortCountries.NO),
    NOLYN("Lyngen", PortCountries.NO),
    NOLYS("Lysaker", PortCountries.NO),
    NOMAH("Maurholen", PortCountries.NO),
    NOMAK("Malvik", PortCountries.NO),
    NOMAL("Malangen", PortCountries.NO),
    NOMAN("Mandal", PortCountries.NO),
    NOMAT("Matre", PortCountries.NO),
    NOMAY("Maloy", PortCountries.NO),
    NOMEH("Mehamn", PortCountries.NO),
    NOMEK("Mekjarvik", PortCountries.NO),
    NOMEL("Melbu", PortCountries.NO),
    NOMEN("Menstad", PortCountries.NO),
    NOMEV("Melsomvik", PortCountries.NO),
    NOMEY("Meloy", PortCountries.NO),
    NOMGR("Manger", PortCountries.NO),
    NOMID("Midsund", PortCountries.NO),
    NOMIS("Misvar", PortCountries.NO),
    NOMIT("Misten", PortCountries.NO),
    NOMJF("Mosjoen", PortCountries.NO),
    NOMLD("Meland", PortCountries.NO),
    NOMLK("Melkoya", PortCountries.NO),
    NOMLM("Malm", PortCountries.NO),
    NOMLT("Moldtustranda", PortCountries.NO),
    NOMOB("Mongstadbase", PortCountries.NO),
    NOMOI("Moi", PortCountries.NO),
    NOMOL("Molde", PortCountries.NO),
    NOMON("Mongstad", PortCountries.NO),
    NOMOR("Morsvikbotn", PortCountries.NO),
    NOMOS("Mosterhamn", PortCountries.NO),
    NOMOV("Molstrevag", PortCountries.NO),
    NOMQN("Mo i rana", PortCountries.NO),
    NOMRV("Muruvik", PortCountries.NO),
    NOMSD("Mjolstadneset", PortCountries.NO),
    NOMSK("Moskenes", PortCountries.NO),
    NOMSN("Moss Nord", PortCountries.NO),
    NOMSS("Moss", PortCountries.NO),
    NOMVV("Mjolkevikvarden", PortCountries.NO),
    NOMYO("Myre-Oksnes", PortCountries.NO),
    NONAU("Naustdal", PortCountries.NO),
    NONDE("Namdalseid", PortCountries.NO),
    NONEO("Nesodden", PortCountries.NO),
    NONEV("Nevlunghamn", PortCountries.NO),
    NONFD("Nordfjordeid", PortCountries.NO),
    NONFO("Nordfosen", PortCountries.NO),
    NONGH("Nygardsviken", PortCountries.NO),
    NONHS("Norheimsund", PortCountries.NO),
    NONIA("Nordhammarvika Industriomrade", PortCountries.NO),
    NONKB("Nordkjosbotn", PortCountries.NO),
    NONOD("Norddal", PortCountries.NO),
    NONOF("Nordfold", PortCountries.NO),
    NONOL("Nordlenangen", PortCountries.NO),
    NONOR("Nordmela", PortCountries.NO),
    NONRY("Naroy", PortCountries.NO),
    NONSF("Nordskaget - Froya", PortCountries.NO),
    NONSN("Nesna", PortCountries.NO),
    NONVK("Narvik", PortCountries.NO),
    NONVS("Nedre Vats", PortCountries.NO),
    NONYE("Nyelv", PortCountries.NO),
    NONYH("Nyhamna", PortCountries.NO),
    NONZC("Larsnes", PortCountries.NO),
    NONZD("Bremnes", PortCountries.NO),
    NONZH("Tofte", PortCountries.NO),
    NONZY("Tromsdalen", PortCountries.NO),
    NOODD("Odda", PortCountries.NO),
    NOOKF("Oksfjord", PortCountries.NO),
    NOOLD("Olden", PortCountries.NO),
    NOOLL("Olderdalen", PortCountries.NO),
    NOOLN("Olen", PortCountries.NO),
    NOOLT("Frafjord", PortCountries.NO),
    NOOLV("Olve", PortCountries.NO),
    NOOMA("Omastranda", PortCountries.NO),
    NOOMB("Ombo", PortCountries.NO),
    NOOOS("Os", PortCountries.NO),
    NOORK("Orkanger", PortCountries.NO),
    NOORN("Skutvik", PortCountries.NO),
    NOORS("Orsta", PortCountries.NO),
    NOOSE("Osnes", PortCountries.NO),
    NOOSL("Oslo", PortCountries.NO),
    NOOSN("Osen", PortCountries.NO),
    NOOSY("Namsos", PortCountries.NO),
    NOOTB("Ottersbogen", PortCountries.NO),
    NOOTO("Ottersoy", PortCountries.NO),
    NOOVG("Olensvag", PortCountries.NO),
    NOOVK("Oltesvik", PortCountries.NO),
    NOOYB("Bogoy", PortCountries.NO),
    NOOYG("Oygarden", PortCountries.NO),
    NOOYS("Oystese", PortCountries.NO),
    NOPAR("Porsanger", PortCountries.NO),
    NOPOR("Porsgrunn", PortCountries.NO),
    NORAD("Rade", PortCountries.NO),
    NORAF("Rafsnes", PortCountries.NO),
    NORAM("Ramsund", PortCountries.NO),
    NORAY("Radoy", PortCountries.NO),
    NORBV("Raudbergvika", PortCountries.NO),
    NORDB("Randaberg", PortCountries.NO),
    NORDY("Rodoy", PortCountries.NO),
    NOREI("Reine", PortCountries.NO),
    NOREK("Rekefjord", PortCountries.NO),
    NOREN("Rennesoy", PortCountries.NO),
    NOREP("Repparfjord", PortCountries.NO),
    NORES("Raunes-Vindafjord", PortCountries.NO),
    NORET("Rost", PortCountries.NO),
    NORFJ("Reinfjord", PortCountries.NO),
    NORIS("Risor", PortCountries.NO),
    NORIV("Risavika", PortCountries.NO),
    NORMJ("Ramfjordnes", PortCountries.NO),
    NORMV("Ramsvika", PortCountries.NO),
    NOROA("Roan", PortCountries.NO),
    NOROE("Royken", PortCountries.NO),
    NOROG("Rognan", PortCountries.NO),
    NOROM("Gjerdsvika", PortCountries.NO),
    NORON("Ronningen", PortCountries.NO),
    NOROV("Rovde", PortCountries.NO),
    NOROY("Snaroya", PortCountries.NO),
    NORSD("Raudsand", PortCountries.NO),
    NORSE("Rosendal", PortCountries.NO),
    NORSH("Risoyhamn", PortCountries.NO),
    NORSS("Rissa", PortCountries.NO),
    NORTL("Rutletangen", PortCountries.NO),
    NORUB("Rubbestadneset", PortCountries.NO),
    NORUN("Runde", PortCountries.NO),
    NORVK("Rorvik", PortCountries.NO),
    NORVR("Rovar", PortCountries.NO),
    NORYF("Rypefjord", PortCountries.NO),
    NORYG("Rygge", PortCountries.NO),
    NOSAA("Skaland", PortCountries.NO),
    NOSAC("Salangsverket", PortCountries.NO),
    NOSAD("Sandefjord", PortCountries.NO),
    NOSAF("Sandeid", PortCountries.NO),
    NOSAG("Vormedal", PortCountries.NO),
    NOSAH("Sandshamn", PortCountries.NO),
    NOSAI("Sandviksberget", PortCountries.NO),
    NOSAK("Stakkvik", PortCountries.NO),
    NOSAL("Salangen", PortCountries.NO),
    NOSAM("Samnanger", PortCountries.NO),
    NOSAS("Sandnes", PortCountries.NO),
    NOSAT("Salten", PortCountries.NO),
    NOSAU("Sauda", PortCountries.NO),
    NOSAX("SandNO", PortCountries.NO),
    NOSAY("Sandsoy", PortCountries.NO),
    NOSBA("Stord base", PortCountries.NO),
    NOSBT("Botn", PortCountries.NO),
    NOSBU("Salsbruket", PortCountries.NO),
    NOSDI("Sandvika", PortCountries.NO),
    NOSDL("Saltdal", PortCountries.NO),
    NOSDN("Sandane", PortCountries.NO),
    NOSDZ("Stordal", PortCountries.NO),
    NOSEJ("Seljeli", PortCountries.NO),
    NOSEK("Seljeli", PortCountries.NO),
    NOSEV("Selva", PortCountries.NO),
    NOSGE("Slagen", PortCountries.NO),
    NOSGT("Skorgeneset", PortCountries.NO),
    NOSHT("Stanghelle", PortCountries.NO),
    NOSID("Savareid", PortCountries.NO),
    NOSIH("Siholmen", PortCountries.NO),
    NOSIP("Skipavik - Gulen", PortCountries.NO),
    NOSIS("Sunde", PortCountries.NO),
    NOSJA("Senja", PortCountries.NO),
    NOSJE("Selje", PortCountries.NO),
    NOSJH("Senjahopen", PortCountries.NO),
    NOSJO("Sjoholt", PortCountries.NO),
    NOSJU("Sjursoja/Oslo", PortCountries.NO),
    NOSJV("Sjovegan", PortCountries.NO),
    NOSKA("Skarholmen", PortCountries.NO),
    NOSKB("Skibotn", PortCountries.NO),
    NOSKD("Skjarhalden", PortCountries.NO),
    NOSKE("Skien", PortCountries.NO),
    NOSKG("Skogsvag", PortCountries.NO),
    NOSKH("Skien Voll", PortCountries.NO),
    NOSKI("Skjerkoya", PortCountries.NO),
    NOSKK("Stokksund- Afjord", PortCountries.NO),
    NOSKL("Skanland", PortCountries.NO),
    NOSKN("Stokmarknes", PortCountries.NO),
    NOSKO("Skodje", PortCountries.NO),
    NOSKU("Skudeneshavn", PortCountries.NO),
    NOSKX("Skogn", PortCountries.NO),
    NOSKY("Skjervoy", PortCountries.NO),
    NOSKZ("Skarsvag", PortCountries.NO),
    NOSLA("Sola", PortCountries.NO),
    NOSLD("Solund", PortCountries.NO),
    NOSLE("Lenangen Sondre", PortCountries.NO),
    NOSLG("Slagentangen", PortCountries.NO),
    NOSLH("Salthella", PortCountries.NO),
    NOSLM("Slemmestad", PortCountries.NO),
    NOSLN("Skjolden", PortCountries.NO),
    NOSLO("Slovag", PortCountries.NO),
    NOSLV("Sløvåg", PortCountries.NO),
    NOSLX("Sortland", PortCountries.NO),
    NOSMO("Smola", PortCountries.NO),
    NOSNE("Sogne", PortCountries.NO),
    NOSNL("Standal", PortCountries.NO),
    NOSNS("Steinesjoen", PortCountries.NO),
    NOSNV("Snekkevik", PortCountries.NO),
    NOSOF("Sorfold", PortCountries.NO),
    NOSOG("Sogndal", PortCountries.NO),
    NOSOJ("Sorkjosen", PortCountries.NO),
    NOSOM("Sommaroy", PortCountries.NO),
    NOSOR("Sorarnoy", PortCountries.NO),
    NOSOS("Svolvaer Osan", PortCountries.NO),
    NOSOV("Sovik", PortCountries.NO),
    NOSOY("Storoya", PortCountries.NO),
    NOSPG("Sarpsborg", PortCountries.NO),
    NOSPK("Skipavik", PortCountries.NO),
    NOSPV("Spjelkavik", PortCountries.NO),
    NOSRA("Sorreisa", PortCountries.NO),
    NOSRD("Sigerfjord", PortCountries.NO),
    NOSRK("Skrolsvik", PortCountries.NO),
    NOSRM("Straumsnes", PortCountries.NO),
    NOSRN("Stranda", PortCountries.NO),
    NOSRO("Skrova", PortCountries.NO),
    NOSRP("Stord", PortCountries.NO),
    NOSRS("Storesund", PortCountries.NO),
    NOSRV("Sirevag", PortCountries.NO),
    NOSRX("Sotra", PortCountries.NO),
    NOSSJ("Sandnessjoen", PortCountries.NO),
    NOSSO("Straumsjoen", PortCountries.NO),
    NOSSS("Sistranda", PortCountries.NO),
    NOSTA("Stathelle", PortCountries.NO),
    NOSTB("Storebo", PortCountries.NO),
    NOSTD("Strand", PortCountries.NO),
    NOSTE("Steinkjer", PortCountries.NO),
    NOSTF("Storfjord", PortCountries.NO),
    NOSTG("Steigen", PortCountries.NO),
    NOSTH("Steinshamn", PortCountries.NO),
    NOSTI("Steinvig", PortCountries.NO),
    NOSTJ("Stjordal", PortCountries.NO),
    NOSTL("Nord-Statland", PortCountries.NO),
    NOSTN("Stavneset - Kristiansund", PortCountries.NO),
    NOSTO("Stokkvagen", PortCountries.NO),
    NOSTR("Stryn", PortCountries.NO),
    NOSTU("Sture", PortCountries.NO),
    NOSTV("Stavern", PortCountries.NO),
    NOSTX("Sto", PortCountries.NO),
    NOSTY("Stjernoya", PortCountries.NO),
    NOSUN("Sunndalsora", PortCountries.NO),
    NOSUR("Surnadal", PortCountries.NO),
    NOSUS("Susort", PortCountries.NO),
    NOSUZ("Stamsund", PortCountries.NO),
    NOSVA("Stavanger East", PortCountries.NO),
    NOSVB("Svartebukt", PortCountries.NO),
    NOSVE("Svelgen", PortCountries.NO),
    NOSVG("Stavanger", PortCountries.NO),
    NOSVI("Ornes", PortCountries.NO),
    NOSVJ("Svolvar", PortCountries.NO),
    NOSVK("Salten verk", PortCountries.NO),
    NOSVO("Haskru lykt", PortCountries.NO),
    NOSVR("Sorvar", PortCountries.NO),
    NOSVT("Stavneset - Rissa", PortCountries.NO),
    NOSVV("Svelvik", PortCountries.NO),
    NOSYK("Sykkylven", PortCountries.NO),
    NOTAE("Tananger", PortCountries.NO),
    NOTAF("Tafjord", PortCountries.NO),
    NOTAU("Tau", PortCountries.NO),
    NOTAV("Torangsvag", PortCountries.NO),
    NOTBO("Tjeldbergodden", PortCountries.NO),
    NOTEJ("Tennfjord", PortCountries.NO),
    NOTHA("Thamshamn", PortCountries.NO),
    NOTIN("Tingvoll", PortCountries.NO),
    NOTJL("Tjotta", PortCountries.NO),
    NOTJO("Tjome", PortCountries.NO),
    NOTJR("Tjorvag", PortCountries.NO),
    NOTJS("Tjeldsund", PortCountries.NO),
    NOTJU("Torjulvagen", PortCountries.NO),
    NOTMV("Tromvik", PortCountries.NO),
    NOTNN("Tonnes", PortCountries.NO),
    NOTOF("Tofte in Hurum", PortCountries.NO),
    NOTOM("Tomrefjord", PortCountries.NO),
    NOTON("Tonsberg", PortCountries.NO),
    NOTOR("Torsken", PortCountries.NO),
    NOTOS("Tromso", PortCountries.NO),
    NOTOV("Tovik", PortCountries.NO),
    NOTOY("Thoroya", PortCountries.NO),
    NOTRD("Trondheim", PortCountries.NO),
    NOTRN("Trana", PortCountries.NO),
    NOTSB("Tyssebotn", PortCountries.NO),
    NOTSD("Torvastad", PortCountries.NO),
    NOTSX("Tyssedal", PortCountries.NO),
    NOTUF("Tufjorden", PortCountries.NO),
    NOTVA("Torsvag", PortCountries.NO),
    NOTVE("Tvedestrand", PortCountries.NO),
    NOTVI("Torvika", PortCountries.NO),
    NOTYN("Tysnes", PortCountries.NO),
    NOTYT("Tytebarvika", PortCountries.NO),
    NOTYV("Tysvar", PortCountries.NO),
    NOUBO("Uloybukt", PortCountries.NO),
    NOULE("Ulstein", PortCountries.NO),
    NOULL("Ullensvang", PortCountries.NO),
    NOULS("Ulsteinvik", PortCountries.NO),
    NOUME("Straume", PortCountries.NO),
    NOUND("Sund - Karmoy", PortCountries.NO),
    NOUSD("Uskedalen", PortCountries.NO),
    NOUTH("Uthaug", PortCountries.NO),
    NOUTN("Utne", PortCountries.NO),
    NOUTS("Utsira", PortCountries.NO),
    NOUTV("Utvorda", PortCountries.NO),
    NOUVK("Ulvik", PortCountries.NO),
    NOVAD("Valldal", PortCountries.NO),
    NOVAE("Valsneset", PortCountries.NO),
    NOVAG("Valevag", PortCountries.NO),
    NOVAK("Vaksdal", PortCountries.NO),
    NOVAL("Valloy", PortCountries.NO),
    NOVAO("Vardo", PortCountries.NO),
    NOVAV("Vannavalen", PortCountries.NO),
    NOVBE("Valberg", PortCountries.NO),
    NOVDA("Volda", PortCountries.NO),
    NOVDL("Vistdal", PortCountries.NO),
    NOVDS("Vadso", PortCountries.NO),
    NOVEG("Vega", PortCountries.NO),
    NOVEO("Vengsoy", PortCountries.NO),
    NOVER("Verdal", PortCountries.NO),
    NOVEY("Varoy", PortCountries.NO),
    NOVGN("Vågan", PortCountries.NO),
    NOVHM("Vikholmen", PortCountries.NO),
    NOVHN("Vadheim", PortCountries.NO),
    NOVID("Vikedal", PortCountries.NO),
    NOVIF("Vindafjord", PortCountries.NO),
    NOVIG("Vigra", PortCountries.NO),
    NOVIL("Vingsand", PortCountries.NO),
    NOVIS("Vik i Sogn", PortCountries.NO),
    NOVKK("Vikkilen", PortCountries.NO),
    NOVKN("Vikna", PortCountries.NO),
    NOVLL("Voll", PortCountries.NO),
    NOVMD("Vedavagen", PortCountries.NO),
    NOVNG("Vevang", PortCountries.NO),
    NOVNJ("Vinjeora", PortCountries.NO),
    NOVNN("Vannoy", PortCountries.NO),
    NOVNV("Vannvag", PortCountries.NO),
    NOVOH("Vagaholmen", PortCountries.NO),
    NOVRE("Vrengen", PortCountries.NO),
    NOVRR("Verran", PortCountries.NO),
    NOVSM("Vikan - Smola", PortCountries.NO),
    NOVSN("Visnes - Eide", PortCountries.NO),
    NOVST("Vestnes", PortCountries.NO),
    NOVTL("Vartdal", PortCountries.NO),
    NOVTS("Vats", PortCountries.NO),
    NOVVG("Vagsvag", PortCountries.NO),
    NOVVY("Vestvagoy", PortCountries.NO),
    NOXKF("Kafjord anchorage", PortCountries.NO),
    NOZAA("Slagen Anchorage", PortCountries.NO),
    NOZAC("Akkarfjord", PortCountries.NO),
    NOZAF("Amoyfjorden", PortCountries.NO),
    NOZAL("Altsula Anchorage", PortCountries.NO),
    NOZAR("Akrafjorden", PortCountries.NO),
    NOZAZ("Sarnesfjorden Anchorage", PortCountries.NO),
    NOZBA("Balsnesodden", PortCountries.NO),
    NOZBB("Breiangen", PortCountries.NO),
    NOZBC("Byfjorden - Stavanger", PortCountries.NO),
    NOZBD("Buadjupet", PortCountries.NO),
    NOZBE("Belgen", PortCountries.NO),
    NOZBF("Boknafjorden", PortCountries.NO),
    NOZBG("Byfjorden - Bergen", PortCountries.NO),
    NOZBH("Bomlafjorden", PortCountries.NO),
    NOZBI("Buefjorden", PortCountries.NO),
    NOZBJ("Bjornafjorden", PortCountries.NO),
    NOZBQ("Borroyfjorden", PortCountries.NO),
    NOZBS("Bjornsund", PortCountries.NO),
    NOZBV("Buvika Anchorage", PortCountries.NO),
    NOZCB("Hustadvika", PortCountries.NO),
    NOZCH("Sognefjorden", PortCountries.NO),
    NOZCI("Porsangvika Anchorage", PortCountries.NO),
    NOZCJ("Strandviksflaket Anchorage", PortCountries.NO),
    NOZCL("Klosterfjorden", PortCountries.NO),
    NOZCQ("Blasoppbukta - Halden", PortCountries.NO),
    NOZCS("Grotsundet", PortCountries.NO),
    NOZCT("Lyngstuva", PortCountries.NO),
    NOZDA("Dalasundet", PortCountries.NO),
    NOZDD("Dragnesodden", PortCountries.NO),
    NOZDF("Digerflesa", PortCountries.NO),
    NOZDI("Digernessundet", PortCountries.NO),
    NOZDK("Dragnesklubben Anchorage", PortCountries.NO),
    NOZDM("Digermulen", PortCountries.NO),
    NOZDU("Duken", PortCountries.NO),
    NOZFB("Fensfjorden", PortCountries.NO),
    NOZFC("Finnoyfjorden", PortCountries.NO),
    NOZFF("Falkeidflaet Anchorage", PortCountries.NO),
    NOZFG("Flesa", PortCountries.NO),
    NOZFI("Fiskefjord Anchorage", PortCountries.NO),
    NOZFJ("Froysjoen", PortCountries.NO),
    NOZFK("Fugloyfjorden", PortCountries.NO),
    NOZFM("Freifjorden 1 Anchorage", PortCountries.NO),
    NOZFN("Fosen Anchorage - Karmoy", PortCountries.NO),
    NOZFO("Fonnesflaket Anchorage", PortCountries.NO),
    NOZFR("Frierfjorden", PortCountries.NO),
    NOZFZ("Forresfjorden", PortCountries.NO),
    NOZGJ("Gjaslingan", PortCountries.NO),
    NOZGS("Grasholmen", PortCountries.NO),
    NOZHB("Helgerobukta", PortCountries.NO),
    NOZHC("Hanasandsundet", PortCountries.NO),
    NOZHD("Hanoysundet", PortCountries.NO),
    NOZHF("Hervikfjorden", PortCountries.NO),
    NOZHI("Haugsoytangen anchorage", PortCountries.NO),
    NOZHN("Harstad Roads", PortCountries.NO),
    NOZHP("Hellmobotn", PortCountries.NO),
    NOZHQ("Hidlefjorden", PortCountries.NO),
    NOZHU("Husoyflaket", PortCountries.NO),
    NOZHW("Hustadsundet", PortCountries.NO),
    NOZJU("Julsundet", PortCountries.NO),
    NOZKB("Krigsborgan", PortCountries.NO),
    NOZKE("Krakhellesundet", PortCountries.NO),
    NOZKH("Kvasefjorden", PortCountries.NO),
    NOZKM("Karlsmedgrunnen Anchorage", PortCountries.NO),
    NOZKQ("Kafjorden", PortCountries.NO),
    NOZLB("Langenuen", PortCountries.NO),
    NOZLC("Langsundet", PortCountries.NO),
    NOZLD("Lauksundet", PortCountries.NO),
    NOZLE("Lindoysundet", PortCountries.NO),
    NOZLF("Lofotodden  Anchorage", PortCountries.NO),
    NOZLH("Langgrunnen Anchorage", PortCountries.NO),
    NOZLI("Listafjorden", PortCountries.NO),
    NOZLN("Langoytangen Pilot boarding area", PortCountries.NO),
    NOZLS("Leroyosen", PortCountries.NO),
    NOZLU("Lukksundet", PortCountries.NO),
    NOZLY("Lysefjorden", PortCountries.NO),
    NOZMA("Marnesskagen - Anchorage", PortCountries.NO),
    NOZMB("Mandal Anchorage", PortCountries.NO),
    NOZMC("Mangerfjorden", PortCountries.NO),
    NOZMD("Mastrafjorden", PortCountries.NO),
    NOZMM("Sammelsund", PortCountries.NO),
    NOZMS("Myken Sea", PortCountries.NO),
    NOZMU("Maursundet", PortCountries.NO),
    NOZNA("Naeroysundet", PortCountries.NO),
    NOZNC("Nordfjorden", PortCountries.NO),
    NOZND("Neverdalsbukta Anchorage", PortCountries.NO),
    NOZNH("Nordreholsflu", PortCountries.NO),
    NOZNJ("Nusfjord", PortCountries.NO),
    NOZNL("Nordlandsflaget", PortCountries.NO),
    NOZNN("Nesnaflaket Anchorage", PortCountries.NO),
    NOZNR("Troms Anchorage", PortCountries.NO),
    NOZNS("Nedstrandsfjorden", PortCountries.NO),
    NOZNT("Tomma", PortCountries.NO),
    NOZNV("Narvik Anchorage", PortCountries.NO),
    NOZNY("Myrflesan Ankring", PortCountries.NO),
    NOZOC("Ormoysand anchorage", PortCountries.NO),
    NOZOK("Oksoy Pilot Boarding Area", PortCountries.NO),
    NOZOM("Tomrefjorden", PortCountries.NO),
    NOZOS("Josenfjorden", PortCountries.NO),
    NOZPP("Repparfjorden", PortCountries.NO),
    NOZQC("Mageroysundet", PortCountries.NO),
    NOZQW("Stjernsundet", PortCountries.NO),
    NOZRA("Reinoya Anchorage", PortCountries.NO),
    NOZRB("Rarftsundet", PortCountries.NO),
    NOZRD("Kirkenes Anchorage", PortCountries.NO),
    NOZRE("Reine Sea", PortCountries.NO),
    NOZRF("Rekstafjorden", PortCountries.NO),
    NOZRM("Drammen Anchorage", PortCountries.NO),
    NOZRN("Verrafjorden", PortCountries.NO),
    NOZRO("Rovarsfjorden", PortCountries.NO),
    NOZRS("Rauneskjar West", PortCountries.NO),
    NOZRT("Rosthavet", PortCountries.NO),
    NOZRU("Raudoya", PortCountries.NO),
    NOZRY("Rotsundet", PortCountries.NO),
    NOZSA("Sastein", PortCountries.NO),
    NOZSB("Soroysundet", PortCountries.NO),
    NOZSD("Svartisen", PortCountries.NO),
    NOZSE("Snekkeflua", PortCountries.NO),
    NOZSF("Stefjorden", PortCountries.NO),
    NOZSI("Sildagapet", PortCountries.NO),
    NOZSJ("Selbjornsfjorden", PortCountries.NO),
    NOZSK("Skanevikfjorden", PortCountries.NO),
    NOZSL("Sortland Anchorage", PortCountries.NO),
    NOZSN("Sandverken lighthouse", PortCountries.NO),
    NOZSQ("Skinnfelltangen", PortCountries.NO),
    NOZST("Stad", PortCountries.NO),
    NOZSU("Skagoysundet", PortCountries.NO),
    NOZSW("Sklinna light house", PortCountries.NO),
    NOZSZ("Sarnesfjorden South Anchorage", PortCountries.NO),
    NOZTA("Talgsjoen", PortCountries.NO),
    NOZTB("Lanesgrunnen - Tromso", PortCountries.NO),
    NOZTF("Trollfjorden", PortCountries.NO),
    NOZTG("Tjeldsundet", PortCountries.NO),
    NOZTI("Torget", PortCountries.NO),
    NOZTJ("Tanafjorden", PortCountries.NO),
    NOZTR("Trondheim Reden", PortCountries.NO),
    NOZTT("Nordspissen - Tromso", PortCountries.NO),
    NOZUL("Ullsfjord", PortCountries.NO),
    NOZVA("Vagsfjorden", PortCountries.NO),
    NOZVB("Mastadbukta Anchorage", PortCountries.NO),
    NOZVC("Vannoy Anchorage", PortCountries.NO),
    NOZVD("Ylvingen", PortCountries.NO),
    NOZVE("Varangerfjorden", PortCountries.NO),
    NOZVF("Valderhaugfjorden", PortCountries.NO),
    NOZVH("Vatlestraumen", PortCountries.NO),
    NOZVO("Skarsvag Anchorage", PortCountries.NO),
    NOZVS("Kvalsundet", PortCountries.NO),
    NOZVU("Vagsholmsundet", PortCountries.NO),
    NOZWS("Vargsundet", PortCountries.NO),
    NOZXA("Karmsundet", PortCountries.NO),
    NOZXV("Verdal Anchorage", PortCountries.NO),
    NOZZS("Sarnesfjorden North Anchorage", PortCountries.NO),
    PLBZI("Burzenin", PortCountries.PL),
    PLDAR("Darlowo", PortCountries.PL),
    PLDZN("Dziwnow", PortCountries.PL),
    PLELB("Elblag", PortCountries.PL),
    PLFBK("Frombork", PortCountries.PL),
    PLGDN("Gdansk", PortCountries.PL),
    PLGDY("Gdynia", PortCountries.PL),
    PLGKZ("GORKI ZACHODNIE", PortCountries.PL),
    PLHEL("Hel", PortCountries.PL),
    PLKOL("Kolobrzeg", PortCountries.PL),
    PLLEA("Leba", PortCountries.PL),
    PLMID("Miedzyzdroje", PortCountries.PL),
    PLMRE("MRZEZYNO", PortCountries.PL),
    PLNCH("NIECHORZE", PortCountries.PL),
    PLNOW("Nowy Port/Gdansk", PortCountries.PL),
    PLNWA("Nowe Warpno", PortCountries.PL),
    PLPLC("Police", PortCountries.PL),
    PLRWL("REWAL", PortCountries.PL),
    PLSJK("Karsibor", PortCountries.PL),
    PLSOP("Sopot", PortCountries.PL),
    PLSPA("Stepnica", PortCountries.PL),
    PLSWI("Swinoujscie", PortCountries.PL),
    PLSZZ("Szczecin", PortCountries.PL),
    PLTBZ("Trzebiez", PortCountries.PL),
    PLUST("Ustka", PortCountries.PL),
    PLWLA("Wladyslawowo", PortCountries.PL),
    PLWLI("Wolin", PortCountries.PL),
    PTADH("Angra do Heroísmo", PortCountries.PT),
    PTAVE("Aveiro", PortCountries.PT),
    PTCDP("Cais do Pico", PortCountries.PT),
    PTCNL("Canical", PortCountries.PT),
    PTFAO("Faro", PortCountries.PT),
    PTFDF("Figueira da Foz", PortCountries.PT),
    PTFNC("Funchal", PortCountries.PT),
    PTHOR("Horta", PortCountries.PT),
    PTLAJ("Lajes das Flores", PortCountries.PT),
    PTLEI("Leixoes", PortCountries.PT),
    PTLIS("Lisbon", PortCountries.PT),
    PTPDL("Ponta Delgada", PortCountries.PT),
    PTPRG("Praia da Graciosa", PortCountries.PT),
    PTPRM("Portimao", PortCountries.PT),
    PTPRV("Praia da Vitoria", PortCountries.PT),
    PTPXO("Porto Santo", PortCountries.PT),
    PTSET("Setubal", PortCountries.PT),
    PTSIE("Sines", PortCountries.PT),
    PTVDC("Viana do castelo", PortCountries.PT),
    PTVDP("Vila do Porto", PortCountries.PT),
    PTVEL("Velas de Sao Jorge", PortCountries.PT),
    PTVRE("Vila real de santo antonio", PortCountries.PT),
    RELPT("Le Port", null),
    REPDG("Port de Pointe des Galets", null),
    REPOS("Possession", null),
    REREU("Reunion", null),
    ROAGI("Agigea", PortCountries.RO),
    ROBRA("Braila", PortCountries.RO),
    ROCND("Constanta", PortCountries.RO),
    ROGAL("Galati", PortCountries.RO),
    ROMAG("Mangalia", PortCountries.RO),
    ROMID("Midia", PortCountries.RO),
    ROSUL("Sulina", PortCountries.RO),
    ROTCE("Tulcea", PortCountries.RO),
    RUAMV("Amderma", PortCountries.RU),
    RUARH("Arkhangelsk", PortCountries.RU),
    RUASF("Astrakhan", PortCountries.RU),
    RUAZO("Azov", PortCountries.RU),
    RUBLT("Baltiysk", PortCountries.RU),
    RUBNK("Bronka Port", PortCountries.RU),
    RUCPC("Cpc Terminal", PortCountries.RU),
    RUDKA("De-Kastri", PortCountries.RU),
    RUDUD("Dudinka", PortCountries.RU),
    RUKAN("Kandalaksha", PortCountries.RU),
    RUKDT("Kronshtadt", PortCountries.RU),
    RUKGD("Kaliningrad", PortCountries.RU),
    RUKOR("Korsakov", PortCountries.RU),
    RUKZP("Kavkaz", PortCountries.RU),
    RULED("Saint Petersburg", PortCountries.RU),
    RULOM("Lomonosov", PortCountries.RU),
    RUMMK("Murmansk", PortCountries.RU),
    RUNEV("Nevelsk", PortCountries.RU),
    RUNJK("Nakhodka", PortCountries.RU),
    RUNVS("Novorossiysk", PortCountries.RU),
    RUONG("Onega", PortCountries.RU),
    RUPKC("Petropavlovsk-Kamchatsky", PortCountries.RU),
    RUPRI("Primorsk", PortCountries.RU),
    RURBK("Lomonosov", PortCountries.RU),
    RUROV("Rostov/Don", PortCountries.RU),
    RUSAB("Sabetta", PortCountries.RU),
    RUSOC("Sochi", PortCountries.RU),
    RUTAG("Taganrog", PortCountries.RU),
    RUTAM("Taman", PortCountries.RU),
    RUTMR("Temryuk", PortCountries.RU),
    RUTUA("Tuapse", PortCountries.RU),
    RUUKK("Ust-Kamchatsk", PortCountries.RU),
    RUULU("Ust-Luga", PortCountries.RU),
    RUVIT("Vitino", PortCountries.RU),
    RUVNN("Vanino", PortCountries.RU),
    RUVVO("Vladivostok", PortCountries.RU),
    RUVYG("Vyborg", PortCountries.RU),
    RUVYP("Vostochnyy", PortCountries.RU),
    RUVYS("Vysotsk", PortCountries.RU),
    RUYEY("Eysk", PortCountries.RU),
    RUZEM("Zeleniy Mys", PortCountries.RU),
    SAVLANDSVIK("NOSVL", PortCountries.SA),
    SE064("Slite port, Anchorage", PortCountries.SE),
    SE065("Slite road B, Anchorage", PortCountries.SE),
    SEAAR("Ar", PortCountries.SE),
    SEADG("Arildslage", PortCountries.SE),
    SEAGB("Agnesberg", PortCountries.SE),
    SEAGE("Ange", PortCountries.SE),
    SEAGN("Alvangen", PortCountries.SE),
    SEAHU("Ahus", PortCountries.SE),
    SEALA("Ala", PortCountries.SE),
    SEALF("Alfredshem", PortCountries.SE),
    SEALN("Alvenas", PortCountries.SE),
    SEAMA("Amal", PortCountries.SE),
    SEANK("Ankarsvik", PortCountries.SE),
    SEANN("Ann", PortCountries.SE),
    SEARA("Arboga", PortCountries.SE),
    SEARK("Arnoviken", PortCountries.SE),
    SEARV("Arvika", PortCountries.SE),
    SEASD("Askersund", PortCountries.SE),
    SEASU("Arkosund", PortCountries.SE),
    SEBAA("Balsta", PortCountries.SE),
    SEBAC("Backviken", PortCountries.SE),
    SEBAS("Bastad", PortCountries.SE),
    SEBAT("Batskarsnas", PortCountries.SE),
    SEBBH("Barsebackshamn", PortCountries.SE),
    SEBDQ("Boda", PortCountries.SE),
    SEBEA("Bergkvara", PortCountries.SE),
    SEBER("Bergs oljehamn", PortCountries.SE),
    SEBGA("Berga orlogsskolor", PortCountries.SE),
    SEBJR("Bjarred", PortCountries.SE),
    SEBLA("Blankaholm", PortCountries.SE),
    SEBLD("Bovallstrand", PortCountries.SE),
    SEBOG("Borensberg", PortCountries.SE),
    SEBOH("Bohus", PortCountries.SE),
    SEBOL("Bollstabruk", PortCountries.SE),
    SEBOM("Borgholm", PortCountries.SE),
    SEBRE("Bredviken", PortCountries.SE),
    SEBRO("Brofjorden", PortCountries.SE),
    SEBRT("Brottby", PortCountries.SE),
    SEBRU("Brunflo", PortCountries.SE),
    SEBTF("Bengtsfors", PortCountries.SE),
    SEBUR("Burea", PortCountries.SE),
    SEBUV("Burgsvik", PortCountries.SE),
    SEBVK("Braviken", PortCountries.SE),
    SEBYX("Byxelkrok", PortCountries.SE),
    SEDEG("Degerhamn", PortCountries.SE),
    SEDJN("Djuron", PortCountries.SE),
    SEDJP("Djupvik", PortCountries.SE),
    SEDJU("Djurmo", PortCountries.SE),
    SEDLA("Dalaro", PortCountries.SE),
    SEDOM("Domsjo", PortCountries.SE),
    SEDON("Donso", PortCountries.SE),
    SEDRT("Drottningholm", PortCountries.SE),
    SEDYN("Dynas", PortCountries.SE),
    SEELL("Elleholm", PortCountries.SE),
    SEELO("Ellos", PortCountries.SE),
    SEENK("Enkoping", PortCountries.SE),
    SEESS("Essvik", PortCountries.SE),
    SEFAG("Falkenberg", PortCountries.SE),
    SEFAK("Fagervik", PortCountries.SE),
    SEFAR("Farjestaden", PortCountries.SE),
    SEFBK("Fiskebackskil", PortCountries.SE),
    SEFIG("Figeholm", PortCountries.SE),
    SEFIL("Filipsstad", PortCountries.SE),
    SEFIS("Fiskeback", PortCountries.SE),
    SEFJA("Fjallbacka", PortCountries.SE),
    SEFKG("Falkoping", PortCountries.SE),
    SEFLI("Flivik", PortCountries.SE),
    SEFOR("Forsmark", PortCountries.SE),
    SEFRA("Frano", PortCountries.SE),
    SEFSB("Falsterbo", PortCountries.SE),
    SEFSD("Farosund", PortCountries.SE),
    SEGAM("Gamleby", PortCountries.SE),
    SEGKS("Gustavsvik/Stockholm", PortCountries.SE),
    SEGKV("Grankullaviken", PortCountries.SE),
    SEGMS("Grums", PortCountries.SE),
    SEGOA("Gota", PortCountries.SE),
    SEGOR("Goringseholm", PortCountries.SE),
    SEGOT("Goteborg", PortCountries.SE),
    SEGRD("Grundsund", PortCountries.SE),
    SEGRE("Grebbestad", PortCountries.SE),
    SEGRH("Grisslehamn", PortCountries.SE),
    SEGRU("Gruvon", PortCountries.SE),
    SEGUB("Gustavsberg", PortCountries.SE),
    SEGUN("Gunnebo", PortCountries.SE),
    SEGUS("Gustavsik", PortCountries.SE),
    SEGVN("Gravarna", PortCountries.SE),
    SEGVX("Gavle", PortCountries.SE),
    SEHAA("Haparanda", PortCountries.SE),
    SEHAC("Hackas", PortCountries.SE),
    SEHAD("Halmstad", PortCountries.SE),
    SEHAH("Haraholmen", PortCountries.SE),
    SEHAK("Hallstavik", PortCountries.SE),
    SEHAN("Hargshamn", PortCountries.SE),
    SEHAS("Hallstanas", PortCountries.SE),
    SEHBG("Hamburgsund", PortCountries.SE),
    SEHBV("Hasselbyverket", PortCountries.SE),
    SEHEL("Helsingborg", PortCountries.SE),
    SEHER("Herrang", PortCountries.SE),
    SEHGS("Hogsjo", PortCountries.SE),
    SEHLD("Holmsund", PortCountries.SE),
    SEHLS("Hallekis", PortCountries.SE),
    SEHMR("Hammar", PortCountries.SE),
    SEHNB("Horneborg", PortCountries.SE),
    SEHND("Harnosand", PortCountries.SE),
    SEHNF("Hornefors", PortCountries.SE),
    SEHOG("Hoganas", PortCountries.SE),
    SEHON("Honsater", PortCountries.SE),
    SEHST("Heestrand", PortCountries.SE),
    SEHUN("Hunnebostrand", PortCountries.SE),
    SEHUS("Husum", PortCountries.SE),
    SEHUV("Hudiksvall", PortCountries.SE),
    SEHYP("Hyppeln", PortCountries.SE),
    SEIGG("Iggesund", PortCountries.SE),
    SEJAR("Jarfalla", PortCountries.SE),
    SEJAT("Jatterson", PortCountries.SE),
    SEJKG("Jonkoping", PortCountries.SE),
    SEJNA("Jorlanda", PortCountries.SE),
    SEJOH("Johannedal", PortCountries.SE),
    SEKAA("Karlskrona", PortCountries.SE),
    SEKAF("Straa", PortCountries.SE),
    SEKAG("Kage", PortCountries.SE),
    SEKAK("Karlsvik", PortCountries.SE),
    SEKAL("Kalmarsand", PortCountries.SE),
    SEKAN("Karlshamn", PortCountries.SE),
    SEKAO("Karo", PortCountries.SE),
    SEKAS("Karskar", PortCountries.SE),
    SEKAT("Katthammarsvik", PortCountries.SE),
    SEKAX("Kalix", PortCountries.SE),
    SEKBK("Karlsholmsbruk", PortCountries.SE),
    SEKGG("Kagghamra", PortCountries.SE),
    SEKGM("Klagshamn", PortCountries.SE),
    SEKGR("Kungsor", PortCountries.SE),
    SEKHN("Kristinehamn", PortCountries.SE),
    SEKID("Kristianstad", PortCountries.SE),
    SEKKS("Kyrkesund", PortCountries.SE),
    SEKLA("Klavrestrom", PortCountries.SE),
    SEKLD("Kladesholmen", PortCountries.SE),
    SEKLI("Klintehamn", PortCountries.SE),
    SEKLR("Kalmar", PortCountries.SE),
    SEKMH("Kopmanholmen", PortCountries.SE),
    SEKOG("Koping", PortCountries.SE),
    SEKPH("Kappelshamn", PortCountries.SE),
    SEKPS("Kapellskar", PortCountries.SE),
    SEKRF("Kramfors", PortCountries.SE),
    SEKRH("Karehamn", PortCountries.SE),
    SEKSD("Karlstad", PortCountries.SE),
    SEKUA("Kungsbacka", PortCountries.SE),
    SEKUB("Kubikenborg", PortCountries.SE),
    SEKUN("Kungshamn", PortCountries.SE),
    SEKUV("Kungalv", PortCountries.SE),
    SEKVA("Kvarnholmen", PortCountries.SE),
    SEKVH("Kopparverkshamen", PortCountries.SE),
    SEKXV("Karlsborg Axelvik", PortCountries.SE),
    SEKYR("Kyrkebyn", PortCountries.SE),
    SELAA("Landskrona", PortCountries.SE),
    SELAV("Landvetter", PortCountries.SE),
    SELDK("Lidkoping", PortCountries.SE),
    SELDO("Lodose", PortCountries.SE),
    SELED("Lilla Edet", PortCountries.SE),
    SELIM("Limhamn", PortCountries.SE),
    SELIO("Lidingo", PortCountries.SE),
    SELIS("Linanas", PortCountries.SE),
    SELJU("Ljusne", PortCountries.SE),
    SELLA("Lulea", PortCountries.SE),
    SELOD("Loddekopinge", PortCountries.SE),
    SELOM("Lomma", PortCountries.SE),
    SELOT("Loten", PortCountries.SE),
    SELOU("Loudden", PortCountries.SE),
    SELUG("Lungvik", PortCountries.SE),
    SELUN("Lovholmen", PortCountries.SE),
    SELVR("Lovanger", PortCountries.SE),
    SELYS("Lysekil", PortCountries.SE),
    SEMAD("Mariestad", PortCountries.SE),
    SEMAN("Marsviken", PortCountries.SE),
    SEMAR("Marieberg", PortCountries.SE),
    SEMDM("Munkedalshamn", PortCountries.SE),
    SEMEM("Mem", PortCountries.SE),
    SEMLE("Molle", PortCountries.SE),
    SEMLO("Mollosund", PortCountries.SE),
    SEMMA("Malmo", PortCountries.SE),
    SEMON("Monsteras/Jatterson", PortCountries.SE),
    SEMOR("Morbylanga", PortCountries.SE),
    SEMOT("Motala", PortCountries.SE),
    SEMRF("Mariefred", PortCountries.SE),
    SEMSD("Marstrand", PortCountries.SE),
    SEMSK("Musko", PortCountries.SE),
    SEMUN("Munksund", PortCountries.SE),
    SENAS("Nas", PortCountries.SE),
    SENAV("Navekvarn", PortCountries.SE),
    SENJA("Norrbotten jarnverk-SSAB", PortCountries.SE),
    SENOE("Norrtajle", PortCountries.SE),
    SENOG("Nordmaling", PortCountries.SE),
    SENOL("Nol", PortCountries.SE),
    SENOR("Norrbyskar", PortCountries.SE),
    SENOT("Norrsundet", PortCountries.SE),
    SENRK("Norrkoping", PortCountries.SE),
    SENST("Norastrom", PortCountries.SE),
    SENYG("Nygard", PortCountries.SE),
    SENYN("Nynashamn", PortCountries.SE),
    SENYO("Nykoping", PortCountries.SE),
    SEOAX("Oaxen", PortCountries.SE),
    SEOBB("Obbola", PortCountries.SE),
    SEOCO("Ockero", PortCountries.SE),
    SEOEN("On", PortCountries.SE),
    SEOER("Ornskoldsvik", PortCountries.SE),
    SEOGR("Oregrund", PortCountries.SE),
    SEORT("Ortviken", PortCountries.SE),
    SEORV("Orviken", PortCountries.SE),
    SEOSK("Oskarshamn", PortCountries.SE),
    SEOST("Ostrand", PortCountries.SE),
    SEOTT("Otterbacken", PortCountries.SE),
    SEOXE("Oxelosund", PortCountries.SE),
    SEPAS("Paskallavik", PortCountries.SE),
    SEPHM("Pataholm", PortCountries.SE),
    SEPIT("Pitea", PortCountries.SE),
    SERAA("Raa", PortCountries.SE),
    SERAM("Ramvik", PortCountries.SE),
    SERBG("Rosenborg", PortCountries.SE),
    SERBY("Ronnebyhamn", PortCountries.SE),
    SERIN("Ringhals", PortCountries.SE),
    SERNB("Ronneby", PortCountries.SE),
    SERNG("Ronnang", PortCountries.SE),
    SERNH("Ronehamn", PortCountries.SE),
    SEROR("Ronnskar", PortCountries.SE),
    SEROV("Ronnskarsverken", PortCountries.SE),
    SERUV("Rundvik", PortCountries.SE),
    SESAE("Sandarne", PortCountries.SE),
    SESAF("Saffle", PortCountries.SE),
    SESAK("Sandvik", PortCountries.SE),
    SESBB("Saltsjo-Boo", PortCountries.SE),
    SESBN("Saltsjobaden", PortCountries.SE),
    SESDK("Sundsbruk", PortCountries.SE),
    SESDL("Sundsvall", PortCountries.SE),
    SESDS("Studsvik", PortCountries.SE),
    SESES("Seskaro", PortCountries.SE),
    SESFT("Skelleftea", PortCountries.SE),
    SESGM("Skagshamn", PortCountries.SE),
    SESGT("Sigtuna", PortCountries.SE),
    SESIK("Sikea", PortCountries.SE),
    SESIM("Simrishamn", PortCountries.SE),
    SESKB("Skarblacka", PortCountries.SE),
    SESKE("Skelleftehamn", PortCountries.SE),
    SESKL("Skalhamn", PortCountries.SE),
    SESKM("Skarhamn", PortCountries.SE),
    SESKN("Skuthamn", PortCountries.SE),
    SESKO("Skoghall", PortCountries.SE),
    SESKR("Skredsvik", PortCountries.SE),
    SESKT("Skattkarr", PortCountries.SE),
    SESLI("Slite", PortCountries.SE),
    SESMD("Stromstad", PortCountries.SE),
    SESMN("Storuman", PortCountries.SE),
    SESMO("Smogen", PortCountries.SE),
    SESMS("Salmis", PortCountries.SE),
    SESND("Svanesund", PortCountries.SE),
    SESNR("Skanor", PortCountries.SE),
    SESOE("Sodertalje", PortCountries.SE),
    SESOG("Soderkoping", PortCountries.SE),
    SESOL("Solvesborg", PortCountries.SE),
    SESOO("Soderhamn", PortCountries.SE),
    SESOR("Soraker", PortCountries.SE),
    SESPP("Simpevarp", PortCountries.SE),
    SESPR("Sprangsviken", PortCountries.SE),
    SESSR("Skutskar", PortCountries.SE),
    SESTA("Stocka", PortCountries.SE),
    SESTE("Stenungsund", PortCountries.SE),
    SESTG("Stigtomta", PortCountries.SE),
    SESTI("Stillingson", PortCountries.SE),
    SESTK("Stockvik", PortCountries.SE),
    SESTL("Saltkallan", PortCountries.SE),
    SESTO("Stockholm", PortCountries.SE),
    SESTQ("Strangnas", PortCountries.SE),
    SESTU("Stugsund", PortCountries.SE),
    SESTV("Stora Vika", PortCountries.SE),
    SESTY("Styrso", PortCountries.SE),
    SESUD("Stocksund", PortCountries.SE),
    SESUG("Sundbyberg", PortCountries.SE),
    SESUN("Sund", PortCountries.SE),
    SESUR("Surte", PortCountries.SE),
    SESUS("Storugns", PortCountries.SE),
    SESVE("Svenstavik", PortCountries.SE),
    SESVK("Svartvik", PortCountries.SE),
    SESVS("Saivisnas", PortCountries.SE),
    SESVX("Svano", PortCountries.SE),
    SETHN("Trollhattan", PortCountries.SE),
    SETOA("Torshalla", PortCountries.SE),
    SETOE("Tore", PortCountries.SE),
    SETOV("Torekov", PortCountries.SE),
    SETRG("Trelleborg", PortCountries.SE),
    SETTD("Tomteboda", PortCountries.SE),
    SETUN("Tunadal", PortCountries.SE),
    SEUDD("Uddevalla", PortCountries.SE),
    SEUGN("Ulebergshamn", PortCountries.SE),
    SEULF("Ulfvik", PortCountries.SE),
    SEUME("Umea", PortCountries.SE),
    SEUND("Underas", PortCountries.SE),
    SEUPP("Uppsala", PortCountries.SE),
    SEURS("Ursviken", PortCountries.SE),
    SEUTA("Utansjo", PortCountries.SE),
    SEVAG("Varberg", PortCountries.SE),
    SEVAJ("Vaja", PortCountries.SE),
    SEVAK("Valdemarsvik", PortCountries.SE),
    SEVAL("Vallvik", PortCountries.SE),
    SEVAN("Vanersborg", PortCountries.SE),
    SEVBY("Visby", PortCountries.SE),
    SEVER("Verkeback", PortCountries.SE),
    SEVGN("Vargon", PortCountries.SE),
    SEVGO("Vrango", PortCountries.SE),
    SEVIA("Vingaker", PortCountries.SE),
    SEVIV("Vivstavarv", PortCountries.SE),
    SEVRB("Varby", PortCountries.SE),
    SEVRM("Varmdo", PortCountries.SE),
    SEVST("Vasteras", PortCountries.SE),
    SEVVK("Vastervik", PortCountries.SE),
    SEVXH("Vaxholm", PortCountries.SE),
    SEWAL("Wallhamn", PortCountries.SE),
    SEYST("Ystad", PortCountries.SE),
    SIIZO("Izola", PortCountries.SI),
    SIKOP("Koper", PortCountries.SI),
    SIPIR("Piran", PortCountries.SI),
    SJBAR("Barentsburg", null),
    SJHIN("Hinlopen", null),
    SJLYR("Longyearbyen", null),
    SJNYA("Ny-Alesund", null),
    SJSVE("Sveagruva", null),
    SJZTE("Tempelfjorden", null),
    SJZVA("Svea-Blahuken anchorage", null),
    TNARI("Ariana", PortCountries.TN),
    TNASH("Ashtart Terminal", PortCountries.TN),
    TNBIZ("Bizerte", PortCountries.TN),
    TNBJC("Borj Cedria", PortCountries.TN),
    TNCHB("Chebba", PortCountries.TN),
    TNDID("Didon", PortCountries.TN),
    TNDJE("Djerba", PortCountries.TN),
    TNGAE("Gabes", PortCountries.TN),
    TNHMM("Al Hammamat", PortCountries.TN),
    TNJAR("Jarjis", PortCountries.TN),
    TNKEB("Kebili", PortCountries.TN),
    TNKEM("Ksibet el Mediouni", PortCountries.TN),
    TNLGN("La Goulette Nord", PortCountries.TN),
    TNLSK("La Skhirra", PortCountries.TN),
    TNMAD("Mahdia", PortCountries.TN),
    TNMBA("Menzel Bourguiba", PortCountries.TN),
    TNOUD("Oudna", PortCountries.TN),
    TNRDS("Port of Rades", PortCountries.TN),
    TNSFA("Sfax", PortCountries.TN),
    TNSLN("Soliman", PortCountries.TN),
    TNSUS("Sousse", PortCountries.TN),
    TNTAT("Tazerka Terminal", PortCountries.TN),
    TNTUN("Tunis", PortCountries.TN),
    TNTZE("Al Marsa", PortCountries.TN),
    TNZRZ("Zarzis", PortCountries.TN),
    USAL3("LOUISIANA - ALLIANCE", PortCountries.US),
    USBAL("Baltimore", PortCountries.US),
    USBAY("NEW JERSEY - BAYONNE", PortCountries.US),
    USBBT("TEXAS - BARBOURS CUT", PortCountries.US),
    USBCS("LOUISIANA - BELLE CHASSE", PortCountries.US),
    USBOS("MASSACHUSETTS - BOSTON", PortCountries.US),
    USBPT("TEXAS - BEAUMONT", PortCountries.US),
    USBRO("Brownsville", PortCountries.US),
    USBTR("LOUISIANA - BATON ROUGE", PortCountries.US),
    USCEN("LOUISIANA - CONVENT", PortCountries.US),
    USCHI("ILLINOIS - CHICAGO", PortCountries.US),
    USCHS("SOUTH CAROLINA - CHARLESTON", PortCountries.US),
    USCLE("OHIO - CLEVELAND", PortCountries.US),
    USCRP("Corpus Christi", PortCountries.US),
    USCRW("WEST VIRGINIA - CHARLESTON", PortCountries.US),
    USCSF("NEW JERSEY - CARTERET", PortCountries.US),
    USDET("MICHIGAN - DETROIT", PortCountries.US),
    USDLH("MINNESOTA - DULUTH", PortCountries.US),
    USEFG("FLORIDA - EVERGLADES CITY", PortCountries.US),
    USEVT("Everett", PortCountries.US),
    USEWR("NEW JERSEY - NEWARK", PortCountries.US),
    USFAH("PENNSYLVANIA - FAIRLESS HILLS", PortCountries.US),
    USFPO("Freeport", PortCountries.US),
    USGLS("TEXAS - GALVESTON LIGHTERING ZONE", PortCountries.US),
    USGRY("LOUISIANA - GRAMERCY", PortCountries.US),
    USHOU("TEXAS - HOUSTON PILOT", PortCountries.US),
    USHPY("TEXAS - BAYTOWN", PortCountries.US),
    USHVN("CONNECTICUT - NEW HAVEN", PortCountries.US),
    USILG("DELAWARE - WILMINGTON", PortCountries.US),
    USILM("NORTH CAROLINA - WILMINGTON", PortCountries.US),
    USJAX("FLORIDA - JACKSONVILLE", PortCountries.US),
    USJEC("NEW JERSEY - JERSEY CITY", PortCountries.US),
    USLAX("LOS ANGELES", PortCountries.US),
    USLCH("LOUISIANA - LAKE CHARLES", PortCountries.US),
    USLDJ("NEW JERSEY - LINDEN", PortCountries.US),
    USLGB("Long Beach", PortCountries.US),
    USLOG("Longview", PortCountries.US),
    USMAH("PENNSYLVANIA - MARCUS HOOK", PortCountries.US),
    USMKE("WISCONSIN - MILWAUKEE", PortCountries.US),
    USMOB("ALABAMA - MOBILE", PortCountries.US),
    USMPP("TEXAS - MORGANS POINT", PortCountries.US),
    USMRH("NORTH CAROLINA - MOREHEAD CITY", PortCountries.US),
    USMSY("New Orleans", PortCountries.US),
    USNCM("LOUISIANA - NORCO", PortCountries.US),
    USNDX("Nederland,Texas", PortCountries.US),
    USNNS("VIRGINIA - NEWPORT NEWS", PortCountries.US),
    USNYC("New York", PortCountries.US),
    USOCP("Ocean Port", PortCountries.US),
    USORF("VIRGINIA - NORFOLK", PortCountries.US),
    USPAS("TEXAS - PASADENA", PortCountries.US),
    USPCV("Port Canaveral", PortCountries.US),
    USPEB("NEW JERSEY - PORT ELIZABETH", PortCountries.US),
    USPEF("FLORIDA - PORT EVERGLADES", PortCountries.US),
    USPHL("Philadelphia", PortCountries.US),
    USPLL("LOUISIANA - PORT ALLEN", PortCountries.US),
    USPLQ("LOUISIANA - PLAQUEMINE", PortCountries.US),
    USPME("Port Manatee", PortCountries.US),
    USPOA("TEXAS - PORT ARTHUR", PortCountries.US),
    USPOB("TEXAS - PORT BOLIVAR", PortCountries.US),
    USPON("TEXAS - PORT NECHES", PortCountries.US),
    USPVD("RHODE ISLAND - PROVIDENCE", PortCountries.US),
    USPWM("MAINE - PORTLAND", PortCountries.US),
    USQHH("NEW JERSEY - AMBROSE CHANNEL LIGHT", PortCountries.US),
    USRCH("CALIFORNIA - RICHMOND", PortCountries.US),
    USRHD("NEW YORK - RIVERHEAD", PortCountries.US),
    USSAC("Sacramento", PortCountries.US),
    USSAN("San Diego", PortCountries.US),
    USSAV("GEORGIA - SAVANNAH", PortCountries.US),
    USSFO("SAN FRANCISCO", PortCountries.US),
    USSNJ("LOUISIANA - SAINT JAMES", PortCountries.US),
    USSPQ("San Pedro", PortCountries.US),
    USSRE("LOUISIANA - SAINT ROSE", PortCountries.US),
    USSSI("GEORGIA - BRUNSWICK", PortCountries.US),
    USSUW("WISCONSIN - SUPERIOR", PortCountries.US),
    USTOL("OHIO - TOLEDO", PortCountries.US),
    USTPA("Tampa", PortCountries.US),
    USTXT("TEXAS - TEXAS CITY", PortCountries.US),
    USXMK("NORTH CAROLINA - SOUTHPORT", PortCountries.US),
    USZSC("LOUISIANA - St. Charles", PortCountries.US),
    VIHOC("St. Croix (HOVIC, Limetree Bay)", null),
    YTDZA("Dzaoudzi", null),
    YTKNG("Koungou", null),
    YTLON("Longoni", null),
    YTMAM("Mamoudzou", null),
    YTPAS("Passamainty", null);

    private final String name;
    private final PortCountries country;

    public static PortCodes2 fromString(String value) {
        for (PortCodes2 e : PortCodes2.values()) {
            if (e.name().equalsIgnoreCase(value)) {
                return e;
            }
        }
        return null;
    }
}
