package uk.gov.mrtm.api.reporting.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PortCodes1 {
    NOT_APPLICABLE("Not applicable", null),
    BE888("Andere", PortCountries.BE),
    BEAAB("Aalst", PortCountries.BE),
    BEAAL("Aalter", PortCountries.BE),
    BEABK("Albertkanaal ports", PortCountries.BE),
    BEADK("Adinkerke", PortCountries.BE),
    BEAEJ("Arendonk", PortCountries.BE),
    BEAFN("Afsnee", PortCountries.BE),
    BEAGT("Argenteau", PortCountries.BE),
    BEAHE("Antheit", PortCountries.BE),
    BEAMY("Amay", PortCountries.BE),
    BEANB("Angleur", PortCountries.BE),
    BEAND("Andenne", PortCountries.BE),
    BEANH("Anhée", PortCountries.BE),
    BEANL("Anderlecht/Brussel (Bruxelles)", PortCountries.BE),
    BEANR("Antwerpen", PortCountries.BE),
    BEAPL("Appels", PortCountries.BE),
    BEAPS("Ampsin", PortCountries.BE),
    BEAPT("Appelterre-Eichem", PortCountries.BE),
    BEASP("Asper", PortCountries.BE),
    BEASR("Anseremme", PortCountries.BE),
    BEAST("Astene", PortCountries.BE),
    BEATH("Ath", PortCountries.BE),
    BEATO("Antoing", PortCountries.BE),
    BEAVE("Annevoie", PortCountries.BE),
    BEAVG("Anvaing", PortCountries.BE),
    BEAVL("Avelgem", PortCountries.BE),
    BEAVS("Auvelais", PortCountries.BE),
    BEBAI("Baillonville", PortCountries.BE),
    BEBAN("Ben-Ahin", PortCountries.BE),
    BEBAT("Battel", PortCountries.BE),
    BEBAZ("Bazel", PortCountries.BE),
    BEBBG("Blankenberge", PortCountries.BE),
    BEBCM("Berchem", PortCountries.BE),
    BEBCR("Bellecourt", PortCountries.BE),
    BEBDU("Baudour", PortCountries.BE),
    BEBER("Beerse", PortCountries.BE),
    BEBEZ("Beez", PortCountries.BE),
    BEBGK("Balgerhoek", PortCountries.BE),
    BEBGN("Briegden", PortCountries.BE),
    BEBGS("Brugge (Bruges)", PortCountries.BE),
    BEBHE("Boekhoute", PortCountries.BE),
    BEBHR("Bléharies", PortCountries.BE),
    BEBHU("Buggenhout", PortCountries.BE),
    BEBLE("Balen", PortCountries.BE),
    BEBLO("Beloeil", PortCountries.BE),
    BEBLT("Blaton", PortCountries.BE),
    BEBLZ("Bilzen", PortCountries.BE),
    BEBMB("Boortmeerbeek", PortCountries.BE),
    BEBNU("Berneau", PortCountries.BE),
    BEBOA("Bas-Oha", PortCountries.BE),
    BEBOC("Bocholt", PortCountries.BE),
    BEBOM("Boom", PortCountries.BE),
    BEBON("Bornem", PortCountries.BE),
    BEBOO("Boorsem", PortCountries.BE),
    BEBRC("Brecht", PortCountries.BE),
    BEBRE("Bree", PortCountries.BE),
    BEBRM("Beernem", PortCountries.BE),
    BEBRT("Berendrecht", PortCountries.BE),
    BEBRU("Brussel (Bruxelles)", PortCountries.BE),
    BEBRY("Bruyelle", PortCountries.BE),
    BEBSE("Bissegem", PortCountries.BE),
    BEBSI("Labuissière", PortCountries.BE),
    BEBSR("Baasrode", PortCountries.BE),
    BEBSU("Bossuit", PortCountries.BE),
    BEBTX("Bertrix", PortCountries.BE),
    BEBUD("Burcht", PortCountries.BE),
    BEBVE("Bever", PortCountries.BE),
    BEBVM("Bouvignes-sur-Meuse", PortCountries.BE),
    BEBVO("Beverlo", PortCountries.BE),
    BEBWN("Warneton", PortCountries.BE),
    BECBQ("Clabecq", PortCountries.BE),
    BECCS("Courcelles", PortCountries.BE),
    BECHA("Châtelet", PortCountries.BE),
    BECHE("Chênée", PortCountries.BE),
    BECHI("Chièvres", PortCountries.BE),
    BECLN("Calonne", PortCountries.BE),
    BECOM("Comines", PortCountries.BE),
    BECOU("Couillet", PortCountries.BE),
    BECRA("Cheratte", PortCountries.BE),
    BECRL("Charleroi", PortCountries.BE),
    BECRQ("Chercq", PortCountries.BE),
    BECTA("Chertal", PortCountries.BE),
    BECTL("Châtelineau", PortCountries.BE),
    BEDDR("Dendermonde", PortCountries.BE),
    BEDEG("Deurne", PortCountries.BE),
    BEDEL("Doel", PortCountries.BE),
    BEDEZ("Deinze", PortCountries.BE),
    BEDGN("Drongen", PortCountries.BE),
    BEDIA("Dinant", PortCountries.BE),
    BEDIK("Diksmuide", PortCountries.BE),
    BEDKN("Daknam", PortCountries.BE),
    BEDLS("Dilsen", PortCountries.BE),
    BEDNB("Denderbelle", PortCountries.BE),
    BEDPE("De Pinte", PortCountries.BE),
    BEDPK("Diepenbeek", PortCountries.BE),
    BEDPY("Dampremy", PortCountries.BE),
    BEDRW("Denderleeuw", PortCountries.BE),
    BEDSE("Dessel", PortCountries.BE),
    BEDSL("Desselgem", PortCountries.BE),
    BEDUF("Duffel", PortCountries.BE),
    BEDXN("Deux-Acren", PortCountries.BE),
    BEEAM("Ename", PortCountries.BE),
    BEEBM("Emblem", PortCountries.BE),
    BEEBZ("Eigenbilzen", PortCountries.BE),
    BEECH("Mechelen", PortCountries.BE),
    BEEEK("Eeklo", PortCountries.BE),
    BEEET("Éthe", PortCountries.BE),
    BEEFS("Escanaffles", PortCountries.BE),
    BEEHT("Eindhout", PortCountries.BE),
    BEEIN("Eine", PortCountries.BE),
    BEEKE("Ekeren", PortCountries.BE),
    BEEKS("Eksaarde", PortCountries.BE),
    BEELA("Écaussinnes-Lalaing", PortCountries.BE),
    BEELS("Melsen", PortCountries.BE),
    BEEMP("Estaimpuis", PortCountries.BE),
    BEENG("Engis", PortCountries.BE),
    BEEQE("Eke", PortCountries.BE),
    BEEQM("Esquelmes", PortCountries.BE),
    BEERE("Ertvelde", PortCountries.BE),
    BEESD("Eisden", PortCountries.BE),
    BEEVM("Evergem", PortCountries.BE),
    BEFCS("Farciennes", PortCountries.BE),
    BEFEY("Feluy", PortCountries.BE),
    BEFFX("Floriffoux", PortCountries.BE),
    BEFLN("Flône", PortCountries.BE),
    BEFLO("Floreffe", PortCountries.BE),
    BEFMA("Flémalle", PortCountries.BE),
    BEFNR("Franière", PortCountries.BE),
    BEFRM("Fortem", PortCountries.BE),
    BEFVT("Fontaine-Valmont", PortCountries.BE),
    BEFWI("Flawinne", PortCountries.BE),
    BEGBB("Grobbendonk", PortCountries.BE),
    BEGBH("Genenbos", PortCountries.BE),
    BEGBU("Gentbrugge", PortCountries.BE),
    BEGDE("Godsheide", PortCountries.BE),
    BEGDN("Godinne", PortCountries.BE),
    BEGEA("Geraardsbergen", PortCountries.BE),
    BEGEL("Geel", PortCountries.BE),
    BEGGM("Grembergen", PortCountries.BE),
    BEGHI("Saint-Ghislain", PortCountries.BE),
    BEGHL("Ghlin", PortCountries.BE),
    BEGIS("Gistel", PortCountries.BE),
    BEGLK("Gellik", PortCountries.BE),
    BEGNE("Gent", PortCountries.BE),
    BEGNK("Genk", PortCountries.BE),
    BEGOS("Gosselies", PortCountries.BE),
    BEGRB("Grimbergen", PortCountries.BE),
    BEGRO("Groot Bijgaarden", PortCountries.BE),
    BEGVR("Gavere", PortCountries.BE),
    BEGZE("Gozée", PortCountries.BE),
    BEHAM("Hamsehoeven", PortCountries.BE),
    BEHAR("Haren", PortCountries.BE),
    BEHBE("Hansbeke", PortCountries.BE),
    BEHBN("Hoboken", PortCountries.BE),
    BEHCS("Harchies", PortCountries.BE),
    BEHCT("Haccourt", PortCountries.BE),
    BEHDK("Heindonk", PortCountries.BE),
    BEHEE("Heer", PortCountries.BE),
    BEHEJ("Harelbeke", PortCountries.BE),
    BEHER("Herentals", PortCountries.BE),
    BEHET("Herent", PortCountries.BE),
    BEHEX("Hemiksem", PortCountries.BE),
    BEHFB("Halle", PortCountries.BE),
    BEHGA("Houdeng-Aimeries", PortCountries.BE),
    BEHGG("Houdeng-Goegnies", PortCountries.BE),
    BEHKN("Helkijn", PortCountries.BE),
    BEHLU("Halluin", PortCountries.BE),
    BEHMB("Ham-sur-Sambre", PortCountries.BE),
    BEHMH("Hermalle-sous-Huy", PortCountries.BE),
    BEHMM("Hamme", PortCountries.BE),
    BEHNA("Handzame", PortCountries.BE),
    BEHNS("Hensies", PortCountries.BE),
    BEHOL("Hollain", PortCountries.BE),
    BEHPD("Hastière-par-delà", PortCountries.BE),
    BEHRE("Havré", PortCountries.BE),
    BEHRP("Hourpes", PortCountries.BE),
    BEHRS("Herstal", PortCountries.BE),
    BEHSD("Hofstade", PortCountries.BE),
    BEHSL("Sint-Huibrechts-Lille", PortCountries.BE),
    BEHSS("Hasselt", PortCountries.BE),
    BEHTJ("Hautrage", PortCountries.BE),
    BEHTM("Hermeton-sur-Meuse", PortCountries.BE),
    BEHUM("Humbeek", PortCountries.BE),
    BEHUX("Houx", PortCountries.BE),
    BEHUY("Huy", PortCountries.BE),
    BEHVE("Hever", PortCountries.BE),
    BEHYB("Herdersem", PortCountries.BE),
    BEHZO("Heusden-Zolder", PortCountries.BE),
    BEIAI("Denderhoutem", PortCountries.BE),
    BEIDG("Idegem", PortCountries.BE),
    BEIGE("Ingelmunster", PortCountries.BE),
    BEIPR("Ieper", PortCountries.BE),
    BEISR("Isières", PortCountries.BE),
    BEITR("Itter (Ittre)", PortCountries.BE),
    BEIZG("Izegem", PortCountries.BE),
    BEJAK("Jupille-sur-Meuse", PortCountries.BE),
    BEJAM("Jambes", PortCountries.BE),
    BEJAV("Java", PortCountries.BE),
    BEJBE("Jabbeke", PortCountries.BE),
    BEJKP("Sint-Jacobs-Kapelle", PortCountries.BE),
    BEJPS("Jemeppe-sur-Sambre", PortCountries.BE),
    BEKAI("Kain", PortCountries.BE),
    BEKAN("Canne (Kanne)", PortCountries.BE),
    BEKCT("Kachtem", PortCountries.BE),
    BEKDE("Kieldrecht", PortCountries.BE),
    BEKEK("Kruibeke", PortCountries.BE),
    BEKHN("Kerkhove", PortCountries.BE),
    BEKJK("Kortrijk", PortCountries.BE),
    BEKLE("Kaulille", PortCountries.BE),
    BEKMH("Kampenhout", PortCountries.BE),
    BEKNS("Knesselaere", PortCountries.BE),
    BEKOU("Kallo", PortCountries.BE),
    BEKPB("Kapelle-op-den-Bos", PortCountries.BE),
    BEKRN("Kuringen", PortCountries.BE),
    BEKRO("Kinrooi", PortCountries.BE),
    BEKSN("Kessenich", PortCountries.BE),
    BEKSR("Kluisbergen", PortCountries.BE),
    BEKUU("Kuurne", PortCountries.BE),
    BEKVE("Klein Veerle", PortCountries.BE),
    BEKWA("Kwaadmechelen", PortCountries.BE),
    BEKWB("Klein Willebroek", PortCountries.BE),
    BELAN("Limburg", PortCountries.BE),
    BELAW("Lauwe", PortCountries.BE),
    BELBE("Lembeek", PortCountries.BE),
    BELBS("Lobbes", PortCountries.BE),
    BELDA("Laakdal", PortCountries.BE),
    BELDS("Charleroi", PortCountries.BE),
    BELES("Lessines", PortCountries.BE),
    BELEU("Leuven", PortCountries.BE),
    BELFE("Leffinge", PortCountries.BE),
    BELGB("Langerbrugge", PortCountries.BE),
    BELGG("Luik", PortCountries.BE),
    BELGM("Landegem", PortCountries.BE),
    BELGO("Langerlo", PortCountries.BE),
    BELHK("Liefkenshoek", PortCountries.BE),
    BELIE("Lier", PortCountries.BE),
    BELIL("Lillo", PortCountries.BE),
    BELIX("Lixhe", PortCountries.BE),
    BELLO("La Louvière", PortCountries.BE),
    BELML("Lommel", PortCountries.BE),
    BELNK("Lanklaar", PortCountries.BE),
    BELNY("Lanaye (Ternaaien)", PortCountries.BE),
    BELOK("Lokeren", PortCountries.BE),
    BELOT("Lot", PortCountries.BE),
    BELOZ("Lozen", PortCountries.BE),
    BELPG("Leopoldsburg", PortCountries.BE),
    BELPI("Laplaigne", PortCountries.BE),
    BELQA("Lanquesaint", PortCountries.BE),
    BELRG("Ledeberg", PortCountries.BE),
    BELSG("Lissewege", PortCountries.BE),
    BELUI("Lustin", PortCountries.BE),
    BELUM("Lummen", PortCountries.BE),
    BELUZ("Ladeuze", PortCountries.BE),
    BELVO("Lovendegem", PortCountries.BE),
    BEMAN("Manage", PortCountries.BE),
    BEMAP("Marchienne-au-Pont", PortCountries.BE),
    BEMBY("Maubray", PortCountries.BE),
    BEMCA("Merbes-le-Château", PortCountries.BE),
    BEMCN("Machelen", PortCountries.BE),
    BEMEE("Meer", PortCountries.BE),
    BEMEG("Meilegem", PortCountries.BE),
    BEMEH("Meerhout", PortCountries.BE),
    BEMEL("Melle", PortCountries.BE),
    BEMEN("Menen", PortCountries.BE),
    BEMEW("Moerbeke-Waas", PortCountries.BE),
    BEMFF("Maffle", PortCountries.BE),
    BEMGM("Meigem", PortCountries.BE),
    BEMGN("Moignelée", PortCountries.BE),
    BEMGS("Montignies-sur-Sambre", PortCountries.BE),
    BEMHN("Massenhoven", PortCountries.BE),
    BEMLD("Marche-les-Dames", PortCountries.BE),
    BEMLO("Mol", PortCountries.BE),
    BEMLY("Marly", PortCountries.BE),
    BEMMN("Maasmechelen", PortCountries.BE),
    BEMNO("Moen", PortCountries.BE),
    BEMQS("Mons", PortCountries.BE),
    BEMRB("Moerbrugge", PortCountries.BE),
    BEMRD("Merendree", PortCountries.BE),
    BEMRG("Maurage", PortCountries.BE),
    BEMRI("Mariakerke", PortCountries.BE),
    BEMRK("Merksem", PortCountries.BE),
    BEMRL("Merelbeke", PortCountries.BE),
    BEMRM("Merkem", PortCountries.BE),
    BEMRO("Mornimont", PortCountries.BE),
    BEMSI("Monsin", PortCountries.BE),
    BEMSJ("Molenbeek-Saint-Jean (Sint-Jans-Molenbeek)/Brussel (Bruxelles)", PortCountries.BE),
    BEMSK("Maaseik", PortCountries.BE),
    BEMSP("Mespelare", PortCountries.BE),
    BEMSR("Maisières", PortCountries.BE),
    BEMSS("Monceau-sur-Sambre", PortCountries.BE),
    BEMUI("Muizen", PortCountries.BE),
    BEMZK("Moerzeke", PortCountries.BE),
    BENAM("Namen", PortCountries.BE),
    BENBA("Nimy", PortCountries.BE),
    BENFE("Neffe", PortCountries.BE),
    BENHA("Neerharen", PortCountries.BE),
    BENHY("Neuville-sous-Huy", PortCountries.BE),
    BENIE("Nieuwpoort", PortCountries.BE),
    BENIL("Niel", PortCountries.BE),
    BENMC("Namêche", PortCountries.BE),
    BENNV("Ninove", PortCountries.BE),
    BENRP("Neerpelt", PortCountries.BE),
    BENRT("Neeroeteren", PortCountries.BE),
    BENRY("Renory", PortCountries.BE),
    BENVH("Brussel", PortCountries.BE),
    BENVL("Nevele", PortCountries.BE),
    BENVN("Noeveren", PortCountries.BE),
    BENYL("Nijlen", PortCountries.BE),
    BEOBG("Oudenburg", PortCountries.BE),
    BEOBR("Obourg", PortCountries.BE),
    BEOBT("Ombret-Rawsa", PortCountries.BE),
    BEODE("Auderghem (Oudergem)/Brussel (Bruxelles)", PortCountries.BE),
    BEOEL("Oelegem", PortCountries.BE),
    BEOEV("Oevel", PortCountries.BE),
    BEOGS("Ollignies", PortCountries.BE),
    BEOHN("Ophoven", PortCountries.BE),
    BEOKG("Okegem", PortCountries.BE),
    BEOKP("Oostkamp", PortCountries.BE),
    BEOLE("Overboelare", PortCountries.BE),
    BEOLN("Olen", PortCountries.BE),
    BEOOG("Ooigem", PortCountries.BE),
    BEOPI("Opitter", PortCountries.BE),
    BEOPY("Oupeye", PortCountries.BE),
    BEOQC("Oisquercq", PortCountries.BE),
    BEORR("Orroir", PortCountries.BE),
    BEOSG("Oeselgem", PortCountries.BE),
    BEOSH("Oostham", PortCountries.BE),
    BEOST("Oostende", PortCountries.BE),
    BEOTH("Oud-Turnhout", PortCountries.BE),
    BEOTK("Oostkerke", PortCountries.BE),
    BEOTL("Oosterlo", PortCountries.BE),
    BEOUD("Oudenaarde", PortCountries.BE),
    BEOUG("Ougrée", PortCountries.BE),
    BEOVE("Overpelt", PortCountries.BE),
    BEOZL("Onkerzele", PortCountries.BE),
    BEPAL("Paal", PortCountries.BE),
    BEPCL("Pont-à-Celles", PortCountries.BE),
    BEPCQ("Pecq", PortCountries.BE),
    BEPES("Péronnes", PortCountries.BE),
    BEPFE("Profondeville", PortCountries.BE),
    BEPKH("Pollinkhove", PortCountries.BE),
    BEPLB("Péronnes/Binche", PortCountries.BE),
    BEPLO("Pont-de-Loup", PortCountries.BE),
    BEPLY("Petit-Lanaye", PortCountries.BE),
    BEPME("Pommeroeul", PortCountries.BE),
    BEPML("Pamel", PortCountries.BE),
    BEPTP("Pijp Tabak", PortCountries.BE),
    BEPTS("Pottes", PortCountries.BE),
    BEPUU("Puurs", PortCountries.BE),
    BEPWZ("Péruwelz", PortCountries.BE),
    BERAR("La Roche-en-Ardenne", PortCountries.BE),
    BERAS("Ranst", PortCountries.BE),
    BERBE("Roesbrugge", PortCountries.BE),
    BERBX("Rebaix", PortCountries.BE),
    BERCI("Ramegnies-Chin", PortCountries.BE),
    BERCL("Richelle", PortCountries.BE),
    BERCT("Roucourt", PortCountries.BE),
    BEREK("Rekkem", PortCountries.BE),
    BEREQ("Erquelinnes", PortCountries.BE),
    BERGE("Reninge", PortCountries.BE),
    BERHA("Roesbrugge-Haringe", PortCountries.BE),
    BERIE("Rieme", PortCountries.BE),
    BERIJ("Rijkevorsel", PortCountries.BE),
    BERIN("Beringen", PortCountries.BE),
    BERIS("Riemst", PortCountries.BE),
    BERJT("Rocourt", PortCountries.BE),
    BEROE("Roeselare", PortCountries.BE),
    BEROS("Roselies", PortCountries.BE),
    BEROU("Le Roeulx", PortCountries.BE),
    BEROX("Roux", PortCountries.BE),
    BERPM("Rupelmonde", PortCountries.BE),
    BERQS("Ronquières", PortCountries.BE),
    BERTI("Retie", PortCountries.BE),
    BERUE("Ruien", PortCountries.BE),
    BERUI("Ruisbroek", PortCountries.BE),
    BERUS("Rumst", PortCountries.BE),
    BERVE("Rivière", PortCountries.BE),
    BERVS("Ravels", PortCountries.BE),
    BESAN("Sint-Andries", PortCountries.BE),
    BESAS("Sint-Amands", PortCountries.BE),
    BESBE("Steenbrugge", PortCountries.BE),
    BESBG("Stambruges", PortCountries.BE),
    BESCE("Schilde", PortCountries.BE),
    BESCT("Schoten", PortCountries.BE),
    BESDP("Steendorp", PortCountries.BE),
    BESDT("Soudromont", PortCountries.BE),
    BESEN("Seneffe", PortCountries.BE),
    BESES("Seilles", PortCountries.BE),
    BESEV("Sint-Eloois-Vijve", PortCountries.BE),
    BESGM("Stasegem", PortCountries.BE),
    BESGS("Saint-Georges", PortCountries.BE),
    BESGX("Sclaigneaux", PortCountries.BE),
    BESHB("Schellebelle", PortCountries.BE),
    BESHL("Schelle", PortCountries.BE),
    BESHR("Schelderode", PortCountries.BE),
    BESJG("Sint-Job-in-'t-Goor", PortCountries.BE),
    BESJO("Sint-Jozef-Olen", PortCountries.BE),
    BESJR("Sint-Joris", PortCountries.BE),
    BESKA("Sint Katelijne Waver", PortCountries.BE),
    BESKE("Steenkerke", PortCountries.BE),
    BESKR("Stokrooie", PortCountries.BE),
    BESLJ("Sas-Slijkens", PortCountries.BE),
    BESLN("Sint-Lenaarts", PortCountries.BE),
    BESLS("Salles", PortCountries.BE),
    BESLY("Sclayn", PortCountries.BE),
    BESML("Sint-Martens-Latem", PortCountries.BE),
    BESNE("Schoonaarde", PortCountries.BE),
    BESPE("Scheepsdale", PortCountries.BE),
    BESPI("Espierres (Spiere)", PortCountries.BE),
    BESPT("Sint-Pieters-Leeuw", PortCountries.BE),
    BESSB("Solre-sur-Sambre", PortCountries.BE),
    BESSK("Snaaskerke", PortCountries.BE),
    BESSN("Sclessin", PortCountries.BE),
    BESSO("Samson", PortCountries.BE),
    BESTB("Strépy-Bracquegnies", PortCountries.BE),
    BESTT("Statte", PortCountries.BE),
    BESTV("Sint-Baafs-Vijve", PortCountries.BE),
    BESVG("Ruisbroek", PortCountries.BE),
    BESVN("Stevensvennen", PortCountries.BE),
    BETBE("Tournebride", PortCountries.BE),
    BETDK("Terdonk", PortCountries.BE),
    BETER("Ternat", PortCountries.BE),
    BETES("Tessenderlo", PortCountries.BE),
    BETET("Tertre", PortCountries.BE),
    BETFN("Teralfene", PortCountries.BE),
    BETGE("Tergnée", PortCountries.BE),
    BETGL("Tongerlo", PortCountries.BE),
    BETGN("Terhagen", PortCountries.BE),
    BETHE("Thieu", PortCountries.BE),
    BETHG("Tihange", PortCountries.BE),
    BETHU("Thuin", PortCountries.BE),
    BETIL("Tielrode", PortCountries.BE),
    BETIS("Tisselt", PortCountries.BE),
    BETLK("Tildonk", PortCountries.BE),
    BETLR("Tilleur", PortCountries.BE),
    BETMS("Tamines", PortCountries.BE),
    BETRG("Thorembais-les-Beguines", PortCountries.BE),
    BETRN("Doornik (Tournai)", PortCountries.BE),
    BETSE("Temse", PortCountries.BE),
    BETSL("Tourinnes-St-Lambert", PortCountries.BE),
    BETTJ("Heultje", PortCountries.BE),
    BETUR("Turnhout", PortCountries.BE),
    BEUIT("Uitbergen", PortCountries.BE),
    BEVBG("Verbrande Brug", PortCountries.BE),
    BEVEU("Veurne", PortCountries.BE),
    BEVGL("Virginal-Samme", PortCountries.BE),
    BEVHN("Vroenhoven", PortCountries.BE),
    BEVIL("Vilvoorde", PortCountries.BE),
    BEVIS("Visé", PortCountries.BE),
    BEVIT("Sankt Vith", PortCountries.BE),
    BEVLX("Vaulx", PortCountries.BE),
    BEVSB("Val Saint-Lambert", PortCountries.BE),
    BEVSH("Ville-sur-Haine", PortCountries.BE),
    BEVSL("Viersel", PortCountries.BE),
    BEVVI("Viesville", PortCountries.BE),
    BEVWZ("Veldwezelt", PortCountries.BE),
    BEVZI("Vezin", PortCountries.BE),
    BEWAA("Waasmunster", PortCountries.BE),
    BEWAH("Hoves", PortCountries.BE),
    BEWAN("Wanze", PortCountries.BE),
    BEWAR("Waregem", PortCountries.BE),
    BEWBR("Maransart", PortCountries.BE),
    BEWCG("Warcoing", PortCountries.BE),
    BEWDG("Wondelgem", PortCountries.BE),
    BEWDM("Waardamme", PortCountries.BE),
    BEWEE("Wingene", PortCountries.BE),
    BEWEL("Wellen", PortCountries.BE),
    BEWER("Wervik", PortCountries.BE),
    BEWES("Westerlo", PortCountries.BE),
    BEWET("Wetteren", PortCountries.BE),
    BEWEV("Wevelgem", PortCountries.BE),
    BEWGL("Wijgmaal", PortCountries.BE),
    BEWIH("Wichelen", PortCountries.BE),
    BEWIP("Wépion", PortCountries.BE),
    BEWIR("Wiers", PortCountries.BE),
    BEWJG("Wijnegem", PortCountries.BE),
    BEWLB("Willebroek", PortCountries.BE),
    BEWLM("Walem", PortCountries.BE),
    BEWLP("Wulpen", PortCountries.BE),
    BEWLT("Waulsort", PortCountries.BE),
    BEWND("Wandre", PortCountries.BE),
    BEWSL("Wilsele", PortCountries.BE),
    BEWTH("Wintham", PortCountries.BE),
    BEXXX("RIS Inland waterways", PortCountries.BE),
    BEYRT("Ivoz-Ramet", PortCountries.BE),
    BEYVO("Yvoir", PortCountries.BE),
    BEZAN("Zandhoven", PortCountries.BE),
    BEZBR("Zandbergen", PortCountries.BE),
    BEZEE("Zeebrugge", PortCountries.BE),
    BEZEL("Zelzate", PortCountries.BE),
    BEZER("Seraing", PortCountries.BE),
    BEZET("Zemst", PortCountries.BE),
    BEZGM("Zingem", PortCountries.BE),
    BEZLE("Zele", PortCountries.BE),
    BEZOD("Zolder", PortCountries.BE),
    BEZRM("Zomergem", PortCountries.BE),
    BEZTL("Zutendaal", PortCountries.BE),
    BEZUL("Zulte", PortCountries.BE),
    BEZUN("Zuen (Zuun)", PortCountries.BE),
    BEZVD("Zandvoorde", PortCountries.BE),
    BEZVT("Zandvliet", PortCountries.BE),
    BEZWE("Zwevegem", PortCountries.BE),
    BEZWL("Zwijndrecht", PortCountries.BE),
    BEZWN("Zwijnaarde", PortCountries.BE),
    BGBAL("Balchik", PortCountries.BG),
    BGBOJ("Burgas", PortCountries.BG),
    BGNES("Nessebar", PortCountries.BG),
    BGVAR("Varna", PortCountries.BG),
    BGVAZ("Varna-Zapad", PortCountries.BG),
    BMBDA("Hamilton (Bermuda)", PortCountries.BM),
    BQEUX("Sint Eustatius", null),
    CAACO("Aulds Cove", PortCountries.CA),
    CABAD("Baddeck", PortCountries.CA),
    CABAS("Bayside", PortCountries.CA),
    CABAT("Bathurst", PortCountries.CA),
    CABAY("Bayside (St Roberts)", PortCountries.CA),
    CABBU("Bay Bulls", PortCountries.CA),
    CABCO("Baie Comeau", PortCountries.CA),
    CABEC("Becancour", PortCountries.CA),
    CABEL("Belledune", PortCountries.CA),
    CABIN("Burrard Inlet", PortCountries.CA),
    CABST("Bayside (Charlotte)", PortCountries.CA),
    CABUA("Bull Arm", PortCountries.CA),
    CABWD("Botwood", PortCountries.CA),
    CABYR("Bay Roberts", PortCountries.CA),
    CACAM("Campbell River", PortCountries.CA),
    CACBC("Come by Chance", PortCountries.CA),
    CACBK("Corner Brooke", PortCountries.CA),
    CACCB("Cowichan Bay", PortCountries.CA),
    CACDN("Cardinal", PortCountries.CA),
    CACHA("Charlottetown", PortCountries.CA),
    CACHM("Chemainus", PortCountries.CA),
    CACHR("Chandler", PortCountries.CA),
    CACHT("Cheticamp", PortCountries.CA),
    CACHV("Churchill", PortCountries.CA),
    CACLE("Clarenville", PortCountries.CA),
    CACLT("Carleton", PortCountries.CA),
    CACMS("Cap-aux-Meules", PortCountries.CA),
    CACOC("Contrecoeur", PortCountries.CA),
    CACPT("Canaport", PortCountries.CA),
    CACRO("Crofton", PortCountries.CA),
    CACSC("Cote Ste-Catherine", PortCountries.CA),
    CACSN("Clarkson", PortCountries.CA),
    CACWH("Cow Head", PortCountries.CA),
    CACWL("Cornwall", PortCountries.CA),
    CADAR("Dartmouth", PortCountries.CA),
    CADEB("Deception Bay", PortCountries.CA),
    CADEL("Delta Port", PortCountries.CA),
    CADHS("Dalhousie", PortCountries.CA),
    CADIG("Digby", PortCountries.CA),
    CADLN("Dublin", PortCountries.CA),
    CAEBY("English Bay", PortCountries.CA),
    CAEDC("Edwards Cove", PortCountries.CA),
    CAESQ("Esquimalt", PortCountries.CA),
    CAFOR("Fortune", PortCountries.CA),
    CAFSD("Fraser-Surrey Docks", PortCountries.CA),
    CAFWS("Fraser Wharves", PortCountries.CA),
    CAGAE("Grande-Anse", PortCountries.CA),
    CAGCA("Gros-Cacouna", PortCountries.CA),
    CAGEO("Georgetown, PE", PortCountries.CA),
    CAGGW("Georgetown", PortCountries.CA),
    CAGMA("Grand Manan, NB", PortCountries.CA),
    CAGOH("Goderich", PortCountries.CA),
    CAGOO("Goose Bay", PortCountries.CA),
    CAGPE("Gaspe", PortCountries.CA),
    CAHAL("Halifax", PortCountries.CA),
    CAHAM("Hamilton", PortCountries.CA),
    CAHLI("Herschel Island", PortCountries.CA),
    CAHOD("Holyrood", PortCountries.CA),
    CAHPT("Hantsport", PortCountries.CA),
    CAHRE("Harbour Grace", PortCountries.CA),
    CAHSP("Harve-St.Pierre", PortCountries.CA),
    CAIAM("Indian Arm", PortCountries.CA),
    CAIQL("Iqaluit", PortCountries.CA),
    CAKIN("Kingston", PortCountries.CA),
    CAKTM("Kitimat", PortCountries.CA),
    CALCV("Lower Cove", PortCountries.CA),
    CALIN("Little Narrows", PortCountries.CA),
    CALIV("Liverpool (CA)", PortCountries.CA),
    CALOH("Long Harbour", PortCountries.CA),
    CALOP("Long Pond", PortCountries.CA),
    CALOU("Louisbourg", PortCountries.CA),
    CALUN("Lunenburg", PortCountries.CA),
    CALWP("Lewisporte", PortCountries.CA),
    CAMAR("Marathon", PortCountries.CA),
    CAMHN("Les Mechins", PortCountries.CA),
    CAMIR("Miramichi", PortCountries.CA),
    CAMIS("Mississauga", PortCountries.CA),
    CAMNE("Matane", PortCountries.CA),
    CAMNI("Milne Inlet", PortCountries.CA),
    CAMTN("Marystown", PortCountries.CA),
    CAMTR("Montreal", PortCountries.CA),
    CAMUL("Mulgrave", PortCountries.CA),
    CANAI("Nain", PortCountries.CA),
    CANAN("Nanticoke", PortCountries.CA),
    CANNO("Nanaimo", PortCountries.CA),
    CANVK("Nansivik", PortCountries.CA),
    CANWP("Argentia", PortCountries.CA),
    CAOSH("Oshawa", PortCountries.CA),
    CAOWS("Owen Sound", PortCountries.CA),
    CAPAB("Port Alberni", PortCountries.CA),
    CAPAF("Port Alfred - La Baie", PortCountries.CA),
    CAPCA("Port-Cartier", PortCountries.CA),
    CAPCO("Port Colborne, ON", PortCountries.CA),
    CAPDI("Pond Inlet", PortCountries.CA),
    CAPHW("Port Hawkesbury", PortCountries.CA),
    CAPMA("Port McNeill", PortCountries.CA),
    CAPMO("Port Moody", PortCountries.CA),
    CAPNO("Pointe Noire", PortCountries.CA),
    CAPNT("Pangnirtung", PortCountries.CA),
    CAPOP("Pointe-au-Pic", PortCountries.CA),
    CAPRE("Prescott", PortCountries.CA),
    CAPRR("Prince Rupert", PortCountries.CA),
    CAPTO("Pictou", PortCountries.CA),
    CAPTU("Pt Tupper", PortCountries.CA),
    CAPWE("PORT WELLER", PortCountries.CA),
    CAQUE("Quebec City", PortCountries.CA),
    CAREB("Resolute Bay", PortCountries.CA),
    CAREL("Relance", PortCountries.CA),
    CARIM("Rimouski", PortCountries.CA),
    CARIT("Rankin Inlet", PortCountries.CA),
    CARTB("Robert's Bank", PortCountries.CA),
    CASAG("Saguenay", PortCountries.CA),
    CASBH("Sandy Beach", PortCountries.CA),
    CASBU("Shelburne", PortCountries.CA),
    CASCA("St Catharines, ON", PortCountries.CA),
    CASEB("Seven Islands Bay", PortCountries.CA),
    CASEI("Sept-Iles", PortCountries.CA),
    CASHH("Sheet Harbour", PortCountries.CA),
    CASJB("Saint John", PortCountries.CA),
    CASJF("St. John's", PortCountries.CA),
    CASLB("Shelburne", PortCountries.CA),
    CASMT("Stormont", PortCountries.CA),
    CASNI("Sarnia", PortCountries.CA),
    CASOR("Sorel", PortCountries.CA),
    CASOU("Souris", PortCountries.CA),
    CASPD("Springdale", PortCountries.CA),
    CASSM("Sault Ste. Marie", PortCountries.CA),
    CASTV("Stephenville", PortCountries.CA),
    CASTW("Stewart", PortCountries.CA),
    CASUM("Summerside", PortCountries.CA),
    CASYD("Sydney", PortCountries.CA),
    CATHU("Thunder Bay", PortCountries.CA),
    CATOR("Toronto", PortCountries.CA),
    CATRR("Trois Rivieres", PortCountries.CA),
    CATUK("Tutoyaktuk", PortCountries.CA),
    CAVAN("Vancouver", PortCountries.CA),
    CAVIC("Victoria", PortCountries.CA),
    CAVLF("Valleyfield", PortCountries.CA),
    CAVOB("Voisey's Bay", PortCountries.CA),
    CAWEL("Welland Canal", PortCountries.CA),
    CAWEY("Weymouth (CA)", PortCountries.CA),
    CAWHH("Whiffen Head", PortCountries.CA),
    CAWND("Windsor", PortCountries.CA),
    CAYCB("Cambridge Bay", PortCountries.CA),
    CAYEV("Inuvik", PortCountries.CA),
    CAYMH("Mary's Harbour", PortCountries.CA),
    CAYRF("Cartwright", PortCountries.CA),
    CAYRH("Yarmouth (CA)", PortCountries.CA),
    CUHAV("LA HABANA", PortCountries.CU),
    CUQMA("Matanzas", PortCountries.CU),
    CYAKT("Akrotiri", PortCountries.CY),
    CYDHK("Dhekelia", PortCountries.CY),
    CYLCA("Larnaca", PortCountries.CY),
    CYLMS("Limassol", PortCountries.CY),
    CYMOI("Moni", PortCountries.CY),
    CYVAS("Vasiliko", PortCountries.CY),
    CYVTE("VTT Vasiliko", PortCountries.CY),
    CYZYY("ZYYI", PortCountries.CY),
    DEAHC("Ahlbeck", PortCountries.DE),
    DEANK("Anklam", PortCountries.DE),
    DEBBH("Barth", PortCountries.DE),
    DEBEN("Bensersiel", PortCountries.DE),
    DEBKE("Brake", PortCountries.DE),
    DEBMK("Borkum", PortCountries.DE),
    DEBRB("Brunsbuttel", PortCountries.DE),
    DEBRE("Bremen", PortCountries.DE),
    DEBRV("Bremerhaven", PortCountries.DE),
    DEBSK("Burgstaaken", PortCountries.DE),
    DEBUM("Busum", PortCountries.DE),
    DEBUZ("Butzfleth", PortCountries.DE),
    DEBZR("Binz", PortCountries.DE),
    DECUX("Cuxhaven", PortCountries.DE),
    DEDAG("Dagebuell", PortCountries.DE),
    DEDUI("Duisburg", PortCountries.DE),
    DEECK("Eckernforde", PortCountries.DE),
    DEELS("Elsfleth", PortCountries.DE),
    DEEME("Emden", PortCountries.DE),
    DEFLF("Flensburg", PortCountries.DE),
    DEGLU("Gluckstadt", PortCountries.DE),
    DEGRD("Greifswald", PortCountries.DE),
    DEHAM("Hamburg", PortCountries.DE),
    DEHBU("Harburg", PortCountries.DE),
    DEHGL("Helgoland", PortCountries.DE),
    DEHHF("Heiligenhafen", PortCountries.DE),
    DEHOO("Hooksiel", PortCountries.DE),
    DEHRM("Hoernum", PortCountries.DE),
    DEHTU("Holtenau", PortCountries.DE),
    DEHUS("Husum (Germany)", PortCountries.DE),
    DEIAM("Amrum", PortCountries.DE),
    DEKAP("Kappeln", PortCountries.DE),
    DEKEL("Kiel", PortCountries.DE),
    DEKRE("Krefeld", PortCountries.DE),
    DELBC("Lubeck", PortCountries.DE),
    DELBI("Lubmin", PortCountries.DE),
    DELEE("Leer", PortCountries.DE),
    DELEW("Lemwerder", PortCountries.DE),
    DELGO("Langeoog", PortCountries.DE),
    DELIS("List", PortCountries.DE),
    DEMOZ("Motzen", PortCountries.DE),
    DEMUK("Mukran", PortCountries.DE),
    DENES("Nessmersiel", PortCountries.DE),
    DENGL("Neustadt", PortCountries.DE),
    DENHA("Nordenham", PortCountries.DE),
    DENHO("Neustadt Holstein", PortCountries.DE),
    DENOE("Norddeich", PortCountries.DE),
    DENRD("Norderney", PortCountries.DE),
    DEOLO("Oldenburg", PortCountries.DE),
    DEPAP("Papenburg", PortCountries.DE),
    DEPEF("Peenem&uuml;nde", PortCountries.DE),
    DEPEL("Pellworm", PortCountries.DE),
    DEPUT("Puttgarden", PortCountries.DE),
    DEREN("Rendsburg", PortCountries.DE),
    DERSK("Rostock", PortCountries.DE),
    DESAS("Sassnitz", PortCountries.DE),
    DESLS("Schleswig", PortCountries.DE),
    DESTA("Stade", PortCountries.DE),
    DESTL("Stralsund", PortCountries.DE),
    DETRD("Osterroenfeld", PortCountries.DE),
    DETRV("Travemunde", PortCountries.DE),
    DEUCK("Ueckermunde", PortCountries.DE),
    DEVIW("Vierow", PortCountries.DE),
    DEWAR("Warnemunde", PortCountries.DE),
    DEWED("Wedel", PortCountries.DE),
    DEWEW("Wewelsfleth", PortCountries.DE),
    DEWHV("Wilhelmshaven Stadt", PortCountries.DE),
    DEWIS("Wismar", PortCountries.DE),
    DEWOL("Wolgast", PortCountries.DE),
    DEWVN("Wilhelmshaven", PortCountries.DE),
    DEWYK("Wyk", PortCountries.DE),
    DK109("Akzo Nobel", PortCountries.DK),
    DKAAB("Aabenraa", PortCountries.DK),
    DKAAL("Aalborg", PortCountries.DK),
    DKAAR("Aarhus", PortCountries.DK),
    DKAGE("Allinge", PortCountries.DK),
    DKAGH("Agger Havn", PortCountries.DK),
    DKARK("Aeroskobing", PortCountries.DK),
    DKASH("Aggersund, Dankalk", PortCountries.DK),
    DKASN("Assens", PortCountries.DK),
    DKASS("Asnæs", PortCountries.DK),
    DKASV("Asnaesvaerkets Havn", PortCountries.DK),
    DKAUB("Augustenborg", PortCountries.DK),
    DKAVE("Avedorevaerkets Havn", PortCountries.DK),
    DKAVN("Avernakke Havn", PortCountries.DK),
    DKBAG("Bagenkop", PortCountries.DK),
    DKBAL("Ballen", PortCountries.DK),
    DKBDX("Bandholm", PortCountries.DK),
    DKCPH("Kobenhavn", PortCountries.DK),
    DKCSO("Christianso", PortCountries.DK),
    DKDAN("Dania, Cementfabrikken", PortCountries.DK),
    DKDAS("Mariager, Azko Dansk Salt", PortCountries.DK),
    DKDRA("Dragor", PortCountries.DK),
    DKEBJ("Esbjerg", PortCountries.DK),
    DKEBT("Ebeltoft", PortCountries.DK),
    DKEND("Egernsund", PortCountries.DK),
    DKENS("Enstedvaerkets Havn", PortCountries.DK),
    DKFAA("Faaborg", PortCountries.DK),
    DKFAK("Fakse Ladeplads", PortCountries.DK),
    DKFDH("Frederikshavn", PortCountries.DK),
    DKFDV("Frederiksvark, Baltic", PortCountries.DK),
    DKFRC("Fredericia", PortCountries.DK),
    DKFUH("Fur", PortCountries.DK),
    DKFYH("Fynshav", PortCountries.DK),
    DKGDM("Gudhjem", PortCountries.DK),
    DKGED("Gedser", PortCountries.DK),
    DKGFH("Gulfport, Stigsnaes", PortCountries.DK),
    DKGLE("Gilleleje", PortCountries.DK),
    DKGRA("Graasten", PortCountries.DK),
    DKGRE("Grenaa", PortCountries.DK),
    DKGTS("Glatved Lasteanlaeg", PortCountries.DK),
    DKHAD("Haderslev", PortCountries.DK),
    DKHAN("Hanstholm", PortCountries.DK),
    DKHAS("Hals", PortCountries.DK),
    DKHBK("Holbaek", PortCountries.DK),
    DKHBO("Hobro", PortCountries.DK),
    DKHHV("Hammerhavnen", PortCountries.DK),
    DKHIR("Hirtshals", PortCountries.DK),
    DKHLS("Helsingor", PortCountries.DK),
    DKHNB("Havneby, Romo", PortCountries.DK),
    DKHOR("Horsens", PortCountries.DK),
    DKHSL("Hasle", PortCountries.DK),
    DKHSU("Hadsund", PortCountries.DK),
    DKHUN("Hundested", PortCountries.DK),
    DKHVS("Hvide Sande", PortCountries.DK),
    DKKAL("Kalundborg", PortCountries.DK),
    DKKAV("Kalvehave", PortCountries.DK),
    DKKBK("Karrebaksminde", PortCountries.DK),
    DKKBY("Kyndbyvaerkets Havn", PortCountries.DK),
    DKKDM("Kollund Mole", PortCountries.DK),
    DKKGL("Kongsdal Harbour", PortCountries.DK),
    DKKLH("Klintholm", PortCountries.DK),
    DKKOG("Koge", PortCountries.DK),
    DKKOK("Kolby Kas", PortCountries.DK),
    DKKOL("Kolding", PortCountries.DK),
    DKKON("Kongsdal, Cementfabrikken", PortCountries.DK),
    DKKOR("Korshavn", PortCountries.DK),
    DKKRA("Kragenaes", PortCountries.DK),
    DKKRR("Korsor", PortCountries.DK),
    DKKTD("Kerteminde", PortCountries.DK),
    DKLGR("Logstor", PortCountries.DK),
    DKLHH("Lindholm Havn", PortCountries.DK),
    DKLIN("Lindo", PortCountries.DK),
    DKLIP("Lindo Industripark A/S", PortCountries.DK),
    DKLOH("Lohals", PortCountries.DK),
    DKLUN("Lundeborg", PortCountries.DK),
    DKLVG("Lemvig", PortCountries.DK),
    DKLYU("Lyohavn", PortCountries.DK),
    DKMAS("Masnedo", PortCountries.DK),
    DKMID("Middelfart", PortCountries.DK),
    DKMOM("Mommark", PortCountries.DK),
    DKMRS("Marstal", PortCountries.DK),
    DKNAK("Nakskov", PortCountries.DK),
    DKNBG("Nyborg", PortCountries.DK),
    DKNEX("Nexo", PortCountries.DK),
    DKNRS("Noerresundby", PortCountries.DK),
    DKNTD("Nysted", PortCountries.DK),
    DKNVD("Naestved", PortCountries.DK),
    DKNYB("Nyborg Lystbaadehavn", PortCountries.DK),
    DKNYF("Nykobing Falster", PortCountries.DK),
    DKNYM("Nykobing Mors", PortCountries.DK),
    DKODE("Odense", PortCountries.DK),
    DKONS("Onsevig", PortCountries.DK),
    DKRAN("Randers", PortCountries.DK),
    DKRDH("Rodvig", PortCountries.DK),
    DKRKB("Rudkobing", PortCountries.DK),
    DKRMO("Romo", PortCountries.DK),
    DKRNN("Ronne", PortCountries.DK),
    DKROD("Rodbyhavn", PortCountries.DK),
    DKROF("Rodby (Faergehavn)", PortCountries.DK),
    DKROR("Aalborg Portland", PortCountries.DK),
    DKRRV("Rorvig", PortCountries.DK),
    DKSAX("Sakskobing", PortCountries.DK),
    DKSBK("Stubbekobing", PortCountries.DK),
    DKSGD("Sonderborg", PortCountries.DK),
    DKSIT("Stigsnaes Interterminals", PortCountries.DK),
    DKSJO("Sjaellands Odde", PortCountries.DK),
    DKSKA("Skagen", PortCountries.DK),
    DKSKB("Skaerbaeksvaerkets Havn", PortCountries.DK),
    DKSKV("Skive", PortCountries.DK),
    DKSOB("Soby", PortCountries.DK),
    DKSPB("Spodsbjerg", PortCountries.DK),
    DKSSV("Studstrupvaerkets Havn", PortCountries.DK),
    DKSTE("Stege", PortCountries.DK),
    DKSTG("Stigsnaesvarkets Havn", PortCountries.DK),
    DKSTN("Stigsnæs", PortCountries.DK),
    DKSTP("Stevns Pier", PortCountries.DK),
    DKSTR("Struer", PortCountries.DK),
    DKSTT("Statoil, Kalundborg", PortCountries.DK),
    DKSVA("Svaneke", PortCountries.DK),
    DKSVE("Svendborg", PortCountries.DK),
    DKSVV("Frederiksvaerk, Dansteel", PortCountries.DK),
    DKTED("Thisted", PortCountries.DK),
    DKTYB("Thyboron", PortCountries.DK),
    DKUNX("Masnedsund", PortCountries.DK),
    DKVBN("Vordingborg Nordhavn", PortCountries.DK),
    DKVBS("Vordingborg Sydhavn", PortCountries.DK),
    DKVEJ("Vejle", PortCountries.DK),
    DKVNG("Vang Pier", PortCountries.DK),
    DKVOR("Vordingborg", PortCountries.DK),
    DKVRE("Avedore", PortCountries.DK),
    DKVSV("Nordjyllandsvaerkets Havn", PortCountries.DK),
    DZALG("ALGER (ALGIERS)", PortCountries.DZ),
    DZAZW("Arzew", PortCountries.DZ),
    DZBJA("Bejaia", PortCountries.DZ),
    DZBTA("BETHOULA", PortCountries.DZ),
    DZDJE("DJEN-DJEN", PortCountries.DZ),
    DZGHA("GHARDAIA", PortCountries.DZ),
    DZORN("ORAN", PortCountries.DZ),
    DZSKI("SKIKDA (EX PHILIPPEVILLE)", PortCountries.DZ),
    EEBEK("Bekkeri", PortCountries.EE),
    EEDIR("Dirhami", PortCountries.EE),
    EEHAA("Haapsalu", PortCountries.EE),
    EEHLT("Heltermaa", PortCountries.EE),
    EEHUN("Hundipea", PortCountries.EE),
    EEKHN("Kihnu", PortCountries.EE),
    EEKND("Kunda", PortCountries.EE),
    EEKUI("Kuivastu", PortCountries.EE),
    EELEN("Lennusadam", PortCountries.EE),
    EELHS("Lahesuu", PortCountries.EE),
    EELHT("Lethma", PortCountries.EE),
    EELSA("Loksa", PortCountries.EE),
    EEMDR("Miidruranna", PortCountries.EE),
    EEMNT("Montu", PortCountries.EE),
    EEMRL("Merelaiu", PortCountries.EE),
    EEMRS("Meeruse", PortCountries.EE),
    EEMUG("Muuga", PortCountries.EE),
    EENAS("Nasva", PortCountries.EE),
    EENOB("Noblessneri", PortCountries.EE),
    EEPAR("Patareisadam", PortCountries.EE),
    EEPAS("Paljassaare", PortCountries.EE),
    EEPLA("Paldiski", PortCountries.EE),
    EEPLN("Paldiski Pohjasadam", PortCountries.EE),
    EEPLS("Paldiski Lounasadam", PortCountries.EE),
    EEPRN("Parnu", PortCountries.EE),
    EERHK("Rohukula", PortCountries.EE),
    EERMS("Roomassaare", PortCountries.EE),
    EESLM("Sillamae", PortCountries.EE),
    EESMA("Saaremaa", PortCountries.EE),
    EESVI("Sviby", PortCountries.EE),
    EETGI("Triigi", PortCountries.EE),
    EETLL("Tallinn", PortCountries.EE),
    EEVAN("Vanasadam", PortCountries.EE),
    EEVEB("Vene-Balti", PortCountries.EE),
    EEVIR("Virtsu", PortCountries.EE),
    EGADA("Al Adabiyah  ", PortCountries.EG),
    EGAGZ("Al Jizah (Giza)  ", PortCountries.EG),
    EGAIS("Ain Sukhna", PortCountries.EG),
    EGAKI("Abu Kir", PortCountries.EG),
    EGALY("Alexandria", PortCountries.EG),
    EGAQU("Al Qusayr  ", PortCountries.EG),
    EGAST("Asyut  ", PortCountries.EG),
    EGASW("Aswan", PortCountries.EG),
    EGAUE("Abu Rudeis  ", PortCountries.EG),
    EGAZA("Abu Zenimah", PortCountries.EG),
    EGBEH("El Beheirah  ", PortCountries.EG),
    EGBEN("Beni Suef  ", PortCountries.EG),
    EGBGB("Atakka Dry Port  ", PortCountries.EG),
    EGCA7("New Cairo", PortCountries.EG),
    EGCAI("Cairo", PortCountries.EG),
    EGCUB("Qalyub  ", PortCountries.EG),
    EGDAM("Damietta", PortCountries.EG),
    EGEDK("El Dekheila  ", PortCountries.EG),
    EGEEG("An Nukhaylah  ", PortCountries.EG),
    EGEOB("El Obour  ", PortCountries.EG),
    EGFAD("Fa'id", PortCountries.EG),
    EGFAN("Fanara", PortCountries.EG),
    EGGEI("Geisum Terminal  ", PortCountries.EG),
    EGGUA("El Gouna", PortCountries.EG),
    EGHAL("Halaib  ", PortCountries.EG),
    EGHAM("Hamrawein  ", PortCountries.EG),
    EGHEL("Heliopolis  ", PortCountries.EG),
    EGHRG("Hurghada  ", PortCountries.EG),
    EGISM("Ismailia  ", PortCountries.EG),
    EGKEH("Kafr El Sheikh  ", PortCountries.EG),
    EGKEN("Kenna  ", PortCountries.EG),
    EGMAH("Mersa El Hamra  ", PortCountries.EG),
    EGMIN("Al Minya  ", PortCountries.EG),
    EGMUH("Matruh-Gargob", PortCountries.EG),
    EGNUW("Nuwaiba  ", PortCountries.EG),
    EGPIB("Port Ibrahim  ", PortCountries.EG),
    EGPRA("Rashid", PortCountries.EG),
    EGPSD("Port Said", PortCountries.EG),
    EGPSE("Port Said East  ", PortCountries.EG),
    EGPTK("Port Tewfik  ", PortCountries.EG),
    EGQAH("Nasr City  ", PortCountries.EG),
    EGRAB("Ras Budran  ", PortCountries.EG),
    EGRAG("Ras Gharib  ", PortCountries.EG),
    EGRSH("Ras Shukheir  ", PortCountries.EG),
    EGRSU("Ras Sudr  ", PortCountries.EG),
    EGSBA("Sidi Barrani  ", PortCountries.EG),
    EGSCN("Suez Canal  ", PortCountries.EG),
    EGSGA("Safaga  ", PortCountries.EG),
    EGSHG("Sohag  ", PortCountries.EG),
    EGSIN("South Sinai (Ganoub Sinai)  ", PortCountries.EG),
    EGSKR("Sakr Koreish  ", PortCountries.EG),
    EGSKT("Sidi Kerir Terminal", PortCountries.EG),
    EGSOK("Sokhna Port  ", PortCountries.EG),
    EGSOS("Sosdi/6th October  ", PortCountries.EG),
    EGSSH("Sharm ash Shaykh  ", PortCountries.EG),
    EGSUZ("Suez", PortCountries.EG),
    EGTOR("El Tor", PortCountries.EG),
    EGWAF("Wadi Feiran  ", PortCountries.EG),
    ESACA("Alcanar", PortCountries.ES),
    ESACE("Arrecife de Lanzarote", PortCountries.ES),
    ESADR("Adra", PortCountries.ES),
    ESAGA("Agaete", PortCountries.ES),
    ESAGP("Malaga", PortCountries.ES),
    ESAGU("Aguilas", PortCountries.ES),
    ESALC("Alicante", PortCountries.ES),
    ESALD("Alcudia", PortCountries.ES),
    ESALG("Algeciras", PortCountries.ES),
    ESARI("Arguineguin", PortCountries.ES),
    ESAVS("Aviles", PortCountries.ES),
    ESBBE("Barbate", PortCountries.ES),
    ESBCN("Barcelona", PortCountries.ES),
    ESBIO("Bilbao", PortCountries.ES),
    ESBLA("Blanes", PortCountries.ES),
    ESBRL("Burela", PortCountries.ES),
    ESBRM("Bermeo", PortCountries.ES),
    ESBRX("Burriana", PortCountries.ES),
    ESCAD("Cadiz", PortCountries.ES),
    ESCAR("Cartagena", PortCountries.ES),
    ESCAS("Castellon de la Plana", PortCountries.ES),
    ESCBS("Cala Sabina", PortCountries.ES),
    ESCBZ("Cabezuela", PortCountries.ES),
    ESCCN("Corcubion", PortCountries.ES),
    ESCEE("Brens-Cee", PortCountries.ES),
    ESCEL("Celeiro", PortCountries.ES),
    ESCEU("Ceuta", PortCountries.ES),
    ESCNO("Carino", PortCountries.ES),
    ESCRS("Carboneras", PortCountries.ES),
    ESDNA("Denia", PortCountries.ES),
    ESESC("Escombreras", PortCountries.ES),
    ESFNI("Formentera", PortCountries.ES),
    ESFRO("Ferrol", PortCountries.ES),
    ESFUE("Puerto del Rosario", PortCountries.ES),
    ESGAN("Gandia", PortCountries.ES),
    ESGAR("Garrucha", PortCountries.ES),
    ESGIJ("Gijon", PortCountries.ES),
    ESGND("Granadilla", PortCountries.ES),
    ESHIE("Puerto de la Estaca (El Hierro)", PortCountries.ES),
    ESHUV("Huelva", PortCountries.ES),
    ESIBZ("Eivissa", PortCountries.ES),
    ESLAX("Laxe", PortCountries.ES),
    ESLCG("A Coruna", PortCountries.ES),
    ESLCR("Los Cristianos", PortCountries.ES),
    ESLEI("Almeria", PortCountries.ES),
    ESLEK("Lequeitio", PortCountries.ES),
    ESLES("La Estaca", PortCountries.ES),
    ESLPA("Las Palmas de Gran Canaria", PortCountries.ES),
    ESLPC("Puebla del Caramiñal", PortCountries.ES),
    ESMAH("Mahon", PortCountries.ES),
    ESMAR("Marin", PortCountries.ES),
    ESMGR("MUGARDOS", PortCountries.ES),
    ESMLN("Mellila", PortCountries.ES),
    ESMOT("Motril", PortCountries.ES),
    ESMPG("Marin", PortCountries.ES),
    ESMRS("Muros", PortCountries.ES),
    ESMZO("Mazarron", PortCountries.ES),
    ESOND("Ondarroa", PortCountries.ES),
    ESPAL("Palamos", PortCountries.ES),
    ESPAS("Pasaia", PortCountries.ES),
    ESPMI("Palma de Mallorca", PortCountries.ES),
    ESPNY("Sant Antoni de Portmany", PortCountries.ES),
    ESPSM("Puerto de Santa Maria", PortCountries.ES),
    ESPUS("Puerto Real", PortCountries.ES),
    ESQIU("Ciudadela", PortCountries.ES),
    ESRBI("Ribeira", PortCountries.ES),
    ESRBS("Ribadesella", PortCountries.ES),
    ESRGA("Arinaga", PortCountries.ES),
    ESRIB("Ribadeo", PortCountries.ES),
    ESROS("Rosas", PortCountries.ES),
    ESROT("Rota", PortCountries.ES),
    ESSAD("Sada", PortCountries.ES),
    ESSAG("Sagunto", PortCountries.ES),
    ESSAT("Salinetas", PortCountries.ES),
    ESSCI("San Ciprian", PortCountries.ES),
    ESSCR("San Carlos de la Rapita", PortCountries.ES),
    ESSCT("Santa Cruz de Tenerife", PortCountries.ES),
    ESSDR("Santander", PortCountries.ES),
    ESSIT("Sitges", PortCountries.ES),
    ESSOL("El Port", PortCountries.ES),
    ESSPC("Santa Cruz de la Palma", PortCountries.ES),
    ESSPO("Santa Pola", PortCountries.ES),
    ESSSG("San Sebastian de la Gomera", PortCountries.ES),
    ESSVQ("Sevilla", PortCountries.ES),
    ESTAR("Tarragona", PortCountries.ES),
    ESTCI("Tenerife", PortCountries.ES),
    ESTJI("La Tejita", PortCountries.ES),
    ESTOR("Torrevieja", PortCountries.ES),
    ESTRF("Tarifa", PortCountries.ES),
    ESVCC("Vallcarca", PortCountries.ES),
    ESVGO("Vigo", PortCountries.ES),
    ESVIL("Vilagarcia de Arousa", PortCountries.ES),
    ESVIV("Viveiro", PortCountries.ES),
    ESVLC("Valencia", PortCountries.ES),
    ESVLG("Vilanova I La Geltru", PortCountries.ES),
    ESVVC("Villanueva de Castellón", PortCountries.ES),
    ESVZR("Vinaroz", PortCountries.ES),
    ESZFR("Zona Franca de Cadiz", PortCountries.ES),
    ESZJF("Pobra do Caraminal", PortCountries.ES),
    FIDLS("Taalintehdas", PortCountries.FI),
    FIDRA("Dragsfjard", PortCountries.FI),
    FIECK("Eckero", PortCountries.FI),
    FIEJO("Eurajoki", PortCountries.FI),
    FIFAR("Farjsund", PortCountries.FI),
    FIFOR("Forby", PortCountries.FI),
    FIGDB("Godby", PortCountries.FI),
    FIHAO("Hailuoto", PortCountries.FI),
    FIHEL("Helsinki", PortCountries.FI),
    FIHIM("Himanka", PortCountries.FI),
    FIHKO("Hanko", PortCountries.FI),
    FIHMN("Hamina", PortCountries.FI),
    FIHOU("Houtskari", PortCountries.FI),
    FIIMA("Imatra", PortCountries.FI),
    FIINK("Inkoo", PortCountries.FI),
    FIISN("Isnas", PortCountries.FI),
    FIJOE("Joensuu", PortCountries.FI),
    FIJOU("Joutseno", PortCountries.FI),
    FIKAS("Kaskinen", PortCountries.FI),
    FIKEM("Kemi", PortCountries.FI),
    FIKIM("Kemio", PortCountries.FI),
    FIKJO("Kalajoki", PortCountries.FI),
    FIKKR("Kokar", PortCountries.FI),
    FIKNT("Kantvik", PortCountries.FI),
    FIKOK("Kokkola", PortCountries.FI),
    FIKOR("Korppoo", PortCountries.FI),
    FIKRS("Kristiinankaupunki", PortCountries.FI),
    FIKTK("Kotka", PortCountries.FI),
    FIKTQ("Kitee", PortCountries.FI),
    FIKUO("Kuopio", PortCountries.FI),
    FIKVH("Koverhar", PortCountries.FI),
    FILAN("Langnas", PortCountries.FI),
    FILAP("Lappohja", PortCountries.FI),
    FILLO("Lapaluoto", PortCountries.FI),
    FILOV("Loviisa", PortCountries.FI),
    FILPP("Lappeenranta", PortCountries.FI),
    FIMER("Merikarvia", PortCountries.FI),
    FIMHQ("Mariehamn", PortCountries.FI),
    FIMJO("Mjosund", PortCountries.FI),
    FIMTL("Pori/Mantyluoto", PortCountries.FI),
    FIMTY("Mantyluoto", PortCountries.FI),
    FINAU("Naugo", PortCountries.FI),
    FINLI("Naantali", PortCountries.FI),
    FIOLK("OLKILUOTO", PortCountries.FI),
    FIOUL("Oulu", PortCountries.FI),
    FIPAR("Parainen", PortCountries.FI),
    FIPOH("Pohjankuru", PortCountries.FI),
    FIPOR("Pori", PortCountries.FI),
    FIPRS("Pietarsaari", PortCountries.FI),
    FIPRV("Porvoo", PortCountries.FI),
    FIPUH("Puhos", PortCountries.FI),
    FIRAA("Raahe", PortCountries.FI),
    FIRAU("Rauma", PortCountries.FI),
    FIREP("Reposaari", PortCountries.FI),
    FIRIS("Ristiina", PortCountries.FI),
    FIRTR("Rautaruukki", PortCountries.FI),
    FISAL("Salo", PortCountries.FI),
    FISII("Siilinjarvi", PortCountries.FI),
    FISIP("Sipoo", PortCountries.FI),
    FISKB("Skogby", PortCountries.FI),
    FISKV("Skoldvik", PortCountries.FI),
    FISUL("Kotka/Sumila", PortCountries.FI),
    FISVL("Savonlinna", PortCountries.FI),
    FITAI("Tammisaari", PortCountries.FI),
    FITEI("Teijo", PortCountries.FI),
    FITHK("Tahkoluoto", PortCountries.FI),
    FITKU("Turku", PortCountries.FI),
    FITOK("Tolkkinen", PortCountries.FI),
    FITOR("Tornio", PortCountries.FI),
    FIUKI("Uusikaupunki", PortCountries.FI),
    FIUKP("Uusikarlepyy", PortCountries.FI),
    FIUUS("Uusi-Valamo/Heinävesi", PortCountries.FI),
    FIVAA("Vaasa", PortCountries.FI),
    FIVFT("Vastanfjard", PortCountries.FI),
    FIVKO("Valko (Valkom)", PortCountries.FI),
    FIVKT("Vuoksi", PortCountries.FI),
    FIVRK("Varkaus", PortCountries.FI),
    FIVSS("Vuosaari", PortCountries.FI),
    FIYXP("Yxpila", PortCountries.FI),
    FRAIS("Cassis", PortCountries.FR),
    FRAJA("Ajaccio", PortCountries.FR),
    FRANO("Langon", PortCountries.FR),
    FRANT("Antibes", PortCountries.FR),
    FRBAS("Bassens", PortCountries.FR),
    FRBAY("Bayonne", PortCountries.FR),
    FRBEC("Bec-d'Ambès", PortCountries.FR),
    FRBEE("Berre", PortCountries.FR),
    FRBES("Brest", PortCountries.FR),
    FRBIA("Bastia", PortCountries.FR),
    FRBNV("Barneville-Carteret", PortCountries.FR),
    FRBOD("Bordeaux (GPM)", PortCountries.FR),
    FRBOL("Boulogne", PortCountries.FR),
    FRBON("Bonifacio", PortCountries.FR),
    FRBYE("Blaye", PortCountries.FR),
    FRBZM("Beaulieu-sur-Mer", PortCountries.FR),
    FRCEQ("Cannes", PortCountries.FR),
    FRCER("Cherbourg", PortCountries.FR),
    FRCFR("Caen - Ouistreham", PortCountries.FR),
    FRCLY("Calvi", PortCountries.FR),
    FRCOC("Concarneau", PortCountries.FR),
    FRCOS("Carros", PortCountries.FR),
    FRCOZ("Caronte", PortCountries.FR),
    FRCQF("Calais", PortCountries.FR),
    FRDIL("Dielette", PortCountries.FR),
    FRDKK("Dunkerque (GPM)", PortCountries.FR),
    FRDON("Donges", PortCountries.FR),
    FRDPE("Dieppe", PortCountries.FR),
    FRDRZ("Douarnenez", PortCountries.FR),
    FRETN("Menton", PortCountries.FR),
    FRFEC("Fecamp", PortCountries.FR),
    FRFOS("Fos-sur-Mer", PortCountries.FR),
    FRGFR("Granville", PortCountries.FR),
    FRGLO("Gonfreville-l'Orcher", PortCountries.FR),
    FRHON("Honfleur", PortCountries.FR),
    FRILR("L'Ile-Rousse", PortCountries.FR),
    FRIRK("Dunkirk", PortCountries.FR),
    FRLAV("Lavera", PortCountries.FR),
    FRLCT("La Ciotat", PortCountries.FR),
    FRLEH("Le Havre (GPM)", PortCountries.FR),
    FRLEZ("Lezardrieux", PortCountries.FR),
    FRLNG("Longueville-sur-Scie", PortCountries.FR),
    FRLPE("La Pallice", PortCountries.FR),
    FRLRH("La Rochelle- La Pallice (GPM)", PortCountries.FR),
    FRLRT("Lorient", PortCountries.FR),
    FRLSO("Les Sables d'Olonne", PortCountries.FR),
    FRLTR("Le Treport", PortCountries.FR),
    FRLTT("Le Trait", PortCountries.FR),
    FRLVE("Le Verdon-sur-Mer", PortCountries.FR),
    FRMN4("Montoire", PortCountries.FR),
    FRMRS("Marseille (GPM)", PortCountries.FR),
    FRMTU("Martigues", PortCountries.FR),
    FRMTX("Montoir-de-Bretagne", PortCountries.FR),
    FRMWR("Marseillan", PortCountries.FR),
    FRNCE("Nice-Villefranche", PortCountries.FR),
    FRNOU("Port-la-Nouvelle", PortCountries.FR),
    FRNTE("Nantes-Saint Nazaire (GPM)", PortCountries.FR),
    FROUI("Ouisterham", PortCountries.FR),
    FRPAP("Pauillac", PortCountries.FR),
    FRPBF("Paimboeuf", PortCountries.FR),
    FRPDB("Port-de-Bouc", PortCountries.FR),
    FRPET("Petit-Couronne", PortCountries.FR),
    FRPJE("Port-Jerome", PortCountries.FR),
    FRPOV("Port-Vendres", PortCountries.FR),
    FRPOX("Pontrieux", PortCountries.FR),
    FRPRJ("Port-Joinville", PortCountries.FR),
    FRPRP("Propriano", PortCountries.FR),
    FRPSL("Port-Saint-Louis-du-Rhône", PortCountries.FR),
    FRPVO("Porto Vecchio", PortCountries.FR),
    FRRAD("Radicatel", PortCountries.FR),
    FRRCO("Rochefort", PortCountries.FR),
    FRROS("Roscoff-Bloscon", PortCountries.FR),
    FRSBK("Le Legue - St Brieuc", PortCountries.FR),
    FRSET("Sete", PortCountries.FR),
    FRSML("Saint Malo", PortCountries.FR),
    FRSNR("Saint-Nazaire", PortCountries.FR),
    FRSTP("Saint-Tropez", PortCountries.FR),
    FRTLN("Toulon", PortCountries.FR),
    FRTON("Tonnay Charente", PortCountries.FR),
    FRTRE("Treguier", PortCountries.FR),
    FRURO("Rouen (GPM)", PortCountries.FR),
    FRWBY("Bayon", PortCountries.FR),
    GBABA("Aberaeron", PortCountries.GB),
    GBABD("Aberdeen", PortCountries.GB),
    GBADM("Aird Mhor", PortCountries.GB),
    GBADR("Aberdaron", PortCountries.GB),
    GBAGO("Arinagour", PortCountries.GB),
    GBAMD("Armadale", PortCountries.GB),
    GBAMR("Aird Ma Ruibhe", PortCountries.GB),
    GBARD("Ardrossan", PortCountries.GB),
    GBASG("Ardrishaig", PortCountries.GB),
    GBAVO("Avonmouth", PortCountries.GB),
    GBAYR("Ayr", PortCountries.GB),
    GBAYW("Aberystwyth", PortCountries.GB),
    GBBAD("Barry Dock", PortCountries.GB),
    GBBAN("Bangor", PortCountries.GB),
    GBBAW("Baltic Wharf", PortCountries.GB),
    GBBDI("Brodick", PortCountries.GB),
    GBBEL("Belfast", PortCountries.GB),
    GBBFB("Braefoot", PortCountries.GB),
    GBBHK("Bromborough dock", PortCountries.GB),
    GBBHR("Barrow Haven", PortCountries.GB),
    GBBIF("Barrow in Furness", PortCountries.GB),
    GBBKG("Barking", PortCountries.GB),
    GBBLK("Blackpool", PortCountries.GB),
    GBBLS("Brightlingsea", PortCountries.GB),
    GBBLY("Blyth", PortCountries.GB),
    GBBOC("Burnham on Crouch", PortCountries.GB),
    GBBOS("Boston", PortCountries.GB),
    GBBRK("Birkenhead", PortCountries.GB),
    GBBRP("Bridport", PortCountries.GB),
    GBBRS("Bristol", PortCountries.GB),
    GBBRU("Bruray", PortCountries.GB),
    GBBRW("Bridgwater", PortCountries.GB),
    GBBRX("Brixham", PortCountries.GB),
    GBBTL("Burntisland", PortCountries.GB),
    GBBUC("Buckie", PortCountries.GB),
    GBBWK("Berwick upon Tweed", PortCountries.GB),
    GBCAG("Ceann a Gharaidh", PortCountries.GB),
    GBCAN("Canvey Island", PortCountries.GB),
    GBCBA("Castlebay", PortCountries.GB),
    GBCBT("Campbeltown", PortCountries.GB),
    GBCDF("Cardiff", PortCountries.GB),
    GBCEI("Newquay (Dyfed)", PortCountries.GB),
    GBCHE("Mostyn", PortCountries.GB),
    GBCLJ("Claonaig", PortCountries.GB),
    GBCLR("Coleraine", PortCountries.GB),
    GBCLY("Clydebank", PortCountries.GB),
    GBCMP("Crombie Pier", PortCountries.GB),
    GBCNA("Canna", PortCountries.GB),
    GBCNU("Craignure", PortCountries.GB),
    GBCOR("Corpach", PortCountries.GB),
    GBCOW("Cowes", PortCountries.GB),
    GBCOY("Coryton", PortCountries.GB),
    GBCRN("Cromarty", PortCountries.GB),
    GBCSN("Garston", PortCountries.GB),
    GBCTM("Chatham", PortCountries.GB),
    GBCYN("Cairnryan", PortCountries.GB),
    GBCYP("Clydeport", PortCountries.GB),
    GBDAG("Dagenham", PortCountries.GB),
    GBDET("Denton", PortCountries.GB),
    GBDFD("Dartford", PortCountries.GB),
    GBDGL("Douglas", PortCountries.GB),
    GBDNU("Dunoon", PortCountries.GB),
    GBDTM("Darmouth", PortCountries.GB),
    GBDUN("Dundee", PortCountries.GB),
    GBDVR("Dover", PortCountries.GB),
    GBDYN("Ardyne", PortCountries.GB),
    GBEAM("Eastham", PortCountries.GB),
    GBELL("Ellesmere Port", PortCountries.GB),
    GBERI("Erith", PortCountries.GB),
    GBESH("Shoreham By Sea", PortCountries.GB),
    GBEYM("Eyemouth", PortCountries.GB),
    GBFAL("Falmouth", PortCountries.GB),
    GBFAS("Faslane", PortCountries.GB),
    GBFAW("Fawley", PortCountries.GB),
    GBFEE("Fairlie", PortCountries.GB),
    GBFIS("Fishguard", PortCountries.GB),
    GBFLE("Fleetwood", PortCountries.GB),
    GBFLH("Flotta", PortCountries.GB),
    GBFLU("Flushing", PortCountries.GB),
    GBFLW("Flixborough", PortCountries.GB),
    GBFNH("Fishnish", PortCountries.GB),
    GBFNT("Finnart", PortCountries.GB),
    GBFOL("Folkestone", PortCountries.GB),
    GBFOR("Forth", PortCountries.GB),
    GBFOY("Fowey", PortCountries.GB),
    GBFRB("Fraserburgh", PortCountries.GB),
    GBFXT("Felixstowe", PortCountries.GB),
    GBGAI("Gainsborough", PortCountries.GB),
    GBGAR("Gairloch", PortCountries.GB),
    GBGAS("Galmisdale", PortCountries.GB),
    GBGAT("Gateshead", PortCountries.GB),
    GBGIR("Girvan", PortCountries.GB),
    GBGLD("Glasson Dock", PortCountries.GB),
    GBGLW("Glasgow", PortCountries.GB),
    GBGOA("Great Oakley", PortCountries.GB),
    GBGOO("Goole", PortCountries.GB),
    GBGRG("Grangemouth", PortCountries.GB),
    GBGRJ("Grovehurst Jetty", PortCountries.GB),
    GBGRK("Greenock", PortCountries.GB),
    GBGRW("Grove Wharfs (Scunthorpe)", PortCountries.GB),
    GBGSA("Glensanda", PortCountries.GB),
    GBGSY("Grimsby", PortCountries.GB),
    GBGTY("Great Yarmouth", PortCountries.GB),
    GBGUR("Gourock", PortCountries.GB),
    GBGUT("Gutcher", PortCountries.GB),
    GBGUW("Gunness Wharf (Scunthorpe)", PortCountries.GB),
    GBGVS("Gravesend", PortCountries.GB),
    GBGYS("Grays", PortCountries.GB),
    GBHAM("Hamble", PortCountries.GB),
    GBHDD("Howdendyke", PortCountries.GB),
    GBHLY("Holyhead", PortCountries.GB),
    GBHNS("Hamars Ness", PortCountries.GB),
    GBHOV("Housa Voe, Papa Stour (Shetland)", PortCountries.GB),
    GBHPT("Hound Point", PortCountries.GB),
    GBHRW("Harwich", PortCountries.GB),
    GBHST("Hunterston", PortCountries.GB),
    GBHTP("Hartlepool", PortCountries.GB),
    GBHUL("Hull", PortCountries.GB),
    GBHWZ("Isles of Scilly (Hugh Town St Marys)", PortCountries.GB),
    GBHYM("Heysham", PortCountries.GB),
    GBILL("Gills", PortCountries.GB),
    GBIMM("Immingham", PortCountries.GB),
    GBINC("Ince", PortCountries.GB),
    GBINK("Inverkeithing", PortCountries.GB),
    GBINV("Inverness", PortCountries.GB),
    GBIOG("Isle of Grain", PortCountries.GB),
    GBION("Iona", PortCountries.GB),
    GBIPS("Ipswich", PortCountries.GB),
    GBIVG("Invergordon", PortCountries.GB),
    GBKBE("Kinlochbervie", PortCountries.GB),
    GBKCG("Kennacraig", PortCountries.GB),
    GBKEA("Keadby", PortCountries.GB),
    GBKGH("Killingholme", PortCountries.GB),
    GBKIS("Kishorn", PortCountries.GB),
    GBKKD("Kirkcaldy", PortCountries.GB),
    GBKLN("King's Lynn", PortCountries.GB),
    GBKLR("Kilroot", PortCountries.GB),
    GBKOH("Kinloch", PortCountries.GB),
    GBKWL("Kirkwall", PortCountries.GB),
    GBKYL("Kyle of Lochalsh", PortCountries.GB),
    GBLAR("Larne", PortCountries.GB),
    GBLAX("Laxo", PortCountries.GB),
    GBLBD("Lochboisdale", PortCountries.GB),
    GBLDY("Londonderry", PortCountries.GB),
    GBLEI("Leith", PortCountries.GB),
    GBLER("Lerwick", PortCountries.GB),
    GBLGP("London Gateway Port", PortCountries.GB),
    GBLGS("Largs", PortCountries.GB),
    GBLIT("Littlehampton", PortCountries.GB),
    GBLIV("Liverpool", PortCountries.GB),
    GBLLD("Llanddulas", PortCountries.GB),
    GBLMA("Lochmaddy", PortCountries.GB),
    GBLOL("Lochaline", PortCountries.GB),
    GBLON("London", PortCountries.GB),
    GBLOV("Lochinver", PortCountries.GB),
    GBLOW("Lowestoft", PortCountries.GB),
    GBLRP("Loch Ryan Port", PortCountries.GB),
    GBLRZ("Lochranza", PortCountries.GB),
    GBLSH("Langstone Harbour", PortCountries.GB),
    GBLVR("Leverburgh", PortCountries.GB),
    GBLWT("West Thurrock", PortCountries.GB),
    GBLYS("Lyness, Hoy (Orkney)", PortCountries.GB),
    GBMAL("Maldon", PortCountries.GB),
    GBMAW("Marchwood", PortCountries.GB),
    GBMGT("Margate", PortCountries.GB),
    GBMID("Middlesbrough", PortCountries.GB),
    GBMIS("Mistley", PortCountries.GB),
    GBMLF("Milford Haven", PortCountries.GB),
    GBMLG("Mallaig", PortCountries.GB),
    GBMLP("Millport", PortCountries.GB),
    GBMME("Teesside", PortCountries.GB),
    GBMNC("Manchester", PortCountries.GB),
    GBMON("Montrose", PortCountries.GB),
    GBMRB("Maryfield, Bressay (Shetland)", PortCountries.GB),
    GBMSC("Manchester Ship Canal", PortCountries.GB),
    GBMTH("Methil", PortCountries.GB),
    GBNCL("Newcastle upon Tyne", PortCountries.GB),
    GBNCS("Newcastle", PortCountries.GB),
    GBNEA("Neath", PortCountries.GB),
    GBNEH("Neap House (Scunthorpe)", PortCountries.GB),
    GBNET("Neath (Briton Ferry)", PortCountries.GB),
    GBNFT("Northfleet", PortCountries.GB),
    GBNGG("Nigg", PortCountries.GB),
    GBNHO("New Holland", PortCountries.GB),
    GBNHV("Newhaven", PortCountries.GB),
    GBNOH("North Haven (Fair Isle)", PortCountries.GB),
    GBNPO("Newport (Isle of Wght)", PortCountries.GB),
    GBNPT("Newport (Gwent)", PortCountries.GB),
    GBNSH("NORTH SHIELDS", PortCountries.GB),
    GBNYL("Newlyn", PortCountries.GB),
    GBOBA("Oban", PortCountries.GB),
    GBPAD("Padstow", PortCountries.GB),
    GBPAK("Port Askaig", PortCountries.GB),
    GBPAR("Par", PortCountries.GB),
    GBPED("Pembroke Dock", PortCountries.GB),
    GBPEM("Abercastle", PortCountries.GB),
    GBPEN("Penzance", PortCountries.GB),
    GBPER("Perth", PortCountries.GB),
    GBPFT("Purfleet", PortCountries.GB),
    GBPHD("Peterhead", PortCountries.GB),
    GBPIE("Pierowall (Westray)", PortCountries.GB),
    GBPLN("Port Ellen", PortCountries.GB),
    GBPLY("Plymouth", PortCountries.GB),
    GBPME("Portsmouth", PortCountries.GB),
    GBPMR("Port Mor", PortCountries.GB),
    GBPOO("Poole", PortCountries.GB),
    GBPRT("Portree (Isle of Skye)", PortCountries.GB),
    GBPRU("Royal Portbury", PortCountries.GB),
    GBPRY("Penryn", PortCountries.GB),
    GBPSB("Sutton Bridge", PortCountries.GB),
    GBPST("Parkeston Quay", PortCountries.GB),
    GBPTB("Port Talbot", PortCountries.GB),
    GBPTL("Portland", PortCountries.GB),
    GBPTT("Parkington", PortCountries.GB),
    GBQUB("Queenborough (Rochester)", PortCountries.GB),
    GBRAY("Rothesay", PortCountries.GB),
    GBRCS("Rochester", PortCountries.GB),
    GBRER("Redcar", PortCountries.GB),
    GBRID("Ridham Dock", PortCountries.GB),
    GBRMG("Ramsgate", PortCountries.GB),
    GBROW("Rowehedge", PortCountries.GB),
    GBROY("Rosyth", PortCountries.GB),
    GBRSY("Ramsey", PortCountries.GB),
    GBRUN("Runcorn", PortCountries.GB),
    GBRYE("Rye", PortCountries.GB),
    GBSCA("Scarborough", PortCountries.GB),
    GBSCF("Scapa (Orkney)", PortCountries.GB),
    GBSCG("Scalasaig", PortCountries.GB),
    GBSCN("Scarinish", PortCountries.GB),
    GBSCR("Scrabster", PortCountries.GB),
    GBSEA("Seaham", PortCountries.GB),
    GBSED("Salt End", PortCountries.GB),
    GBSEF("Seaforth", PortCountries.GB),
    GBSFW("Scapa Flow", PortCountries.GB),
    GBSFY("Salford Docks", PortCountries.GB),
    GBSHS("Sheerness", PortCountries.GB),
    GBSHV("Shellhaven", PortCountries.GB),
    GBSIL("Silloth", PortCountries.GB),
    GBSLB("Selby", PortCountries.GB),
    GBSMH("St Margaret's Hope", PortCountries.GB),
    GBSNS("STROMNESS", PortCountries.GB),
    GBSOU("Southampton", PortCountries.GB),
    GBSOW("Stanlow", PortCountries.GB),
    GBSPT("St Peter's Port", PortCountries.GB),
    GBSSH("South Shields", PortCountries.GB),
    GBSSS("Sharpness", PortCountries.GB),
    GBSTH("St Helier", PortCountries.GB),
    GBSTO("Stornoway", PortCountries.GB),
    GBSTR("Stranraer", PortCountries.GB),
    GBSUL("Sullom Voe", PortCountries.GB),
    GBSUN("Sunderland", PortCountries.GB),
    GBSVT("Silvertown", PortCountries.GB),
    GBSWA("Swansea", PortCountries.GB),
    GBSWD("Southwold", PortCountries.GB),
    GBSWY("Scalloway", PortCountries.GB),
    GBSYM("Symbister", PortCountries.GB),
    GBTAB("Tarbert (Harris - Outer Hebrides)", PortCountries.GB),
    GBTBY("Torbay", PortCountries.GB),
    GBTEE("Teesport", PortCountries.GB),
    GBTFT("Toft (Shetland)", PortCountries.GB),
    GBTGU("Tongue", PortCountries.GB),
    GBTHP("Thamesport", PortCountries.GB),
    GBTHS("Thames Haven", PortCountries.GB),
    GBTIL("Tilbury", PortCountries.GB),
    GBTLD("Shetland", PortCountries.GB),
    GBTNM("Teignmouth", PortCountries.GB),
    GBTOB("Tobermory", PortCountries.GB),
    GBTOR("Torquay", PortCountries.GB),
    GBTRA("Tranmere", PortCountries.GB),
    GBTRN("Troon", PortCountries.GB),
    GBTRU("Truro", PortCountries.GB),
    GBTSO("Isles of Scilly (Tresco)", PortCountries.GB),
    GBTTL("Tetney Terminal Monobuoy", PortCountries.GB),
    GBTYN("Tyne", PortCountries.GB),
    GBUIG("Uig", PortCountries.GB),
    GBULL("Ullapool", PortCountries.GB),
    GBULS("Ulsta, Yell (Shetland)", PortCountries.GB),
    GBVID("Vidlin", PortCountries.GB),
    GBWEY("Weymouth", PortCountries.GB),
    GBWHV("Whitehaven", PortCountries.GB),
    GBWIC("Wick", PortCountries.GB),
    GBWIS("Wisbech", PortCountries.GB),
    GBWLZ("Walls", PortCountries.GB),
    GBWMB("Wemyss Bay", PortCountries.GB),
    GBWNS("Wells Next the Sea", PortCountries.GB),
    GBWOR("Workington", PortCountries.GB),
    GBWPT("Warrenpoint", PortCountries.GB),
    GBWTB("Whitby", PortCountries.GB),
    GBWTS("Whitstable", PortCountries.GB),
    GBXSS("Seal Sands", PortCountries.GB),
    GESUP("Supsa Marine Terminal", PortCountries.GE),
    GFCAY("Cayenne", null),
    GFDDC("Degrad des Cannes", null),
    GFQKR("Kourou", null),
    GFSLM("Saint Laurent du Maroni", null),
    GIGIB("Gibraltar", PortCountries.GI),
    GPBBR("Basse-Terre", null),
    GPBMH("Baie Mahault", null),
    GPCBE("Capesterre-Belle-Eau", null),
    GPFAE("Folle-Anse", null),
    GPGOS("Le Gosier", null),
    GPGRB("Grand-Bourg", null),
    GPJAR("Jarry", null),
    GPMSB("Marigot", null),
    GPPTL("Port-Louis", null),
    GPPTP("Pointe-a-Pitre", null),
    GPSFC("Saint-François", null),
    GRACL("Achladi", PortCountries.GR),
    GRADL("Adamas Milos", PortCountries.GR),
    GRAEG("Aegina", PortCountries.GR),
    GRAGE("Agios Georgios", PortCountries.GR),
    GRAGF("Agios Nikolaos Fokidas", PortCountries.GR),
    GRAGG("Agistri", PortCountries.GR),
    GRAGM("Agia Marina Fthiotidas", PortCountries.GR),
    GRAGN("Agathonisi", PortCountries.GR),
    GRAGO("Agios Efstratios", PortCountries.GR),
    GRAGT("Agioi Theodoroi", PortCountries.GR),
    GRAIG("Aigiali Amorgou", PortCountries.GR),
    GRAIO("Alimos", PortCountries.GR),
    GRAIY("Aiyion", PortCountries.GR),
    GRAKI("Agios Kirykos", PortCountries.GR),
    GRAKO("Agios Konstantinos", PortCountries.GR),
    GRAKT("Aktio Vonitsas", PortCountries.GR),
    GRALO("Alonnisos", PortCountries.GR),
    GRALV("Alivérion", PortCountries.GR),
    GRAMF("Amfilochia", PortCountries.GR),
    GRAMI("Amoliani", PortCountries.GR),
    GRAML("Agia Marina Lerou", PortCountries.GR),;

    private final String name;
    private final PortCountries country;

    public static PortCodes1 fromString(String value) {
        for (PortCodes1 e : PortCodes1.values()) {
            if (e.name().equalsIgnoreCase(value)) {
                return e;
            }
        }
        return null;
    }
}
