import { EmpVariationApplicationReturnedForAmendsRequestActionPayload } from '@mrtm/api';

export type EmpVariationReturnedForAmendsActionPayload = EmpVariationApplicationReturnedForAmendsRequestActionPayload;
