export enum MiReportType {
  LIST_OF_ACCOUNTS_USERS_CONTACTS = 'LIST_OF_ACCOUNTS_USERS_CONTACTS',
  CUSTOM = 'CUSTOM',
  LIST_OF_ACCOUNTS_ASSIGNED_REGULATOR_SITE_CONTACTS = 'LIST_OF_ACCOUNTS_ASSIGNED_REGULATOR_SITE_CONTACTS',
  COMPLETED_WORK = 'COMPLETED_WORK',
  REGULATOR_OUTSTANDING_REQUEST_TASKS = 'REGULATOR_OUTSTANDING_REQUEST_TASKS',
  LIST_OF_VERIFICATION_BODY_USERS = 'LIST_OF_VERIFICATION_BODY_USERS',
}
