const { defaultTransformerOptions } = require('jest-preset-angular/presets');

/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  preset: 'jest-preset-angular',
  cacheDirectory: 'tmp/jest/cache',
  moduleNameMapper: {
    '^@netz/govuk-components': '<rootDir>/dist/govuk-components/fesm2022/netz-govuk-components.mjs',
    '^@mrtm/api': '<rootDir>/dist/mrtm-api/fesm2022/mrtm-api.mjs',
    '^@netz/common/(.*)$': '<rootDir>/dist/common/fesm2022/netz-common-$1.mjs',
    '^@accessibility/(.*)': '<rootDir>/src/app/accessibility/$1',
    '^@accounts/(.*)': '<rootDir>/src/app/accounts/$1',
    '^@batch-variations/(.*)': '<rootDir>/src/app/batch-variations/$1',
    '^@contact-us/(.*)': '<rootDir>/src/app/contact-us/$1',
    '^@cookies/(.*)': '<rootDir>/src/app/cookies/$1',
    '^@core/(.*)': '<rootDir>/src/app/core/$1',
    '^@data-suppliers/(.*)': '<rootDir>/src/app/data-suppliers/$1',
    '^@error/(.*)': '<rootDir>/src/app/error/$1',
    '^@feedback/(.*)': '<rootDir>/src/app/feedback/$1',
    '^@forgot-password/(.*)': '<rootDir>/src/app/forgot-password/$1',
    '^@guidance/(.*)': '<rootDir>/src/app/guidance/$1',
    '^@incorporate-header/(.*)': '<rootDir>/src/app/incorporate-header/$1',
    '^@invitation/(.*)': '<rootDir>/src/app/invitation/$1',
    '^@landing-page/(.*)': '<rootDir>/src/app/landing-page/$1',
    '^@legislation/(.*)': '<rootDir>/src/app/legislation/$1',
    '^@mi-reports/(.*)': '<rootDir>/src/app/mi-reports/$1',
    '^@notes/(.*)': '<rootDir>/src/app/notes/$1',
    '^@privacy-notice/(.*)': '<rootDir>/src/app/privacy-notice/$1',
    '^@registration/(.*)': '<rootDir>/src/app/registration/$1',
    '^@regulators/(.*)': '<rootDir>/src/app/regulators/$1',
    '^@requests/(.*)': '<rootDir>/src/app/requests/$1',
    '^@shared/(.*)': '<rootDir>/src/app/shared/$1',
    '^@templates/(.*)': '<rootDir>/src/app/templates/$1',
    '^@terms-and-conditions/(.*)': '<rootDir>/src/app/terms-and-conditions/$1',
    '^@timeout/(.*)': '<rootDir>/src/app/timeout/$1',
    '^@timeline/(.*)': '<rootDir>/src/app/timeline/$1',
    '^@two-fa/(.*)': '<rootDir>/src/app/two-fa/$1',
    '^@verification-bodies/(.*)': '<rootDir>/src/app/verification-bodies/$1',
    '^@verifiers/(.*)': '<rootDir>/src/app/verifiers/$1',
    '^@version/(.*)': '<rootDir>/src/app/version/$1',
    '^@environments/(.*)': '<rootDir>/src/environments/$1',
    '^lodash-es$': 'lodash',
  },
  modulePathIgnorePatterns: ['<rootDir>/dist'],
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  moduleFileExtensions: ['ts', 'html', 'js', 'json', 'mjs'],
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  transform: {
    '^.+\\.(ts|js|mjs|html|svg)$': [
      'jest-preset-angular',
      {
        ...defaultTransformerOptions,
      },
    ],
  },
};
