# The database credentials should be defined there.

driver: org.postgresql.Driver
url: jdbc:postgresql://localhost:5439/mrtm
## username: add here the username of your local db##
## username: add here the password of your local db##
verbose: true
changeLogFile: db/migration/changelog-master.xml
