import { MrtmRequestActionType, MrtmRequestTaskType } from '@shared/types';

const aerTypesList: Array<MrtmRequestTaskType | MrtmRequestActionType> = [
  'AER',
  'AER_APPLICATION_SUBMIT',
  'AER_WAIT_FOR_VERIFICATION',
  'AER_APPLICATION_VERIFICATION_SUBMIT',
  'AER_APPLICATION_SUBMITTED',
  'AER_APPLICATION_SENT_TO_VERIFIER',
  'AER_APPLICATION_VERIFICATION_SUBMITTED',
  'AER_RECALLED_FROM_VERIFICATION',
  'AER_VERIFICATION_RETURNED_TO_OPERATOR',
  'VERIFICATION_STATEMENT_CANCELLED',
  'AER_APPLICATION_REVIEW',
  'AER_WAIT_FOR_AMENDS',
  'AER_WAIT_FOR_REVIEW',
  'AER_APPLICATION_AMENDS_SUBMIT',
  'AER_AMEND_WAIT_FOR_VERIFICATION',
  'AER_APPLICATION_CANCELLED_DUE_TO_EXEMPT',
  'AER_APPLICATION_RE_INITIATED',
  'AER_APPLICATION_EXEMPTION_REVERTED',
  'AER_APPLICATION_REVIEW_SKIPPED',
  'AER_APPLICATION_COMPLETED',
  'AER_APPLICATION_RETURNED_FOR_AMENDS',
  'AER_APPLICATION_AMENDS_SUBMITTED',
  'AER_APPLICATION_AMENDS_SENT_TO_VERIFIER',
  'AER_AMEND_APPLICATION_VERIFICATION_SUBMIT',
];

export const isAer = (type: MrtmRequestTaskType | MrtmRequestActionType): boolean => {
  return aerTypesList.includes(type);
};
