/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountContactVbInfoDTO } from './accountContactVbInfoDTO';

export interface AccountContactVbInfoResponse {
  contacts?: Array<AccountContactVbInfoDTO>;
  editable?: boolean;
  totalItems?: number;
}
