/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountUserContact {
  userId?: string;
  Account_ID?: string;
  Account_name?: string;
  Account_status?: string;
  Is_User_Primary_contact?: boolean;
  User_status?: string;
  Name?: string;
  Telephone?: string;
  Last_logon?: string;
  Email?: string;
  User_role?: string;
}
