/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountOperatorAuthorityUpdateDTO } from './accountOperatorAuthorityUpdateDTO';

/**
 * The account operator authorities to update
 */
export interface AccountOperatorAuthorityUpdateWrapperDTO {
  accountOperatorAuthorityUpdateList: Array<AccountOperatorAuthorityUpdateDTO>;
  contactTypes: { [key: string]: string };
}
