/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountNoteDto } from './accountNoteDto';

export interface AccountNoteResponse {
  accountNotes?: Array<AccountNoteDto>;
  totalItems?: number;
}
