/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountContactInfoDTO } from './accountContactInfoDTO';

export interface AccountContactInfoResponse {
  contacts?: Array<AccountContactInfoDTO>;
  editable?: boolean;
  totalItems?: number;
}
