/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The account reporting status submit dto
 */
export interface AccountReportingStatusHistoryCreationDTO {
  status: 'REQUIRED_TO_REPORT' | 'EXEMPT';
  reason: string;
}
