/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountClosure } from './accountClosure';

export interface AccountClosureSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  accountClosure?: AccountClosure;
}
