/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The account note request
 */
export interface AccountNoteRequest {
  note: string;
  files?: Array<string>;
  accountId: number;
}
