/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The verifier user information
 */
export interface AdminVerifierUserInvitationDTO {
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  mobileNumber?: string;
}
