/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalDocuments } from './additionalDocuments';
import { AerAggregatedData } from './aerAggregatedData';
import { AerEmissions } from './aerEmissions';
import { AerMonitoringPlanChanges } from './aerMonitoringPlanChanges';
import { AerOperatorDetails } from './aerOperatorDetails';
import { AerPortEmissions } from './aerPortEmissions';
import { AerSmf } from './aerSmf';
import { AerTotalEmissions } from './aerTotalEmissions';
import { AerVoyageEmissions } from './aerVoyageEmissions';

export interface Aer {
  operatorDetails: AerOperatorDetails;
  additionalDocuments: AdditionalDocuments;
  emissions: AerEmissions;
  aerMonitoringPlanChanges: AerMonitoringPlanChanges;
  portEmissions?: AerPortEmissions;
  voyageEmissions?: AerVoyageEmissions;
  aggregatedData: AerAggregatedData;
  smf: AerSmf;
  totalEmissions: AerTotalEmissions;
}
