/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerAggregatedEmissionsMeasurementSave {
  co2: string;
  ch4: string;
  n2o: string;
  co2Captured: string;
}
