/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aer } from './aer';
import { AerMonitoringPlanVersion } from './aerMonitoringPlanVersion';
import { AerReportingObligationDetails } from './aerReportingObligationDetails';
import { AerVerificationReport } from './aerVerificationReport';

export interface AerApplicationSubmittedRequestActionPayload {
  payloadType?: string;
  reportingRequired?: boolean;
  reportingObligationDetails?: AerReportingObligationDetails;
  aer?: Aer;
  reportingYear?: number;
  aerMonitoringPlanVersion?: AerMonitoringPlanVersion;
  verificationPerformed?: boolean;
  verificationReport?: AerVerificationReport;
  aerAttachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
}
