/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerShipAggregatedData } from './aerShipAggregatedData';

export interface AerAggregatedData {
  emissions: Array<AerShipAggregatedData>;
}
