/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aer } from './aer';
import { AerMonitoringPlanVersion } from './aerMonitoringPlanVersion';
import { AerReportingObligationDetails } from './aerReportingObligationDetails';
import { AerReviewDecision } from './aerReviewDecision';
import { AerSkipReviewDecision } from './aerSkipReviewDecision';
import { AerVerificationReport } from './aerVerificationReport';

export interface AerApplicationCompletedRequestActionPayload {
  payloadType?: string;
  reportingRequired?: boolean;
  reportingObligationDetails?: AerReportingObligationDetails;
  aer?: Aer;
  reportingYear?: number;
  aerMonitoringPlanVersion?: AerMonitoringPlanVersion;
  verificationPerformed?: boolean;
  verificationReport?: AerVerificationReport;
  aerAttachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
  reviewGroupDecisions?: { [key: string]: AerReviewDecision };
  reviewAttachments?: { [key: string]: string };
  aerSkipReviewDecision?: AerSkipReviewDecision;
}
