/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aer } from './aer';
import { AerMonitoringPlanVersion } from './aerMonitoringPlanVersion';
import { AerReportingObligationDetails } from './aerReportingObligationDetails';
import { AerTotalReportableEmissions } from './aerTotalReportableEmissions';
import { AerVerificationReport } from './aerVerificationReport';

export interface AerApplicationVerificationSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  reportingYear?: number;
  reportingRequired?: boolean;
  reportingObligationDetails?: AerReportingObligationDetails;
  aerMonitoringPlanVersion?: AerMonitoringPlanVersion;
  aerSectionsCompleted?: { [key: string]: string };
  verificationSectionsCompleted?: { [key: string]: string };
  aerAttachments?: { [key: string]: string };
  aer?: Aer;
  verificationReport?: AerVerificationReport;
  totalEmissions?: AerTotalReportableEmissions;
  notCoveredChangesProvided?: string;
}
