/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aer } from './aer';
import { AerMonitoringPlanVersion } from './aerMonitoringPlanVersion';
import { AerReportingObligationDetails } from './aerReportingObligationDetails';
import { AerReviewDecision } from './aerReviewDecision';
import { AerTotalReportableEmissions } from './aerTotalReportableEmissions';
import { AerVerificationReport } from './aerVerificationReport';

export interface AerApplicationReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  reportingYear?: number;
  reportingRequired?: boolean;
  reportingObligationDetails?: AerReportingObligationDetails;
  aerMonitoringPlanVersion?: AerMonitoringPlanVersion;
  aerSectionsCompleted?: { [key: string]: string };
  verificationSectionsCompleted?: { [key: string]: string };
  aerAttachments?: { [key: string]: string };
  aer?: Aer;
  verificationReport?: AerVerificationReport;
  totalEmissions?: AerTotalReportableEmissions;
  notCoveredChangesProvided?: string;
  reviewGroupDecisions?: { [key: string]: AerReviewDecision };
  reviewAttachments?: { [key: string]: string };
}
