/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';

export interface AerApplicationReturnedForAmendsRequestActionPayload {
  payloadType?: string;
  reviewGroupDecisions: { [key: string]: AerReviewDecision };
  reviewAttachments?: { [key: string]: string };
}
