/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelOriginTypeName } from './aerAggregatedDataFuelOriginTypeName';

export interface AerAggregatedDataFuelConsumption {
  fuelOriginTypeName: AerAggregatedDataFuelOriginTypeName;
  totalConsumption: string;
}
