/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerFuelsAndEmissionsFactors } from './aerFuelsAndEmissionsFactors';

export interface AerBioFuels extends AerFuelsAndEmissionsFactors {
  type: 'ETHANOL' | 'BIO_DIESEL' | 'HVO' | 'BIO_LNG' | 'BIO_METHANOL' | 'BIO_H2' | 'OTHER';
}
