/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerComplianceMonitoringReporting {
  accuracyCompliant: boolean;
  accuracyNonCompliantReason?: string;
  completenessCompliant: boolean;
  completenessNonCompliantReason?: string;
  consistencyCompliant: boolean;
  consistencyNonCompliantReason?: string;
  comparabilityCompliant: boolean;
  comparabilityNonCompliantReason?: string;
  transparencyCompliant: boolean;
  transparencyNonCompliantReason?: string;
  integrityCompliant: boolean;
  integrityNonCompliantReason?: string;
}
