/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerEmissionsReductionClaimVerification {
  smfBatchClaimsReviewed: boolean;
  batchReferencesNotReviewed?: string;
  dataSampling?: string;
  reviewResults: string;
  noDoubleCountingConfirmation: string;
  evidenceAllCriteriaMetExist: boolean;
  noCriteriaMetIssues?: string;
  complianceWithEmpRequirementsExist: boolean;
  notCompliedWithEmpRequirementsAspects?: string;
}
