/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerEtsComplianceRules {
  monitoringPlanRequirementsMet: boolean;
  monitoringPlanRequirementsNotMetReason?: string;
  etsOrderRequirementsMet: boolean;
  etsOrderRequirementsNotMetReason?: string;
  detailSourceDataVerified: boolean;
  detailSourceDataNotVerifiedReason?: string;
  partOfSiteVerification?: string;
  controlActivitiesDocumented: boolean;
  controlActivitiesNotDocumentedReason?: string;
  proceduresMonitoringPlanDocumented: boolean;
  proceduresMonitoringPlanNotDocumentedReason?: string;
  dataVerificationCompleted: boolean;
  dataVerificationNotCompletedReason?: string;
  monitoringApproachAppliedCorrectly: boolean;
  monitoringApproachNotAppliedCorrectlyReason?: string;
  methodsApplyingMissingDataUsed: boolean;
  methodsApplyingMissingDataNotUsedReason?: string;
  competentAuthorityGuidanceMet: boolean;
  competentAuthorityGuidanceNotMetReason?: string;
  nonConformities: 'YES' | 'NO' | 'NOT_APPLICABLE';
  nonConformitiesDetails?: string;
}
