/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerFuelsAndEmissionsFactors {
  origin: 'FOSSIL' | 'BIOFUEL' | 'RFNBO';
  name?: string;
  carbonDioxide: string;
  methane: string;
  nitrousOxide: string;
  sustainableFraction?: string;
  uniqueIdentifier: string;
}
