/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FuelOriginTypeName } from './fuelOriginTypeName';

export interface AerFuelConsumption {
  uniqueIdentifier: string;
  fuelOriginTypeName: FuelOriginTypeName;
  name?: string;
  amount: string;
  measuringUnit: 'M3' | 'TONNES';
  fuelDensity?: string;
  totalConsumption: string;
}
