/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelOriginTypeName } from './aerAggregatedDataFuelOriginTypeName';

export interface AerFuelOriginEFuelTypeName extends AerAggregatedDataFuelOriginTypeName {
  type: 'E_DIESEL' | 'E_METHANOL' | 'E_LNG' | 'E_H2' | 'E_NH3' | 'E_LPG' | 'E_DME' | 'OTHER';
}
