/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelOriginTypeName } from './aerAggregatedDataFuelOriginTypeName';

export interface AerFuelOriginFossilTypeName extends AerAggregatedDataFuelOriginTypeName {
  type: 'HFO' | 'LFO' | 'MDO' | 'MGO' | 'LNG' | 'LPG_BUTANE' | 'LPG_PROPANE' | 'H2' | 'NH3' | 'METHANOL' | 'OTHER';
}
