/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerInPersonSiteVisitDates } from './aerInPersonSiteVisitDates';
import { AerSiteVisit } from './aerSiteVisit';

export interface AerInPersonSiteVisit extends AerSiteVisit {
  visitDates: Array<AerInPersonSiteVisitDates>;
  teamMembers: string;
}
