/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerMaterialityLevel {
  materialityDetails: string;
  accreditationReferenceDocumentTypes: Array<
    'SI_2020_1265' | 'EN_ISO_14065_2020' | 'EN_ISO_14064_3_2019' | 'IAF_MD_6_2023' | 'AUTHORITY_GUIDANCE' | 'OTHER'
  >;
  otherReference?: string;
}
