/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerNotVerifiedDecisionReason } from './aerNotVerifiedDecisionReason';
import { AerVerificationDecision } from './aerVerificationDecision';

export interface AerNotVerifiedDecision extends AerVerificationDecision {
  notVerifiedReasons: Array<AerNotVerifiedDecisionReason>;
}
