/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerSiteVisit } from './aerSiteVisit';

export interface AerOpinionStatement {
  emissionsCorrect: boolean;
  manuallyProvidedTotalEmissions?: string;
  manuallyProvidedSurrenderEmissions?: string;
  manuallyProvidedLessVoyagesInNorthernIrelandDeduction?: string;
  additionalChangesNotCovered: boolean;
  additionalChangesNotCoveredDetails?: string;
  siteVisit: AerSiteVisit;
}
