/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerFuelConsumption } from './aerFuelConsumption';
import { AerPortDetails } from './aerPortDetails';
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';

export interface AerPort {
  uniqueIdentifier: string;
  imoNumber: string;
  portDetails: AerPortDetails;
  fuelConsumptions?: Array<AerFuelConsumption>;
  directEmissions?: AerPortEmissionsMeasurement;
  totalEmissions: AerPortEmissionsMeasurement;
  surrenderEmissions: AerPortEmissionsMeasurement;
}
