/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerPort } from './aerPort';

export interface AerPortEmissions {
  ports?: Array<AerPort>;
}
