/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerFuelConsumptionSave } from './aerFuelConsumptionSave';
import { AerPortDetails } from './aerPortDetails';
import { AerPortEmissionsMeasurementSave } from './aerPortEmissionsMeasurementSave';

export interface AerPortSave {
  uniqueIdentifier: string;
  imoNumber: string;
  portDetails: AerPortDetails;
  fuelConsumptions?: Array<AerFuelConsumptionSave>;
  directEmissions?: AerPortEmissionsMeasurementSave;
}
