/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerPortVisit } from './aerPortVisit';

export interface AerPortDetails {
  ccu?: string;
  ccs?: string;
  smallIslandFerryReduction?: boolean;
  arrivalTime: string;
  departureTime: string;
  visit: AerPortVisit;
}
