/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerifierComment } from './verifierComment';

export interface AerRecommendedImprovements {
  exist: boolean;
  recommendedImprovements?: Array<VerifierComment>;
}
