/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerInitiatorRequest } from './aerInitiatorRequest';
import { AerTotalReportableEmissions } from './aerTotalReportableEmissions';

export interface AerRequestMetadata {
  type?: string;
  year: number;
  emissions: AerTotalReportableEmissions;
  initiatorRequest: AerInitiatorRequest;
  overallAssessmentType?: 'VERIFIED_AS_SATISFACTORY' | 'VERIFIED_AS_SATISFACTORY_WITH_COMMENTS' | 'NOT_VERIFIED';
  exempted?: boolean;
}
