/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';

export interface AerSaveReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  group:
    | 'OPERATOR_DETAILS'
    | 'MONITORING_PLAN_CHANGES'
    | 'LIST_OF_SHIPS'
    | 'VOYAGES'
    | 'PORTS'
    | 'AGGREGATED_EMISSIONS_DATA'
    | 'ADDITIONAL_DOCUMENTS'
    | 'EMISSIONS_REDUCTION_CLAIM'
    | 'TOTAL_EMISSIONS'
    | 'REPORTING_OBLIGATION_DETAILS'
    | 'VERIFIER_DETAILS'
    | 'OPINION_STATEMENT'
    | 'ETS_COMPLIANCE_RULES'
    | 'COMPLIANCE_MONITORING_REPORTING'
    | 'OVERALL_DECISION'
    | 'UNCORRECTED_MISSTATEMENTS'
    | 'UNCORRECTED_NON_CONFORMITIES'
    | 'UNCORRECTED_NON_COMPLIANCES'
    | 'RECOMMENDED_IMPROVEMENTS'
    | 'EMISSIONS_REDUCTION_CLAIM_VERIFICATION'
    | 'CLOSE_DATA_GAPS_METHODOLOGIES'
    | 'MATERIALITY_LEVEL';
  decision: AerReviewDecision;
  sectionsCompleted?: { [key: string]: string };
}
