/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerDerogations } from './aerDerogations';
import { AerFuelsAndEmissionsFactors } from './aerFuelsAndEmissionsFactors';
import { AerShipDetails } from './aerShipDetails';
import { EmissionsSources } from './emissionsSources';
import { UncertaintyLevel } from './uncertaintyLevel';

export interface AerShipEmissionsSave {
  details: AerShipDetails;
  uniqueIdentifier: string;
  fuelsAndEmissionsFactors: Array<AerFuelsAndEmissionsFactors>;
  emissionsSources: Array<EmissionsSources>;
  uncertaintyLevel: Array<UncertaintyLevel>;
  derogations: AerDerogations;
  dataInputType: 'MANUAL';
}
