/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerSmfPurchase } from './aerSmfPurchase';

export interface AerSmfDetails {
  purchases: Array<AerSmfPurchase>;
  totalSustainableEmissions: string;
}
