/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerComplianceMonitoringReporting } from './aerComplianceMonitoringReporting';
import { AerDataGapsMethodologies } from './aerDataGapsMethodologies';
import { AerEtsComplianceRules } from './aerEtsComplianceRules';
import { AerMaterialityLevel } from './aerMaterialityLevel';
import { AerOpinionStatement } from './aerOpinionStatement';
import { AerRecommendedImprovements } from './aerRecommendedImprovements';
import { AerUncorrectedMisstatements } from './aerUncorrectedMisstatements';
import { AerUncorrectedNonCompliances } from './aerUncorrectedNonCompliances';
import { AerUncorrectedNonConformities } from './aerUncorrectedNonConformities';
import { AerVerificationDecision } from './aerVerificationDecision';
import { AerVerificationTeamDetails } from './aerVerificationTeamDetails';
import { AerVerifierContact } from './aerVerifierContact';

export interface AerSaveApplicationVerificationRequestTaskActionPayload {
  payloadType?: string;
  verifierContact: AerVerifierContact;
  verificationTeamDetails: AerVerificationTeamDetails;
  opinionStatement: AerOpinionStatement;
  uncorrectedNonCompliances: AerUncorrectedNonCompliances;
  uncorrectedMisstatements: AerUncorrectedMisstatements;
  overallDecision: AerVerificationDecision;
  uncorrectedNonConformities: AerUncorrectedNonConformities;
  recommendedImprovements: AerRecommendedImprovements;
  materialityLevel: AerMaterialityLevel;
  etsComplianceRules: AerEtsComplianceRules;
  complianceMonitoringReporting: AerComplianceMonitoringReporting;
  dataGapsMethodologies: AerDataGapsMethodologies;
  verificationSectionsCompleted?: { [key: string]: string };
}
