/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelConsumption } from './aerAggregatedDataFuelConsumption';
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';

export interface AerShipAggregatedData {
  uniqueIdentifier: string;
  imoNumber: string;
  fuelConsumptions?: Array<AerAggregatedDataFuelConsumption>;
  emissionsWithinUKPorts: AerPortEmissionsMeasurement;
  emissionsBetweenUKPorts: AerPortEmissionsMeasurement;
  emissionsBetweenUKAndNIVoyages: AerPortEmissionsMeasurement;
  totalEmissionsFromVoyagesAndPorts: AerPortEmissionsMeasurement;
  lessVoyagesInNorthernIrelandDeduction: AerPortEmissionsMeasurement;
  totalShipEmissions: string;
  surrenderEmissions: string;
  dataInputType: 'MANUAL' | 'EXTERNAL_PROVIDER' | 'FETCH_FROM_EMP';
  fromFetch?: boolean;
}
