/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelConsumption } from './aerAggregatedDataFuelConsumption';
import { AerAggregatedEmissionsMeasurement } from './aerAggregatedEmissionsMeasurement';
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';

export interface AerShipAggregatedData {
  uniqueIdentifier: string;
  imoNumber: string;
  fuelConsumptions?: Array<AerAggregatedDataFuelConsumption>;
  emissionsWithinUKPorts: AerAggregatedEmissionsMeasurement;
  emissionsBetweenUKPorts: AerAggregatedEmissionsMeasurement;
  emissionsBetweenUKAndEEAVoyages: AerAggregatedEmissionsMeasurement;
  totalAggregatedEmissions: AerAggregatedEmissionsMeasurement;
  smallIslandSurrenderReduction?: AerAggregatedEmissionsMeasurement;
  totalEmissionsFromVoyagesAndPorts: AerPortEmissionsMeasurement;
  lessCapturedCo2: AerPortEmissionsMeasurement;
  lessVoyagesNotInScope: AerPortEmissionsMeasurement;
  lessIslandFerryDeduction: AerPortEmissionsMeasurement;
  less5PercentIceClassDeduction?: AerPortEmissionsMeasurement;
  totalShipEmissions: string;
  surrenderEmissions: string;
  fromFetch?: boolean;
}
