/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReportingObligationDetails } from './aerReportingObligationDetails';
import { AerSave } from './aerSave';

export interface AerSaveApplicationAmendRequestTaskActionPayload {
  payloadType?: string;
  reportingRequired?: boolean;
  reportingObligationDetails?: AerReportingObligationDetails;
  aer?: AerSave;
  aerSectionsCompleted?: { [key: string]: string };
}
