/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerSmfPurchaseSave } from './aerSmfPurchaseSave';

export interface AerSmfDetailsSave {
  purchases: Array<AerSmfPurchaseSave>;
}
