/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerAggregatedDataFuelConsumption } from './aerAggregatedDataFuelConsumption';
import { AerPortEmissionsMeasurementSave } from './aerPortEmissionsMeasurementSave';

export interface AerShipAggregatedDataSave {
  uniqueIdentifier: string;
  imoNumber: string;
  fuelConsumptions?: Array<AerAggregatedDataFuelConsumption>;
  emissionsWithinUKPorts?: AerPortEmissionsMeasurementSave;
  emissionsBetweenUKPorts?: AerPortEmissionsMeasurementSave;
  emissionsBetweenUKAndNIVoyages?: AerPortEmissionsMeasurementSave;
  dataInputType: 'MANUAL';
  fromFetch?: boolean;
}
