/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalDocuments } from './additionalDocuments';
import { AerAggregatedDataSave } from './aerAggregatedDataSave';
import { AerEmissions } from './aerEmissions';
import { AerMonitoringPlanChanges } from './aerMonitoringPlanChanges';
import { AerOperatorDetails } from './aerOperatorDetails';
import { AerPortEmissionsSave } from './aerPortEmissionsSave';
import { AerSmfSave } from './aerSmfSave';
import { AerVoyageEmissionsSave } from './aerVoyageEmissionsSave';

export interface AerSave {
  operatorDetails: AerOperatorDetails;
  additionalDocuments: AdditionalDocuments;
  emissions: AerEmissions;
  aerMonitoringPlanChanges: AerMonitoringPlanChanges;
  portEmissions?: AerPortEmissionsSave;
  voyageEmissions?: AerVoyageEmissionsSave;
  aggregatedData: AerAggregatedDataSave;
  smf: AerSmfSave;
}
