/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';

export interface AerTotalEmissions {
  totalEmissions: AerPortEmissionsMeasurement;
  lessCapturedCo2: AerPortEmissionsMeasurement;
  lessVoyagesNotInScope: AerPortEmissionsMeasurement;
  lessAnyERC: AerPortEmissionsMeasurement;
  lessIslandFerryDeduction: AerPortEmissionsMeasurement;
  less5PercentIceClassDeduction: AerPortEmissionsMeasurement;
  totalShipEmissions: string;
  surrenderEmissions: string;
  totalShipEmissionsSummary: string;
  surrenderEmissionsSummary: string;
}
