/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';

export interface AerTotalEmissions {
  totalEmissions: AerPortEmissionsMeasurement;
  lessVoyagesInNorthernIrelandDeduction: AerPortEmissionsMeasurement;
  lessEmissionsReductionClaim: AerPortEmissionsMeasurement;
  totalShipEmissions: string;
  surrenderEmissions: string;
  totalShipEmissionsSummary: string;
  surrenderEmissionsSummary: string;
}
