/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UncorrectedItem } from './uncorrectedItem';

export interface AerUncorrectedNonCompliances {
  exist: boolean;
  uncorrectedNonCompliances?: Array<UncorrectedItem>;
}
