/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerVerificationDecision } from './aerVerificationDecision';

export interface AerVerifiedSatisfactoryWithCommentsDecision extends AerVerificationDecision {
  reasons: Array<string>;
}
