/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerVoyageSave } from './aerVoyageSave';

export interface AerVoyageEmissionsSave {
  voyages?: Array<AerVoyageSave>;
}
