/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerFuelConsumption } from './aerFuelConsumption';
import { AerPortEmissionsMeasurement } from './aerPortEmissionsMeasurement';
import { AerVoyageDetails } from './aerVoyageDetails';

export interface AerVoyage {
  uniqueIdentifier: string;
  imoNumber: string;
  voyageDetails: AerVoyageDetails;
  fuelConsumptions?: Array<AerFuelConsumption>;
  directEmissions?: AerPortEmissionsMeasurement;
  totalEmissions: AerPortEmissionsMeasurement;
  surrenderEmissions: AerPortEmissionsMeasurement;
}
