/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerVerificationDecision {
  type: 'VERIFIED_AS_SATISFACTORY' | 'VERIFIED_AS_SATISFACTORY_WITH_COMMENTS' | 'NOT_VERIFIED';
}
