/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';
import { ReviewDecisionDetails } from './reviewDecisionDetails';

export interface AerVerificationReportDataReviewDecision extends AerReviewDecision {
  type: 'ACCEPTED';
  details?: ReviewDecisionDetails;
}
