/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerFuelConsumptionSave } from './aerFuelConsumptionSave';
import { AerPortEmissionsMeasurementSave } from './aerPortEmissionsMeasurementSave';
import { AerVoyageDetails } from './aerVoyageDetails';

export interface AerVoyageSave {
  uniqueIdentifier: string;
  imoNumber: string;
  voyageDetails: AerVoyageDetails;
  fuelConsumptions?: Array<AerFuelConsumptionSave>;
  directEmissions?: AerPortEmissionsMeasurementSave;
}
