/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AerVerificationTeamDetails {
  leadEtsAuditor: string;
  etsAuditors: string;
  etsTechnicalExperts: string;
  independentReviewer: string;
  technicalExperts: string;
  authorisedSignatoryName: string;
}
