/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerSiteVisit } from './aerSiteVisit';

export interface AerVirtualSiteVisit extends AerSiteVisit {
  reason: string;
}
