/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CaExternalContactDTO {
  id?: number;
  name?: string;
  email?: string;
  description?: string;
  lastUpdatedDate?: string;
}
