/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The ca external information
 */
export interface CaExternalContactRegistrationDTO {
  name: string;
  email: string;
  description: string;
}
