/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CardPaymentStateDTO } from './cardPaymentStateDTO';

export interface CardPaymentProcessResponseDTO {
  paymentId?: string;
  state?: CardPaymentStateDTO;
  nextUrl?: string;
}
