/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The parameters based on which the report will be generated
 */
export interface CustomMiReportQuery {
  sqlQuery: string;
}
