/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoeDeterminationReason } from './doeDeterminationReason';
import { DoeFeeDetails } from './doeFeeDetails';
import { DoeTotalMaritimeEmissions } from './doeTotalMaritimeEmissions';

export interface DoeMaritimeEmissions {
  determinationReason: DoeDeterminationReason;
  totalMaritimeEmissions: DoeTotalMaritimeEmissions;
  chargeOperator: boolean;
  feeDetails?: DoeFeeDetails;
}
