/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerTotalReportableEmissions } from './aerTotalReportableEmissions';

export interface DoeRequestMetadata {
  type?: string;
  year: number;
  emissions: AerTotalReportableEmissions;
  exempted?: boolean;
}
