/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Doe } from './doe';

export interface DoeSaveApplicationRequestTaskActionPayload {
  payloadType?: string;
  doe?: Doe;
  sectionsCompleted?: { [key: string]: string };
}
