/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DoeTotalMaritimeEmissions {
  determinationType: 'MARITIME_EMISSIONS' | 'SURRENDER_OBLIGATION';
  totalReportableEmissions: string;
  smallIslandFerryDeduction: string;
  iceClassDeduction: string;
  surrenderEmissions: string;
  calculationApproach: string;
  supportingDocuments?: Array<string>;
}
