/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FuelOriginTypeName } from './fuelOriginTypeName';

export interface EmissionsSources {
  name: string;
  type:
    | 'MAIN_ENGINE'
    | 'AUX_ENGINE'
    | 'GAS_TURBINE'
    | 'BOILER'
    | 'INERT_GAS_GENERATOR'
    | 'FUEL_CELLS'
    | 'WASTE_INCINERATOR'
    | 'OTHER';
  sourceClass:
    | 'BOILERS'
    | 'FUEL_CELLS'
    | 'GAS_TURBINE'
    | 'ICE'
    | 'INERT_GAS_GENERATOR'
    | 'LNG_DIESEL_DFSS'
    | 'LNG_LBSI'
    | 'LNG_OTTO_DFMS'
    | 'LNG_OTTO_DFSS'
    | 'WASTE_INCINERATORS';
  fuelDetails: Array<FuelOriginTypeName>;
  monitoringMethod: Array<'BDN' | 'BUNKER_TANK' | 'FLOW_METERS' | 'DIRECT'>;
  uniqueIdentifier: string;
}
