/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalDocuments } from './additionalDocuments';
import { EmpAbbreviations } from './empAbbreviations';
import { EmpControlActivities } from './empControlActivities';
import { EmpDataGaps } from './empDataGaps';
import { EmpEmissions } from './empEmissions';
import { EmpEmissionSources } from './empEmissionSources';
import { EmpManagementProcedures } from './empManagementProcedures';
import { EmpMonitoringGreenhouseGas } from './empMonitoringGreenhouseGas';
import { EmpOperatorDetails } from './empOperatorDetails';

export interface EmissionsMonitoringPlan {
  abbreviations: EmpAbbreviations;
  additionalDocuments: AdditionalDocuments;
  controlActivities: EmpControlActivities;
  operatorDetails: EmpOperatorDetails;
  managementProcedures: EmpManagementProcedures;
  dataGaps: EmpDataGaps;
  emissions: EmpEmissions;
  sources: EmpEmissionSources;
  greenhouseGas: EmpMonitoringGreenhouseGas;
}
