/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationDetailsOfChange } from './empNotificationDetailsOfChange';

export interface EmissionsMonitoringPlanNotification {
  detailsOfChange: EmpNotificationDetailsOfChange;
}
