/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpAbbreviationDefinition } from './empAbbreviationDefinition';

export interface EmpAbbreviations {
  exist?: boolean;
  abbreviationDefinitions?: Array<EmpAbbreviationDefinition>;
}
