/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestDetailsDTO } from './requestDetailsDTO';

export interface EmpBatchReissuesResponseDTO {
  requestDetails?: Array<RequestDetailsDTO>;
  total?: number;
  canInitiateBatchReissue?: boolean;
}
