/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpOutsourcedActivities } from './empOutsourcedActivities';
import { EmpProcedureForm } from './empProcedureForm';

export interface EmpControlActivities {
  qualityAssurance: EmpProcedureForm;
  internalReviews: EmpProcedureForm;
  corrections: EmpProcedureForm;
  outsourcedActivities: EmpOutsourcedActivities;
  documentation: EmpProcedureForm;
}
