/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpCarbonCaptureTechnologies } from './empCarbonCaptureTechnologies';

export interface EmpCarbonCapture {
  exist: boolean;
  technologies?: EmpCarbonCaptureTechnologies;
}
