/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';

export interface EmpDetailsDTO {
  id?: string;
  empAttachments?: { [key: string]: string };
  fileDocument?: FileInfoDTO;
}
