/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpDataGaps {
  formulaeUsed?: string;
  fuelConsumptionEstimationMethod: string;
  responsiblePersonOrPosition: string;
  dataSources: string;
  recordsLocation: string;
  itSystemUsed?: string;
}
