/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpEmissionCompliance } from './empEmissionCompliance';
import { EmpEmissionFactors } from './empEmissionFactors';
import { EmpProcedureForm } from './empProcedureForm';

export interface EmpEmissionSources {
  listCompletion: EmpProcedureForm;
  emissionFactors: EmpEmissionFactors;
  emissionCompliance?: EmpEmissionCompliance;
}
