/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpFuelsAndEmissionsFactors {
  origin: 'FOSSIL' | 'BIOFUEL' | 'RFNBO';
  name?: string;
  carbonDioxide: string;
  methane: string;
  nitrousOxide: string;
  sustainableFraction?: string;
  uniqueIdentifier: string;
  densityMethodBunker: 'ON_BOARD_MEASUREMENT_SYSTEMS' | 'FUEL_SUPPLIER' | 'LABORATORY_TEST' | 'NA';
  densityMethodTank: 'MEASUREMENT_SYSTEMS' | 'FUEL_SUPPLIER' | 'LABORATORY_TEST' | 'NA';
}
