/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmpIssuanceDetermination } from './empIssuanceDetermination';
import { EmpIssuanceReviewDecision } from './empIssuanceReviewDecision';

export interface EmpIssuanceApplicationReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  emissionsMonitoringPlan?: EmissionsMonitoringPlan;
  empSectionsCompleted?: { [key: string]: string };
  empAttachments?: { [key: string]: string };
  determination?: EmpIssuanceDetermination;
  accountOpeningEventSentToRegistry?: boolean;
  reviewGroupDecisions?: { [key: string]: EmpIssuanceReviewDecision };
  reviewAttachments?: { [key: string]: string };
  rfiAttachments?: { [key: string]: string };
}
