/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpIssuanceReviewDecision } from './empIssuanceReviewDecision';

export interface EmpIssuanceApplicationReturnedForAmendsRequestActionPayload {
  payloadType?: string;
  reviewGroupDecisions: { [key: string]: EmpIssuanceReviewDecision };
  reviewAttachments?: { [key: string]: string };
}
