/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpIssuanceDetermination } from './empIssuanceDetermination';

export interface EmpIssuanceSaveReviewDeterminationRequestTaskActionPayload {
  payloadType?: string;
  determination: EmpIssuanceDetermination;
  empSectionsCompleted?: { [key: string]: string };
}
