/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmpIssuanceDetermination } from './empIssuanceDetermination';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpIssuanceApplicationDeemedWithdrawnRequestActionPayload {
  payloadType?: string;
  decisionNotification: DecisionNotification;
  determination: EmpIssuanceDetermination;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
}
