/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationStructure } from './organisationStructure';

export interface EmpIssuanceSendRegistryAccountOpeningEventRequestActionPayload {
  payloadType?: string;
  businessId: string;
  imoNumber: string;
  name: string;
  firstMaritimeActivityDate: string;
  competentAuthority: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  organisationStructure: OrganisationStructure;
}
