/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDecisionDetails } from './reviewDecisionDetails';

export interface EmpIssuanceReviewDecision {
  details?: ReviewDecisionDetails;
  type: 'ACCEPTED' | 'OPERATOR_AMENDS_NEEDED';
}
