/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';

export interface EmpIssuanceSaveApplicationReviewRequestTaskActionPayload {
  payloadType?: string;
  emissionsMonitoringPlan: EmissionsMonitoringPlan;
  empSectionsCompleted?: { [key: string]: string };
}
