/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpMonitoringReportingRole } from './empMonitoringReportingRole';
import { EmpProcedureForm } from './empProcedureForm';
import { EmpProcedureFormWithFiles } from './empProcedureFormWithFiles';

export interface EmpManagementProcedures {
  monitoringReportingRoles: Array<EmpMonitoringReportingRole>;
  regularCheckOfAdequacy: EmpProcedureForm;
  dataFlowActivities: EmpProcedureFormWithFiles;
  riskAssessmentProcedures: EmpProcedureFormWithFiles;
}
