/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpRegisteredOwner } from './empRegisteredOwner';

export interface EmpMandate {
  exist: boolean;
  registeredOwners?: Array<EmpRegisteredOwner>;
  responsibilityDeclaration: boolean;
}
