/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpProcedureForm } from './empProcedureForm';

export interface EmpMonitoringGreenhouseGas {
  fuel: EmpProcedureForm;
  crossChecks: EmpProcedureForm;
  information: EmpProcedureForm;
  qaEquipment: EmpProcedureForm;
  voyages: EmpProcedureForm;
}
