/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationFollowUpReviewDecision } from './empNotificationFollowUpReviewDecision';

export interface EmpNotificationFollowUpSaveReviewDecisionRequestTaskActionPayload {
  payloadType?: string;
  reviewDecision: EmpNotificationFollowUpReviewDecision;
  sectionsCompleted?: { [key: string]: string };
}
