/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationFollowUpReviewDecision } from './empNotificationFollowUpReviewDecision';

export interface EmpNotificationFollowUpWaitForAmendsRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  followUpRequest: string;
  followUpResponse: string;
  followUpFiles?: Array<string>;
  reviewDecision: EmpNotificationFollowUpReviewDecision;
  followUpResponseExpirationDate: string;
  followUpResponseAttachments?: { [key: string]: string };
}
