/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmpNotificationFollowUpReviewDecision } from './empNotificationFollowUpReviewDecision';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpNotificationFollowUpApplicationReviewSubmittedDecisionRequestActionPayload {
  payloadType?: string;
  request: string;
  responseExpirationDate: string;
  response: string;
  responseFiles?: Array<string>;
  responseAttachments?: { [key: string]: string };
  responseSubmissionDate: string;
  sectionsCompleted?: { [key: string]: string };
  reviewDecision: EmpNotificationFollowUpReviewDecision;
  reviewDecisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
}
