/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanNotification } from './emissionsMonitoringPlanNotification';

export interface EmpNotificationApplicationSaveRequestTaskActionPayload {
  payloadType?: string;
  emissionsMonitoringPlanNotification: EmissionsMonitoringPlanNotification;
  sectionsCompleted?: { [key: string]: string };
}
