/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FollowUp } from './followUp';

export interface EmpNotificationAcceptedDecisionDetails {
  notes?: string;
  officialNotice: string;
  followUp: FollowUp;
}
