/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpNotificationWaitForFollowUpRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  followUpRequest?: string;
  followUpResponseExpirationDate?: string;
}
