/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpNotificationFollowUpResponseSubmittedRequestActionPayload {
  payloadType?: string;
  request: string;
  response: string;
  responseFiles?: Array<string>;
  responseAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
