/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDecisionRequiredChange } from './reviewDecisionRequiredChange';

export interface EmpNotificationFollowupRequiredChangesDecisionDetails {
  notes?: string;
  requiredChanges: Array<ReviewDecisionRequiredChange>;
  dueDate?: string;
}
