/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationFollowupRequiredChangesDecisionDetails } from './empNotificationFollowupRequiredChangesDecisionDetails';

export interface EmpNotificationFollowUpReturnedForAmendsRequestActionPayload {
  payloadType?: string;
  decisionDetails: EmpNotificationFollowupRequiredChangesDecisionDetails;
  amendAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
