/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationReviewDecision } from './empNotificationReviewDecision';

export interface EmpNotificationSaveReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  reviewDecision: EmpNotificationReviewDecision;
  sectionsCompleted?: { [key: string]: string };
}
