/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpNotificationFollowUpReviewDecision } from './empNotificationFollowUpReviewDecision';

export interface EmpNotificationFollowUpApplicationReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  followUpRequest?: string;
  followUpResponseExpirationDate?: string;
  followUpResponse: string;
  followUpFiles?: Array<string>;
  followUpAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
  submissionDate: string;
  reviewDecision: EmpNotificationFollowUpReviewDecision;
}
