/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmpNotificationReviewDecision } from './empNotificationReviewDecision';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpNotificationApplicationReviewSubmittedDecisionRequestActionPayload {
  payloadType?: string;
  reviewDecision: EmpNotificationReviewDecision;
  reviewDecisionNotification: DecisionNotification;
  sectionsCompleted?: { [key: string]: string };
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
}
