/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpNotificationFollowUpRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  followUpRequest?: string;
  followUpResponseExpirationDate?: string;
  followUpResponse: string;
  followUpFiles?: Array<string>;
  followUpAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
