/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanNotification } from './emissionsMonitoringPlanNotification';
import { EmpNotificationReviewDecision } from './empNotificationReviewDecision';

export interface EmpNotificationApplicationReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  emissionsMonitoringPlanNotification: EmissionsMonitoringPlanNotification;
  empNotificationAttachments?: { [key: string]: string };
  reviewDecision: EmpNotificationReviewDecision;
  rfiAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
