/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpNotificationFollowUpSaveApplicationAmendRequestTaskActionPayload {
  payloadType?: string;
  response: string;
  files?: Array<string>;
  sectionsCompleted?: { [key: string]: string };
}
