/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStateDTO } from './addressStateDTO';
import { OrganisationStructure } from './organisationStructure';

export interface EmpOperatorDetails {
  operatorName: string;
  imoNumber: string;
  contactAddress: AddressStateDTO;
  organisationStructure: OrganisationStructure;
  activityDescription: string;
}
