/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpOperatorDetails } from './empOperatorDetails';

export interface EmpOriginatedData {
  operatorDetails?: EmpOperatorDetails;
  operatorDetailsAttachments?: { [key: string]: string };
}
