/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpProcedureFormWithFiles {
  reference: string;
  version?: string;
  description: string;
  responsiblePersonOrPosition: string;
  recordsLocation: string;
  itSystemUsed?: string;
  files?: Array<string>;
}
