/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisteredOwnerShipDetails } from './registeredOwnerShipDetails';

export interface EmpRegisteredOwner {
  uniqueIdentifier: string;
  name: string;
  imoNumber: string;
  contactName: string;
  email: string;
  effectiveDate: string;
  ships: Array<RegisteredOwnerShipDetails>;
}
