/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpCarbonCapture } from './empCarbonCapture';
import { EmpEmissionsSources } from './empEmissionsSources';
import { EmpFuelsAndEmissionsFactors } from './empFuelsAndEmissionsFactors';
import { ExemptionConditions } from './exemptionConditions';
import { MeasurementDescription } from './measurementDescription';
import { ShipDetails } from './shipDetails';
import { UncertaintyLevel } from './uncertaintyLevel';

export interface EmpShipEmissions {
  details: ShipDetails;
  uniqueIdentifier: string;
  fuelsAndEmissionsFactors: Array<EmpFuelsAndEmissionsFactors>;
  emissionsSources: Array<EmpEmissionsSources>;
  uncertaintyLevel: Array<UncertaintyLevel>;
  carbonCapture: EmpCarbonCapture;
  measurements: Array<MeasurementDescription>;
  exemptionConditions: ExemptionConditions;
}
