/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmpVariationDetails } from './empVariationDetails';

export interface EmpVariationSaveApplicationRequestTaskActionPayload {
  payloadType?: string;
  emissionsMonitoringPlan?: EmissionsMonitoringPlan;
  empVariationDetails?: EmpVariationDetails;
  empVariationDetailsCompleted?: string;
  empSectionsCompleted?: { [key: string]: string };
  updatedSubtasks?: Array<
    | 'MARITIME_OPERATOR_DETAILS'
    | 'SHIPS_CALCULATION_EMISSIONS'
    | 'MONITORING_APPROACH'
    | 'EMISSION_SOURCES'
    | 'MANAGEMENT_PROCEDURES'
    | 'ABBREVIATIONS_AND_DEFINITIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'CONTROL_ACTIVITIES'
  >;
}
