/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmissionsMonitoringPlanContainer } from './emissionsMonitoringPlanContainer';
import { EmpAcceptedVariationDecisionDetails } from './empAcceptedVariationDecisionDetails';
import { EmpVariationDetails } from './empVariationDetails';
import { EmpVariationRegulatorLedReason } from './empVariationRegulatorLedReason';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpVariationApplicationRegulatorLedApprovedRequestActionPayload {
  payloadType?: string;
  emissionsMonitoringPlan: EmissionsMonitoringPlan;
  empVariationDetails: EmpVariationDetails;
  empSectionsCompleted?: { [key: string]: string };
  empAttachments?: { [key: string]: string };
  originalEmpContainer: EmissionsMonitoringPlanContainer;
  reviewGroupDecisions?: { [key: string]: EmpAcceptedVariationDecisionDetails };
  reasonRegulatorLed: EmpVariationRegulatorLedReason;
  decisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
  empDocument: FileInfoDTO;
}
