/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpVariationRegulatorLedReason {
  type: 'FOLLOWING_IMPROVING_REPORT' | 'FAILED_TO_COMPLY_OR_APPLY' | 'OTHER';
  reasonOtherSummary?: string;
  summary: string;
}
