/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmissionsMonitoringPlanContainer } from './emissionsMonitoringPlanContainer';
import { EmpVariationDetails } from './empVariationDetails';
import { EmpVariationDetermination } from './empVariationDetermination';
import { EmpVariationReviewDecision } from './empVariationReviewDecision';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpVariationApplicationApprovedRequestActionPayload {
  payloadType?: string;
  emissionsMonitoringPlan: EmissionsMonitoringPlan;
  empVariationDetails: EmpVariationDetails;
  empSectionsCompleted?: { [key: string]: string };
  empAttachments?: { [key: string]: string };
  originalEmpContainer: EmissionsMonitoringPlanContainer;
  empVariationDetailsReviewDecision?: EmpVariationReviewDecision;
  reviewGroupDecisions?: { [key: string]: EmpVariationReviewDecision };
  reviewAttachments?: { [key: string]: string };
  determination: EmpVariationDetermination;
  decisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
  empDocument: FileInfoDTO;
}
