/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpVariationDetails {
  reason: string;
  changes: Array<
    | 'ADD_NEW_SHIP'
    | 'ADD_NEW_FUELS_OR_EMISSION_SOURCES'
    | 'CHANGE_MONITORING_METHOD'
    | 'CHANGE_EMISSION_FACTOR_VALUES'
    | 'CHANGE_EMP_HOLDER_NAME_OR_ADDRESS'
    | 'USE_OF_EXEMPTION'
    | 'USE_OF_CARBON'
    | 'UPDATE_DELEGATED_RESPONSIBILITY'
    | 'OTHER_SIGNIFICANT'
    | 'REMOVING_SHIP'
    | 'UPDATE_PROCEDURES'
    | 'OTHER_NON_SIGNIFICANT'
  >;
  otherSignificantChangeReason?: string;
  otherNonSignificantChangeReason?: string;
}
