/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmpVariationDetails } from './empVariationDetails';

export interface EmpVariationSaveApplicationReviewRequestTaskActionPayload {
  payloadType?: string;
  emissionsMonitoringPlan?: EmissionsMonitoringPlan;
  empVariationDetails?: EmpVariationDetails;
  empVariationDetailsCompleted?: string;
  empVariationDetailsReviewCompleted?: string;
  empSectionsCompleted?: { [key: string]: string };
}
