/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpVariationDetermination {
  type: 'APPROVED' | 'REJECTED' | 'DEEMED_WITHDRAWN';
  reason?: string;
  summary?: string;
}
