/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpVariationReviewDecision } from './empVariationReviewDecision';

export interface EmpVariationSaveDetailsReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  empVariationDetailsCompleted?: string;
  empVariationDetailsReviewCompleted?: string;
  decision: EmpVariationReviewDecision;
}
