/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpVariationReviewDecision } from './empVariationReviewDecision';

export interface EmpVariationSaveReviewGroupDecisionRequestTaskActionPayload {
  payloadType?: string;
  group:
    | 'MARITIME_OPERATOR_DETAILS'
    | 'SHIPS_CALCULATION_EMISSIONS'
    | 'MONITORING_APPROACH'
    | 'EMISSION_SOURCES'
    | 'MANAGEMENT_PROCEDURES'
    | 'ABBREVIATIONS_AND_DEFINITIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'CONTROL_ACTIVITIES';
  decision: EmpVariationReviewDecision;
  empSectionsCompleted?: { [key: string]: string };
}
