/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmissionsMonitoringPlanContainer } from './emissionsMonitoringPlanContainer';
import { EmpVariationDetails } from './empVariationDetails';
import { EmpVariationDetermination } from './empVariationDetermination';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface EmpVariationApplicationRejectedRequestActionPayload {
  payloadType?: string;
  originalEmpContainer: EmissionsMonitoringPlanContainer;
  emissionsMonitoringPlan: EmissionsMonitoringPlan;
  empVariationDetails: EmpVariationDetails;
  empAttachments?: { [key: string]: string };
  determination: EmpVariationDetermination;
  decisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
}
