/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ExecutedRequestAction {
  Account_ID?: string;
  Account_name?: string;
  Account_status?: string;
  Workflow_ID?: string;
  Workflow_type?: string;
  Workflow_status?: string;
  Timeline_event_type?: string;
  Timeline_event_Completed_by?: string;
  Timeline_event_Date_Completed?: string;
}
