/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutedRequestAction } from './executedRequestAction';

export interface ExecutedRequestActionsMiReportResult {
  reportType: string;
  columnNames: Array<string>;
  results?: Array<ExecutedRequestAction>;
}
