/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FuelOriginTypeName {
  origin: 'FOSSIL' | 'BIOFUEL' | 'RFNBO';
  name?: string;
  uniqueIdentifier: string;
  methaneSlip?: string;
  methaneSlipValueType?: 'PRESELECTED' | 'OTHER';
}
