/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorUserDTO } from './operatorUserDTO';
import { RegulatorCurrentUserDTO } from './regulatorCurrentUserDTO';
import { UserDTO } from './userDTO';
import { VerifierUserDTO } from './verifierUserDTO';

/**
 * @type GetCurrentUser200Response
 * @export
 */
export type GetCurrentUser200Response = OperatorUserDTO | RegulatorCurrentUserDTO | UserDTO | VerifierUserDTO;
