/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileNameAndUuid } from './fileNameAndUuid';

export interface GuidanceDocumentDTO {
  id?: number;
  title?: string;
  fileNameAndUuid?: FileNameAndUuid;
  displayOrderNo?: number;
  guidanceSectionId?: number;
  guidanceSectionName?: string;
  createdOn?: string;
  lastUpdatedOn?: string;
  createdBy?: string;
  lastUpdatedBy?: string;
}
