/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuidanceDocumentDTO } from './guidanceDocumentDTO';

export interface GuidanceSectionDTO {
  id?: number;
  name?: string;
  displayOrderNo?: number;
  guidanceDocuments?: Array<GuidanceDocumentDTO>;
  createdOn?: string;
  lastUpdatedOn?: string;
  createdBy?: string;
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  lastUpdatedBy?: string;
}
