/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuidanceSectionDTO } from './guidanceSectionDTO';

export interface GuidanceSectionsResponseDTO {
  guidanceSections?: { [key: string]: Array<GuidanceSectionDTO> };
  editable?: boolean;
}
