/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The operator user credentials
 */
export interface InvitedUserCredentialsDTO {
  invitationToken: string;
  password: string;
}
