/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDTO } from './itemDTO';

export interface ItemDTOResponse {
  items?: Array<ItemDTO>;
  totalItems?: number;
}
