/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ItemSearchCriteriaDTO {
  orderBy?: 'NEWEST_FIRST' | 'OLDEST_FIRST' | 'NEAREST_DUE_DATE';
  requestType?: string;
  searchTerm?: string;
}
