/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationStructure } from './organisationStructure';

export interface LimitedCompanyOrganisation extends OrganisationStructure {
  registrationNumber: string;
  evidenceFiles?: Array<string>;
}
