/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaritimeVerificationBodyUser } from './maritimeVerificationBodyUser';

export interface MaritimeVerificationBodyUsersMiReportResult {
  reportType: string;
  columnNames: Array<string>;
  results?: Array<MaritimeVerificationBodyUser>;
}
