/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MaritimeVerificationBodyUser {
  userId?: string;
  Verification_body_name?: string;
  Account_status?: string;
  Accreditation_reference_number?: string;
  User_role?: string;
  User_status?: string;
}
