/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MeasurementDescription {
  name: string;
  technicalDescription?: string;
  emissionSources: Array<string>;
}
