/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpDetailsDTO } from './empDetailsDTO';
import { MrtmAccountViewDTO } from './mrtmAccountViewDTO';

export interface MrtmAccountEmpDTO {
  account?: MrtmAccountViewDTO;
  emp?: EmpDetailsDTO;
}
