/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The maritime account creation dto
 */
export interface MrtmAccountDTO {
  imoNumber: string;
  name: string;
  line1: string;
  line2?: string;
  city: string;
  country: string;
  postcode?: string;
  state?: string;
  firstMaritimeActivityDate: string;
}
