/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStateDTO } from './addressStateDTO';

export interface MrtmAccountViewDTO {
  imoNumber: string;
  name: string;
  line1: string;
  line2?: string;
  city: string;
  country: string;
  postcode?: string;
  state?: string;
  firstMaritimeActivityDate: string;
  id?: number;
  status?: 'NEW' | 'LIVE' | 'CLOSED' | 'WITHDRAWN';
  sopId?: number;
  registryId?: number;
  registeredAddress?: AddressStateDTO;
  businessId?: string;
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
}
