/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceCloseJustification } from './nonComplianceCloseJustification';

export interface NonComplianceFinalDeterminationRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  complianceRestored: 'YES' | 'NO' | 'NOT_APPLICABLE';
  complianceRestoredDate?: string;
  comments: string;
  reissuePenalty: boolean;
  operatorPaid: boolean;
  operatorPaidDate?: string;
  closeJustification?: NonComplianceCloseJustification;
  nonComplianceAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
