/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NonComplianceCivilPenaltySaveApplicationRequestTaskActionPayload {
  payloadType?: string;
  civilPenalty: string;
  penaltyAmount: string;
  dueDate?: string;
  comments?: string;
  sectionsCompleted?: { [key: string]: string };
}
