/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceCloseJustification } from './nonComplianceCloseJustification';

export interface NonComplianceInitialPenaltyNoticeRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  issueNoticeOfIntent: boolean;
  initialPenaltyNotice: string;
  comments?: string;
  closeJustification?: NonComplianceCloseJustification;
  nonComplianceAttachments?: { [key: string]: string };
  sectionsCompleted?: { [key: string]: string };
}
