/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NonComplianceFinalDetermination {
  complianceRestored: 'YES' | 'NO' | 'NOT_APPLICABLE';
  complianceRestoredDate?: string;
  comments: string;
  reissuePenalty: boolean;
  operatorPaid: boolean;
  operatorPaidDate?: string;
}
