/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface NonComplianceInitialPenaltyNoticeApplicationSubmittedRequestActionPayload {
  payloadType?: string;
  initialPenaltyNotice: string;
  comments?: string;
  operators?: Array<string>;
  externalContacts?: Array<number>;
  nonComplianceAttachments?: { [key: string]: string };
  usersInfo?: { [key: string]: RequestActionUserInfo };
  sectionsCompleted?: { [key: string]: string };
}
