/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NotificationTemplateInfoDTO {
  id?: number;
  name?: string;
  roleType?: string;
  workflow?: string;
  lastUpdatedDate?: string;
}
