/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTemplateInfoDTO } from './documentTemplateInfoDTO';

export interface NotificationTemplateDTO {
  id?: number;
  name?: string;
  subject?: string;
  text?: string;
  eventTrigger?: string;
  workflow?: string;
  lastUpdatedDate?: string;
  documentTemplates?: Array<DocumentTemplateInfoDTO>;
}
