/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationTemplateInfoDTO } from './notificationTemplateInfoDTO';

export interface NotificationTemplateSearchResults {
  templates?: Array<NotificationTemplateInfoDTO>;
  total?: number;
}
