/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The data to update the notification template
 */
export interface NotificationTemplateUpdateDTO {
  subject: string;
  text: string;
}
