/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneNumberDTO } from './phoneNumberDTO';

export interface OperatorUserDTO {
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber?: PhoneNumberDTO;
  mobileNumber?: PhoneNumberDTO;
}
