/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The operator user account registration info
 */
export interface OperatorUserInvitationDTO {
  email: string;
  firstName: string;
  lastName: string;
  roleCode?: string;
}
