/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStateDTO } from './addressStateDTO';

export interface OrganisationStructure {
  legalStatusType: 'LIMITED_COMPANY' | 'INDIVIDUAL' | 'PARTNERSHIP';
  registeredAddress: AddressStateDTO;
  sameAsContactAddress?: boolean;
}
