/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OutstandingRequestTask {
  requestTaskAssignee?: string;
  Account_ID?: string;
  Account_name?: string;
  Workflow_ID?: string;
  Workflow_type?: string;
  Workflow_task_name?: string;
  Workflow_task_assignee?: string;
  Workflow_task_due_date?: string;
  Workflow_task_days_remaining?: number;
}
