/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutstandingRequestTask } from './outstandingRequestTask';

export interface OutstandingRequestTasksMiReportResult {
  reportType: string;
  columnNames: Array<string>;
  results?: Array<OutstandingRequestTask>;
}
