/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PasswordValidationErrorDTO } from './passwordValidationErrorDTO';

export interface PasswordValidationResponseDTO {
  valid?: boolean;
  errors?: Array<PasswordValidationErrorDTO>;
}
