/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountDetailsDTO } from './bankAccountDetailsDTO';

export interface PaymentMakeRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  amount?: string;
  paymentRefNum?: string;
  creationDate?: string;
  paymentMethodTypes?: Array<'BANK_TRANSFER' | 'CREDIT_OR_DEBIT_CARD'>;
  bankAccountDetails?: BankAccountDetailsDTO;
  externalPaymentId?: string;
}
