/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaymentCancelledRequestActionPayload {
  payloadType?: string;
  status?: 'MARK_AS_PAID' | 'MARK_AS_RECEIVED' | 'COMPLETED' | 'CANCELLED';
  cancellationReason?: string;
}
