/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeerReviewDecision } from './peerReviewDecision';

export interface PeerReviewDecisionSubmittedRequestActionPayload {
  payloadType?: string;
  decision: PeerReviewDecision;
}
