/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';

/**
 * The request to preview the document
 */
export interface PreviewDocumentRequest {
  documentType: string;
  decisionNotification: DecisionNotification;
}
