/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RdeForceDecisionPayload {
  decision: 'ACCEPTED' | 'REJECTED';
  evidence: string;
  files?: Array<string>;
}
