/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdeForceDecisionPayload } from './rdeForceDecisionPayload';
import { RdeResponsePayload } from './rdeResponsePayload';

export interface RdeForceDecisionRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  rdeResponsePayload: RdeResponsePayload;
  rdeForceDecisionPayload: RdeForceDecisionPayload;
  rdeAttachments?: { [key: string]: string };
}
