/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdeForceDecisionPayload } from './rdeForceDecisionPayload';

export interface RdeForceDecisionRequestTaskActionPayload {
  payloadType?: string;
  rdeForceDecisionPayload: RdeForceDecisionPayload;
}
