/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RdePayload {
  extensionDate: string;
  deadline: string;
  operators?: Array<string>;
  signatory: string;
}
