/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdeResponsePayload } from './rdeResponsePayload';

export interface RdeResponseRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  rdeResponsePayload: RdeResponsePayload;
}
