/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdeDecisionPayload } from './rdeDecisionPayload';

export interface RdeResponseSubmitRequestTaskActionPayload {
  payloadType?: string;
  rdeDecisionPayload: RdeDecisionPayload;
}
