/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { RdePayload } from './rdePayload';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface RdeSubmittedRequestActionPayload {
  payloadType?: string;
  rdePayload: RdePayload;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialDocument: FileInfoDTO;
}
