/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RdePayload } from './rdePayload';

export interface RdeSubmitRequestTaskActionPayload {
  payloadType?: string;
  rdePayload: RdePayload;
}
