/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegistryUpdatedEmissionsEventSubmittedRequestActionPayload {
  payloadType?: string;
  registryId?: number;
  reportableEmissions?: number;
  reportingYear?: number;
}
