/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';

export interface RegistryRegulatorNoticeEventSubmittedRequestActionPayload {
  payloadType?: string;
  registryId: number;
  type: 'ACCOUNT_CLOSED' | 'EMP_WITHDRAWN';
  officialNotice?: FileInfoDTO;
}
