/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegulatorImprovementResponse } from './regulatorImprovementResponse';

export interface RegulatorReviewResponse {
  regulatorImprovementResponses: { [key: string]: RegulatorImprovementResponse };
  reportSummary: string;
}
