/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegulatorUserDTO } from './regulatorUserDTO';

export interface RegulatorUserUpdateDTO {
  user: RegulatorUserDTO;
  permissions: { [key: string]: 'NONE' | 'VIEW_ONLY' | 'EXECUTE' };
}
