/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegulatorUserAuthorityInfoDTO } from './regulatorUserAuthorityInfoDTO';

export interface RegulatorUsersAuthoritiesInfoDTO {
  caUsers?: Array<RegulatorUserAuthorityInfoDTO>;
  editable?: boolean;
}
