/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The search criteria
 */
export interface RequestSearchCriteria {
  resourceType: string;
  resourceId: string;
  requestTypes?: Array<string>;
  requestStatuses?: Array<string>;
  historyCategory: string;
  pageNumber: number;
  pageSize: number;
}
