/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestNoteDto } from './requestNoteDto';

export interface RequestNoteResponse {
  requestNotes?: Array<RequestNoteDto>;
  totalItems?: number;
}
