/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestInfoDTO } from './requestInfoDTO';
import { RequestTaskDTO } from './requestTaskDTO';

export interface RequestTaskItemDTO {
  requestTask?: RequestTaskDTO;
  allowedRequestTaskActions?: Array<string>;
  userAssignCapable?: boolean;
  requestInfo?: RequestInfoDTO;
}
