/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTaskActionPayload } from './requestTaskActionPayload';

/**
 * The request task action body
 */
export interface RequestTaskActionProcessDTO {
  requestTaskActionType: string;
  requestTaskActionPayload: RequestTaskActionPayload;
  requestTaskId: number;
}
