/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestDetailsDTO {
  id?: string;
  requestType?: string;
  requestStatus?: string;
  creationDate?: string;
  requestMetadata?: RequestMetadata;
}
