/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestActionUserInfo {
  name: string;
  roleCode?: string;
  contactTypes?: Array<string>;
}
