/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTaskPayload } from './requestTaskPayload';

export interface RequestTaskDTO {
  id?: number;
  type?: string;
  payload?: RequestTaskPayload;
  assignable?: boolean;
  assigneeUserId?: string;
  assigneeFullName?: string;
  daysRemaining?: number;
  startDate?: string;
}
