/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestInfoDTO {
  id?: string;
  type?: string;
  resourceType?: string;
  requestMetadata?: RequestMetadata;
  paymentCompleted?: boolean;
  paymentAmount?: string;
  creationDate?: string;
  resources?: { [key: string]: string };
}
