/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestActionPayload } from './requestActionPayload';

export interface RequestActionDTO {
  id?: number;
  type?: string;
  payload?: RequestActionPayload;
  requestId?: string;
  requestType?: string;
  requestAccountId?: number;
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  submitter?: string;
  creationDate?: string;
}
