/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The new password
 */
export interface ResetPasswordDTO {
  token: string;
  otp: string;
  password: string;
}
