/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RfiQuestionPayload } from './rfiQuestionPayload';
import { RfiResponsePayload } from './rfiResponsePayload';

export interface RfiResponseSubmittedRequestActionPayload {
  payloadType?: string;
  rfiQuestionPayload: RfiQuestionPayload;
  rfiResponsePayload: RfiResponsePayload;
  rfiAttachments?: { [key: string]: string };
}
