/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RfiResponsePayload } from './rfiResponsePayload';

export interface RfiResponseSubmitRequestTaskActionPayload {
  payloadType?: string;
  rfiResponsePayload: RfiResponsePayload;
}
