/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RfiSubmitPayload } from './rfiSubmitPayload';

export interface RfiSubmitRequestTaskActionPayload {
  payloadType?: string;
  rfiSubmitPayload: RfiSubmitPayload;
}
