/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { RfiSubmitPayload } from './rfiSubmitPayload';

export interface RfiSubmittedRequestActionPayload {
  payloadType?: string;
  rfiSubmitPayload: RfiSubmitPayload;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  rfiAttachments?: { [key: string]: string };
  officialDocument: FileInfoDTO;
}
