/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The guidance section request
 */
export interface SaveGuidanceSectionDTO {
  name: string;
  displayOrderNo: number;
}
