/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ThirdPartyDataProviderDTO {
  providerName?: string;
  receivedOn?: string;
  importedOn?: string;
  payload?: object;
}
