/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The third party provider data details
 */
export interface ThirdPartyDataProviderCreateDTO {
  name: string;
  jwksUrl: string;
}
