/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UncertaintyLevel {
  monitoringMethod: 'BDN' | 'BUNKER_TANK' | 'FLOW_METERS' | 'DIRECT';
  methodApproach: 'DEFAULT' | 'SHIP_SPECIFIC';
  value: string;
}
