/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateOperatorDetails {
  registryId?: number;
  firstYearOfVerifiedEmissions?: number;
  monitoringPlanId?: string;
  accountName?: string;
  companyImoNumber?: string;
}
