/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAuthorityInfoDTO } from './userAuthorityInfoDTO';

export interface UsersAuthoritiesInfoDTO {
  authorities?: Array<UserAuthorityInfoDTO>;
  editable?: boolean;
}
