/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserAuthorityInfoDTO {
  userId?: string;
  firstName?: string;
  lastName?: string;
  roleName?: string;
  roleCode?: string;
  authorityCreationDate?: string;
  authorityStatus?: 'PENDING' | 'TEMP_DISABLED_PENDING' | 'ACTIVE' | 'DISABLED' | 'ACCEPTED' | 'TEMP_DISABLED';
}
