/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserStateDTO {
  userId?: string;
  roleType?: string;
  status?: 'NO_ROLE_TYPE' | 'ENABLED' | 'DISABLED' | 'ACCEPTED' | 'TEMP_DISABLED' | 'NO_AUTHORITY';
}
