/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VerifierAuthorityUpdateDTO {
  userId: string;
  authorityStatus: 'PENDING' | 'TEMP_DISABLED_PENDING' | 'ACTIVE' | 'DISABLED' | 'ACCEPTED' | 'TEMP_DISABLED';
  roleCode?: string;
}
