/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

export interface VerificationBodyDTO {
  id?: number;
  name?: string;
  accreditationReferenceNumber?: string;
  status?: 'ACTIVE' | 'PENDING' | 'DISABLED';
  address?: AddressDTO;
  emissionTradingSchemes?: Array<string>;
}
