/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

/**
 * The verification body dto to update
 */
export interface VerificationBodyUpdateDTO {
  id: number;
  name: string;
  accreditationReferenceNumber: string;
  address: AddressDTO;
  emissionTradingSchemes: Array<string>;
}
