/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerificationBodyInfoDTO } from './verificationBodyInfoDTO';

export interface VerificationBodyInfoResponseDTO {
  verificationBodies?: Array<VerificationBodyInfoDTO>;
  editable?: boolean;
}
