/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';

export interface VerificationBodyDetails {
  name?: string;
  accreditationReferenceNumber?: string;
  address?: AddressDTO;
  emissionTradingSchemes?: Array<string>;
}
