/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { AdminVerifierUserInvitationDTO } from './adminVerifierUserInvitationDTO';

/**
 * The verification body creation dto
 */
export interface VerificationBodyCreationDTO {
  name: string;
  accreditationReferenceNumber: string;
  address: AddressDTO;
  emissionTradingSchemes: Array<string>;
  adminVerifierUserInvitation: AdminVerifierUserInvitationDTO;
}
