/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { VirVerificationData } from './virVerificationData';

export interface VirApplicationSubmittedRequestActionPayload {
  payloadType?: string;
  reportingYear: number;
  verificationData: VirVerificationData;
  operatorImprovementResponses: { [key: string]: OperatorImprovementResponse };
  virAttachments?: { [key: string]: string };
}
