/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RegulatorReviewResponse } from './regulatorReviewResponse';
import { VirVerificationData } from './virVerificationData';

export interface VirApplicationReviewRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  verificationData?: VirVerificationData;
  operatorImprovementResponses?: { [key: string]: OperatorImprovementResponse };
  sectionsCompleted?: { [key: string]: string };
  virAttachments?: { [key: string]: string };
  regulatorReviewResponse?: RegulatorReviewResponse;
  rfiAttachments?: { [key: string]: string };
}
