/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RegulatorReviewResponse } from './regulatorReviewResponse';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { VirVerificationData } from './virVerificationData';

export interface VirApplicationReviewedRequestActionPayload {
  payloadType?: string;
  reportingYear: number;
  verificationData: VirVerificationData;
  operatorImprovementResponses: { [key: string]: OperatorImprovementResponse };
  virAttachments?: { [key: string]: string };
  regulatorReviewResponse: RegulatorReviewResponse;
  decisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
}
