/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementFollowUpResponse } from './operatorImprovementFollowUpResponse';
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RegulatorImprovementResponse } from './regulatorImprovementResponse';
import { VirVerificationData } from './virVerificationData';

export interface VirApplicationRespondToRegulatorCommentsRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  verificationData?: VirVerificationData;
  operatorImprovementResponses?: { [key: string]: OperatorImprovementResponse };
  sectionsCompleted?: { [key: string]: string };
  virAttachments?: { [key: string]: string };
  regulatorImprovementResponses?: { [key: string]: RegulatorImprovementResponse };
  operatorImprovementFollowUpResponses?: { [key: string]: OperatorImprovementFollowUpResponse };
  virRespondToRegulatorCommentsSectionsCompleted?: { [key: string]: string };
}
