/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementFollowUpResponse } from './operatorImprovementFollowUpResponse';

export interface VirSaveRespondToRegulatorCommentsRequestTaskActionPayload {
  payloadType?: string;
  reference: string;
  sectionsCompleted?: { [key: string]: string };
  operatorImprovementFollowUpResponse: OperatorImprovementFollowUpResponse;
}
