/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementResponse } from './operatorImprovementResponse';

export interface VirSaveApplicationRequestTaskActionPayload {
  payloadType?: string;
  operatorImprovementResponses?: { [key: string]: OperatorImprovementResponse };
  sectionsCompleted?: { [key: string]: string };
}
