/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegulatorReviewResponse } from './regulatorReviewResponse';

export interface VirSaveReviewRequestTaskActionPayload {
  payloadType?: string;
  regulatorReviewResponse?: RegulatorReviewResponse;
  sectionsCompleted?: { [key: string]: string };
}
