/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UncorrectedItem } from './uncorrectedItem';
import { VerifierComment } from './verifierComment';

export interface VirVerificationData {
  uncorrectedNonConformities?: { [key: string]: UncorrectedItem };
  priorYearIssues?: { [key: string]: VerifierComment };
  recommendedImprovements?: { [key: string]: VerifierComment };
}
