package uk.gov.mrtm.api.reporting.domain.verification;

public enum AerNotVerifiedDecisionReasonType {

    UNCORRECTED_MATERIAL_MISSTATEMENT,
    UNCORRECTED_MATERIAL_NON_CONFORMITY,
    VERIFICATION_DATA_OR_INFORMATION_LIMITATIONS,
    SCOPE_LIMITATIONS_DUE_TO_LACK_OF_CLARITY,
    SCOPE_LIMITATIONS_OF_APPROVED_MONITORING_PLAN,
    NOT_APPROVED_MONITORING_PLAN_BY_REGULATOR,
    ANOTHER_REASON
    ;
}
