export const mockEmpShipsXml = `
<shipParticularsList>
    <shipParticulars>
        <shipImoNumber>2222222</shipImoNumber>
        <name>Ever Green</name>
        <shipType>BULK</shipType>
        <grossTonnage>5000</grossTonnage>
        <flag>NO</flag>
        <iceClassPolarCode>IC</iceClassPolarCode>
        <conditionsOfExemption>
            <useOfDerogationCode>YES</useOfDerogationCode>
            <minimumNumberOfVoyages>301</minimumNumberOfVoyages>
        </conditionsOfExemption>
        <ccsCcu>
            <captureAndStorageApplied>YES</captureAndStorageApplied>
            <technology>string</technology>
            <emissionSourceName>Main Engine 1</emissionSourceName>
        </ccsCcu>
        <company>
            <nature>ISM_COMPANY</nature>
        </company>
        <monitoringPlan>
            <fuelTypes>
                <fuelTypeEntry>
                    <otherFuelType>other1</otherFuelType>
                    <fuelOriginCode>RFNBO</fuelOriginCode>
                    <fuelTypeCode>OTHER</fuelTypeCode>
                    <methodDensityBunkerCode>FUEL_SUPPLIER</methodDensityBunkerCode>
                    <methodDensityTankCode>FUEL_SUPPLIER</methodDensityTankCode>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CO2</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CH4</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>N2O</ghgCode>
                        <ttwEF>0.2</ttwEF>
                    </emissionFactors>
                </fuelTypeEntry>
                <fuelTypeEntry>
                    <otherFuelType>other2</otherFuelType>
                    <fuelOriginCode>FOSSIL</fuelOriginCode>
                    <fuelTypeCode>OTHER</fuelTypeCode>
                    <methodDensityBunkerCode>FUEL_SUPPLIER</methodDensityBunkerCode>
                    <methodDensityTankCode>FUEL_SUPPLIER</methodDensityTankCode>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CO2</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CH4</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>N2O</ghgCode>
                        <ttwEF>0.2</ttwEF>
                    </emissionFactors>
                </fuelTypeEntry>
                <fuelTypeEntry>
                    <otherFuelType>other3</otherFuelType>
                    <fuelOriginCode>BIOFUEL</fuelOriginCode>
                    <fuelTypeCode>OTHER</fuelTypeCode>
                    <methodDensityBunkerCode>FUEL_SUPPLIER</methodDensityBunkerCode>
                    <methodDensityTankCode>FUEL_SUPPLIER</methodDensityTankCode>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CO2</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>CH4</ghgCode>
                        <ttwEF>0.1</ttwEF>
                    </emissionFactors>
                    <emissionFactors>
                        <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                        <ghgCode>N2O</ghgCode>
                        <ttwEF>0.2</ttwEF>
                    </emissionFactors>
                </fuelTypeEntry>
            </fuelTypes>
            <emissionSources>
                <emissionSourceEntry>
                    <identificationNumber>IDE-111</identificationNumber>
                    <name>Main Engine 1</name>
                    <emissionSourceTypeCode>MAIN_ENGINE</emissionSourceTypeCode>
                    <emissionSourceClassCode>BOILERS</emissionSourceClassCode>
                    <monitoringMethodCode>FLOW_METERS</monitoringMethodCode>
                    <fuelTypeCodes>
                        <fuelTypeCode>OTHER</fuelTypeCode>
                        <otherFuelType>other1</otherFuelType>
                        <slipPercentage>0.02</slipPercentage>
                    </fuelTypeCodes>
                    <fuelTypeCodes>
                        <fuelTypeCode>OTHER</fuelTypeCode>
                        <otherFuelType>other3</otherFuelType>
                        <slipPercentage>0.02</slipPercentage>
                    </fuelTypeCodes>
                    <fuelTypeCodes>
                        <fuelTypeCode>OTHER</fuelTypeCode>
                        <otherFuelType>other2</otherFuelType>
                        <slipPercentage>0.02</slipPercentage>
                    </fuelTypeCodes>
                </emissionSourceEntry>
            </emissionSources>
            <monitoringMethods>
                <monitoringMethodEntry>
                    <monitoringMethodCode>FLOW_METERS</monitoringMethodCode>
                    <levelOfUncertaintyTypeCode>SHIP_SPECIFIC</levelOfUncertaintyTypeCode>
                    <shipSpecificUncertainty>99.12</shipSpecificUncertainty>
                </monitoringMethodEntry>
            </monitoringMethods>
        </monitoringPlan>
        <measuringEquipment>
            <measuringEquipmentEntry>
                <name>string</name>
                <appliedToCode>Main Engine 1</appliedToCode>
            </measuringEquipmentEntry>
        </measuringEquipment>
    </shipParticulars>
</shipParticularsList>
`;

export const mockEmpShipsCoreErrorsXml = `
<shipParticularsList>
  <shipParticulars></shipParticulars>
  <shipParticulars>
    <shipImoNumber>1111111</shipImoNumber>
    <name>Ship1</name>
    <shipType>RORO</shipType>
  </shipParticulars>
  <shipParticulars>
    <shipImoNumber>1111111</shipImoNumber>
      <name>Ship</name>
      <shipType>RORO</shipType>
  </shipParticulars>
</shipParticularsList>
`;

export const mockEmpShipsErrorsXml = `
<shipParticularsList>
    <shipParticulars>
        <shipImoNumber>2222222</shipImoNumber>
        <name>Ever Green</name>
        <conditionsOfExemption></conditionsOfExemption>
        <ccsCcu></ccsCcu>
        <company></company>
        <monitoringPlan>
            <fuelTypes>
                <fuelTypeEntry>
                    <emissionFactors></emissionFactors>
                </fuelTypeEntry>
            </fuelTypes>
            <emissionSources>
                <emissionSourceEntry>
                    <fuelTypeCodes></fuelTypeCodes>
                </emissionSourceEntry>
            </emissionSources>
            <monitoringMethods>
                <monitoringMethodEntry>
                </monitoringMethodEntry>
            </monitoringMethods>
        </monitoringPlan>
        <measuringEquipment>
            <measuringEquipmentEntry></measuringEquipmentEntry>
        </measuringEquipment>
    </shipParticulars>
</shipParticularsList>
`;
