export enum AerDataInitialSourceType {
  MANUAL = 'MANUAL',
  EXTERNAL_PROVIDER = 'EXTERNAL_PROVIDER',
  FETCH_FROM_EMP = 'FETCH_FROM_EMP',
  FROM_FETCH_PORTS_OR_VOYAGES = 'FROM_FETCH_PORTS_OR_VOYAGES',
}
