import { RequestTaskDTO } from '@mrtm/api';

export type MrtmRequestTaskType =
  | RequestTaskDTO['type']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SUBMIT'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_APPLICATION_SUBMIT'
  | 'EMP_ISSUANCE_APPLICATION_REVIEW'
  | 'EMP_ISSUANCE_WAIT_FOR_REVIEW'
  | 'EMP_ISSUANCE_APPLICATION_PEER_REVIEW'
  | 'EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW'
  | 'EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_AMENDS'
  | 'EMP_ISSUANCE_RDE_RESPONSE_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE'
  | 'EMP_ISSUANCE_RFI_RESPONSE_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_APPLICATION_SUBMIT'
  | 'EMP_NOTIFICATION_APPLICATION_REVIEW'
  | 'EMP_NOTIFICATION_WAIT_FOR_REVIEW'
  | 'EMP_NOTIFICATION_APPLICATION_PEER_REVIEW'
  | 'EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP'
  | 'EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_APPLICATION_SUBMIT'
  | 'EMP_VARIATION_APPLICATION_REVIEW'
  | 'EMP_VARIATION_WAIT_FOR_REVIEW'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEW'
  | 'EMP_VARIATION_WAIT_FOR_PEER_REVIEW'
  | 'EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT'
  | 'EMP_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW'
  | 'EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW'
  | 'EMP_VARIATION_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_AMENDS'
  | 'EMP_VARIATION_RDE_RESPONSE_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_RDE_RESPONSE'
  | 'EMP_VARIATION_RFI_RESPONSE_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_RFI_RESPONSE'

  /**
   * RDE
   */
  | 'RDE_SUBMITTED'
  | 'RDE_REJECTED'
  | 'RDE_ACCEPTED'
  | 'RDE_FORCE_REJECTED'
  | 'RDE_FORCE_ACCEPTED'
  | 'RDE_EXPIRED'

  /**
   * RFI
   */
  | 'RFI_SUBMITTED'
  | 'RFI_RESPONSE_SUBMITTED'
  | 'RFI_CANCELLED'
  | 'RFI_EXPIRED'

  /**
   * AER
   */
  | 'AER_APPLICATION_SUBMIT'
  | 'AER_WAIT_FOR_VERIFICATION'
  | 'AER_APPLICATION_VERIFICATION_SUBMIT'

  /**
   * DOE
   */
  | 'DOE_APPLICATION_SUBMIT'
  | 'DOE_APPLICATION_PEER_REVIEW'
  | 'DOE_WAIT_FOR_PEER_REVIEW'

  /**
   * NON-COMPLIANCE
   */
  | 'NON_COMPLIANCE_APPLICATION_SUBMIT'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE';
