import { RequestTaskActionPayload } from '@mrtm/api';

export type MrtmRequestTaskActionPayloadType =
  | RequestTaskActionPayload['payloadType']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SAVE_APPLICATION_PAYLOAD'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION_PAYLOAD'
  | 'EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_AMEND_PAYLOAD'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND_PAYLOAD'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_VARIATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_AMEND_PAYLOAD'

  /**
   * AER
   */
  | 'AER_SAVE_APPLICATION_PAYLOAD'
  | 'AER_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD'
  | 'AER_VERIFICATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD'
  | 'AER_SAVE_APPLICATION_VERIFICATION_PAYLOAD'
  | 'AER_VERIFICATION_RETURN_TO_OPERATOR_PAYLOAD'
  | 'AER_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'AER_SAVE_APPLICATION_AMEND_PAYLOAD'
  | 'AER_SKIP_REVIEW_PAYLOAD'

  /**
   * DOE
   */
  | 'DOE_SAVE_APPLICATION_PAYLOAD'
  | 'DOE_SUBMIT_NOTIFY_OPERATOR_PAYLOAD'
  | 'DOE_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'DOE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'

  /**
   * VIR
   */
  | 'VIR_SAVE_APPLICATION_PAYLOAD'
  | 'VIR_SAVE_REVIEW_PAYLOAD'
  | 'VIR_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'VIR_SAVE_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD'
  | 'VIR_SUBMIT_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD'

  /**
   * NON_COMPLIANCE
   */
  | 'NON_COMPLIANCE_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_CLOSE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_AMEND_DETAILS_PAYLOAD';
