import { RequestTaskActionProcessDTO } from '@mrtm/api';

export type MrtmRequestTaskActionType =
  | RequestTaskActionProcessDTO['requestTaskActionType']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SUBMIT_APPLICATION'
  | 'ACCOUNT_CLOSURE_SAVE_APPLICATION'
  | 'ACCOUNT_CLOSURE_CANCEL_APPLICATION'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_SAVE_APPLICATION'
  | 'EMP_ISSUANCE_SUBMIT_APPLICATION'
  | 'EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_REVIEW'
  | 'EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION'
  | 'EMP_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT'
  | 'EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION'
  | 'EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION'
  | 'EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION'
  | 'EMP_ISSUANCE_REQUEST_PEER_REVIEW'
  | 'EMP_ISSUANCE_REVIEW_RETURN_FOR_AMENDS'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_AMEND'
  | 'EMP_ISSUANCE_SUBMIT_APPLICATION_AMEND'
  | 'EMP_ISSUANCE_RECALL_FROM_AMENDS'
  | 'EMP_ISSUANCE_MAKE_PAYMENT'
  | 'EMP_ISSUANCE_CONFIRM_PAYMENT'
  | 'EMP_ISSUANCE_TRACK_PAYMENT'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_SAVE_APPLICATION'
  | 'EMP_NOTIFICATION_CANCEL_APPLICATION'
  | 'EMP_NOTIFICATION_SUBMIT_APPLICATION'
  | 'EMP_NOTIFICATION_UPLOAD_SECTION_ATTACHMENT'
  | 'EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION'
  | 'EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION'
  | 'EMP_NOTIFICATION_REQUEST_PEER_REVIEW'
  | 'EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_RESPONSE'
  | 'EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE'
  | 'EMP_NOTIFICATION_FOLLOW_UP_UPLOAD_ATTACHMENT'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION'
  | 'EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION'
  | 'EMP_NOTIFICATION_FOLLOW_UP_RETURN_FOR_AMENDS'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_APPLICATION_AMEND'
  | 'EMP_NOTIFICATION_FOLLOW_UP_RECALL_FROM_AMENDS'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_SAVE_APPLICATION'
  | 'EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT'
  | 'EMP_VARIATION_SUBMIT_APPLICATION'
  | 'EMP_VARIATION_SAVE_APPLICATION_REVIEW'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION'
  | 'EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION'
  | 'EMP_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT'
  | 'EMP_VARIATION_SAVE_REVIEW_DETERMINATION'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW'
  | 'EMP_VARIATION_REVIEW_RETURN_FOR_AMENDS'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION'
  | 'EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED'
  | 'EMP_VARIATION_CANCEL_APPLICATION'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED'
  | 'EMP_VARIATION_SUBMIT_APPLICATION_AMEND'
  | 'EMP_VARIATION_SAVE_APPLICATION_AMEND'
  | 'EMP_VARIATION_RECALL_FROM_AMENDS'

  /**
   * DOE
   */
  | 'DOE_MAKE_PAYMENT'
  | 'DOE_TRACK_PAYMENT'
  | 'DOE_CONFIRM_PAYMENT'

  /**
   * NON-COMPLIANCE
   */
  | 'NON_COMPLIANCE_SUBMIT_APPLICATION'
  | 'NON_COMPLIANCE_SAVE_APPLICATION'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION_SUBMIT_APPLICATION'
  | 'NON_COMPLIANCE_CLOSE_APPLICATION'
  | 'NON_COMPLIANCE_UPLOAD_ATTACHMENT';
