import { RequestTaskPayload } from '@mrtm/api';

export type MrtmRequestTaskPayloadType =
  | RequestTaskPayload['payloadType']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SUBMIT_PAYLOAD'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD'
  | 'EMP_ISSUANCE_WAIT_FOR_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_APPLICATION_PEER_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT_PAYLOAD'
  | 'EMP_ISSUANCE_WAIT_FOR_AMENDS_PAYLOAD'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_APPLICATION_SUBMIT_PAYLOAD'
  | 'EMP_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_APPLICATION_PEER_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS_PAYLOAD'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_APPLICATION_SUBMIT_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_WAIT_FOR_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_APPLICATION_AMENDS_SUBMIT_PAYLOAD'
  | 'EMP_VARIATION_WAIT_FOR_AMENDS_PAYLOAD'

  /**
   * NON-COMPLIANCE
   */
  | 'NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_CLOSE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION_PAYLOAD'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'NON_COMPLIANCE_SAVE_APPLICATION_PAYLOAD';
