import { RequestTaskActionPayload } from '@mrtm/api';

export type MrtmRequestTaskActionPayloadType =
  | RequestTaskActionPayload['payloadType']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SAVE_APPLICATION_PAYLOAD'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION_PAYLOAD'
  | 'EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_ISSUANCE_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_ISSUANCE_SAVE_APPLICATION_AMEND_PAYLOAD'
  | 'EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND_PAYLOAD'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_SAVE_APPLICATION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW_PAYLOAD'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED_PAYLOAD'
  | 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD'
  | 'EMP_VARIATION_SAVE_APPLICATION_AMEND_PAYLOAD';
