import { MrtmRequestTaskActionType, MrtmRequestTaskType } from '@shared/types';

export const requestTypeUploadActionMap: Record<MrtmRequestTaskType, MrtmRequestTaskActionType> = {
  EMP_ISSUANCE_APPLICATION_REVIEW: 'EMP_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT',
  EMP_VARIATION_APPLICATION_REVIEW: 'EMP_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT',
  EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE: 'RDE_UPLOAD_ATTACHMENT',
  EMP_VARIATION_WAIT_FOR_RDE_RESPONSE: 'RDE_UPLOAD_ATTACHMENT',
  EMP_ISSUANCE_RFI_RESPONSE_SUBMIT: 'RFI_UPLOAD_ATTACHMENT',
  EMP_VARIATION_RFI_RESPONSE_SUBMIT: 'RFI_UPLOAD_ATTACHMENT',
  EMP_NOTIFICATION_RFI_RESPONSE_SUBMIT: 'RFI_UPLOAD_ATTACHMENT',
  AER_APPLICATION_SUBMIT: 'AER_UPLOAD_SECTION_ATTACHMENT',
  VIR_RFI_RESPONSE_SUBMIT: 'RFI_UPLOAD_ATTACHMENT',
  AER_APPLICATION_REVIEW: 'AER_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE: 'NON_COMPLIANCE_UPLOAD_ATTACHMENT',
  NON_COMPLIANCE_NOTICE_OF_INTENT: 'NON_COMPLIANCE_UPLOAD_ATTACHMENT',
};
