import { RequestTaskDTO } from '@mrtm/api';

export const PAYMENT_TASKS: Array<RequestTaskDTO['type']> = [
  'EMP_ISSUANCE_MAKE_PAYMENT',
  'EMP_ISSUANCE_CONFIRM_PAYMENT',
  'EMP_ISSUANCE_TRACK_PAYMENT',
  'EMP_VARIATION_MAKE_PAYMENT',
  'EMP_VARIATION_CONFIRM_PAYMENT',
  'EMP_VARIATION_TRACK_PAYMENT',
  'EMP_VARIATION_REGULATOR_LED_MAKE_PAYMENT',
  'EMP_VARIATION_REGULATOR_LED_CONFIRM_PAYMENT',
  'EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT',
  'DOE_MAKE_PAYMENT',
  'DOE_CONFIRM_PAYMENT',
  'DOE_TRACK_PAYMENT',
];
