export const aerShipsXmlMock = `
<emissionReportsList>
    <emissionReport>
        <shipImoNumber>1111111</shipImoNumber>
        <name>Ship A1</name>
        <shipType>RORO</shipType>
        <grossTonnage>10000</grossTonnage>
        <flag>GR</flag>
        <iceClassPolarCode>PC1</iceClassPolarCode>
        <allYear>true</allYear>
        <company>
            <nature>SHIPOWNER</nature>
        </company>
        <fuelTypes>
            <fuelTypeEntry>
                <fuelOriginCode>FOSSIL</fuelOriginCode>
                <fuelTypeCode>HFO</fuelTypeCode>
                <emissionFactors>
                    <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                    <ghgCode>CH4</ghgCode>
                    <ttwEF>0.14</ttwEF>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFAULT</factorReferenceCode>
                    <ghgCode>CO2</ghgCode>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                    <ghgCode>N2O</ghgCode>
                    <ttwEF>0.12</ttwEF>
                </emissionFactors>
            </fuelTypeEntry>
            <fuelTypeEntry>
                <fuelOriginCode>BIOFUEL</fuelOriginCode>
                <fuelTypeCode>BIO_DIESEL</fuelTypeCode>
                <emissionFactors>
                    <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                    <ghgCode>CH4</ghgCode>
                    <ttwEF>0.24</ttwEF>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFAULT</factorReferenceCode>
                    <ghgCode>CO2</ghgCode>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFINED_BY_USER</factorReferenceCode>
                    <ghgCode>N2O</ghgCode>
                    <ttwEF>0.22</ttwEF>
                </emissionFactors>
            </fuelTypeEntry>
        </fuelTypes>
        <emissionSources>
            <emissionSourceEntry>
                <name>Main Engine 1</name>
                <emissionSourceTypeCode>MAIN_ENGINE</emissionSourceTypeCode>
                <emissionSourceClassCode>ICE</emissionSourceClassCode>
                <monitoringMethodCode>BDN</monitoringMethodCode>
                <fuelTypeCodes>
                    <fuelTypeCode>HFO</fuelTypeCode>
                </fuelTypeCodes>
                <fuelTypeCodes>
                    <fuelTypeCode>BIO_DIESEL</fuelTypeCode>
                </fuelTypeCodes>
            </emissionSourceEntry>
            <emissionSourceEntry>
                <name>Main Engine 2</name>
                <emissionSourceTypeCode>AUX_ENGINE</emissionSourceTypeCode>
                <emissionSourceClassCode>ICE</emissionSourceClassCode>
                <monitoringMethodCode>FLOW_METERS</monitoringMethodCode>
                <fuelTypeCodes>
                    <fuelTypeCode>HFO</fuelTypeCode>
                </fuelTypeCodes>
            </emissionSourceEntry>
        </emissionSources>
        <monitoringMethods>
            <monitoringMethodEntry>
                <monitoringMethodCode>BDN</monitoringMethodCode>
                <levelOfUncertaintyTypeCode>DEFAULT</levelOfUncertaintyTypeCode>
            </monitoringMethodEntry>
            <monitoringMethodEntry>
                <monitoringMethodCode>FLOW_METERS</monitoringMethodCode>
                <levelOfUncertaintyTypeCode>SHIP_SPECIFIC</levelOfUncertaintyTypeCode>
                <shipSpecificUncertainty>0.01</shipSpecificUncertainty>
            </monitoringMethodEntry>
        </monitoringMethods>
        <additionalInformation>
            <exemptionPerVoyageMonitoring>false</exemptionPerVoyageMonitoring>
        </additionalInformation>
    </emissionReport>
    <emissionReport>
        <shipImoNumber>2222222</shipImoNumber>
        <name>Ship B1</name>
        <shipType>OIL</shipType>
        <grossTonnage>20000</grossTonnage>
        <flag>US</flag>
        <iceClassPolarCode>NA</iceClassPolarCode>
        <allYear>false</allYear>
        <partialPeriodFromDate>2025-01-01</partialPeriodFromDate>
        <partialPeriodToDate>2025-12-31</partialPeriodToDate>
        <company>
            <nature>ISM_COMPANY</nature>
        </company>
        <fuelTypes>
            <fuelTypeEntry>
                <fuelOriginCode>FOSSIL</fuelOriginCode>
                <fuelTypeCode>LNG</fuelTypeCode>
                <emissionFactors>
                    <factorReferenceCode>DEFAULT</factorReferenceCode>
                    <ghgCode>CH4</ghgCode>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFAULT</factorReferenceCode>
                    <ghgCode>CO2</ghgCode>
                </emissionFactors>
                <emissionFactors>
                    <factorReferenceCode>DEFAULT</factorReferenceCode>
                    <ghgCode>N2O</ghgCode>
                </emissionFactors>
            </fuelTypeEntry>
        </fuelTypes>
        <emissionSources>
            <emissionSourceEntry>
                <name>Gas Turbine 1</name>
                <emissionSourceTypeCode>GAS_TURBINE</emissionSourceTypeCode>
                <emissionSourceClassCode>GAS_TURBINE</emissionSourceClassCode>
                <monitoringMethodCode>DIRECT</monitoringMethodCode>
                <fuelTypeCodes>
                    <fuelTypeCode>LNG</fuelTypeCode>
                    <slipPercentage>0.031</slipPercentage>
                </fuelTypeCodes>
            </emissionSourceEntry>
        </emissionSources>
        <monitoringMethods>
            <monitoringMethodEntry>
                <monitoringMethodCode>DIRECT</monitoringMethodCode>
                <levelOfUncertaintyTypeCode>DEFAULT</levelOfUncertaintyTypeCode>
            </monitoringMethodEntry>
        </monitoringMethods>
        <additionalInformation>
            <exemptionPerVoyageMonitoring>true</exemptionPerVoyageMonitoring>
        </additionalInformation>
    </emissionReport>
</emissionReportsList>
`;

export const mockAerShipsPartialErrorsXml = `
<emissionReportsList>
    <emissionReport></emissionReport>
    <emissionReport>
      <shipImoNumber>1111111</shipImoNumber>
      <name>Ship1</name>
      <shipType>RORO</shipType>
    </emissionReport>
    <emissionReport>
      <shipImoNumber>1111111</shipImoNumber>
      <name>Ship1</name>
      <shipType>RORO</shipType>
    </emissionReport>
</emissionReportsList>
`;
