import { aerPortCsvMap } from '@requests/common/aer/subtasks/aer-ports/aer-ports-upload.map';

export const mockAerPortsCsvSuccessPapaResult = {
  data: [
    {
      'IMO Number': '1111111',
      'Country code of port': 'GB',
      'Port code': 'GBABD',
      'Date of arrival': '01/02/2025',
      'Actual time of arrival (ATA)': '10:00:00',
      'Date of departure': '02/02/2025',
      'Actual time of departure (ATD)': '16:00:00',
      'Carbon capture and storage (CCS) (t)': '11.11',
      'Carbon capture and utilisation (CCU) (t)': '22.22',
      'Are you claiming a small island ferry operator surrender reduction?': true,
      'Fuel origin': 'BIOFUEL',
      'Fuel type': 'BIO_LNG',
      'Other fuel (O)': null,
      'Unique emission source name (O)': 'Boiler 1',
      'Methane slip (O)': '3.1',
      Amount: '1',
      'Measuring unit': 'M3',
      'Density (O)': '0.8',
      'CO2 emissions (t)': null,
      'CH4 emissions (tCO2e)': null,
      'N2O emissions (tCO2e)': null,
    },
    {
      'IMO Number': '1111111',
      'Country code of port': 'GB',
      'Port code': 'GBABD',
      'Date of arrival': '01/02/2025',
      'Actual time of arrival (ATA)': '10:00:00',
      'Date of departure': '02/02/2025',
      'Actual time of departure (ATD)': '16:00:00',
      'Carbon capture and storage (CCS) (t)': '11.11',
      'Carbon capture and utilisation (CCU) (t)': '22.22',
      'Are you claiming a small island ferry operator surrender reduction?': true,
      'Fuel origin': null,
      'Fuel type': null,
      'Other fuel (O)': null,
      'Unique emission source name (O)': null,
      'Methane slip (O)': null,
      Amount: null,
      'Measuring unit': null,
      'Density (O)': null,
      'CO2 emissions (t)': '33.3',
      'CH4 emissions (tCO2e)': '44.4',
      'N2O emissions (tCO2e)': '55.5',
    },
  ],
  errors: [],
  meta: {
    fields: Object.values(aerPortCsvMap),
  },
} as Papa.ParseResult<any>;

export const mockAerPortsCsvErrorPapaResult = {
  data: [
    {
      'IMO Number': null,
      'Country code of port': null,
      'Port code': null,
      'Date of arrival': null,
      'Actual time of arrival (ATA)': null,
      'Date of departure': null,
      'Actual time of departure (ATD)': null,
      'Carbon capture and storage (CCS) (t)': null,
      'Carbon capture and utilisation (CCU) (t)': null,
      'Are you claiming a small island ferry operator surrender reduction?': null,
      'Fuel origin': null,
      'Fuel type': null,
      'Other fuel (O)': null,
      'Unique emission source name': null,
      'Methane slip': null,
      Amount: null,
      'Measuring unit': null,
      Density: null,
      'CO2 emissions (t)': null,
      'CH4 emissions (tCO2e)': null,
      'N2O emissions (tCO2e)': null,
    },
  ],
  errors: [],
  meta: {
    fields: Object.values(aerPortCsvMap),
  },
} as Papa.ParseResult<any>;
