import { aerVoyageCsvMap } from '@requests/common/aer/subtasks/aer-voyages/aer-voyage-upload.map';

export const mockAerVoyagesCsvSuccessPapaResult = {
  data: [
    {
      'IMO Number': '1111111',
      'Country code of departure': 'GB',
      'Port code of departure': 'GBABD',
      'Date of departure': '1/1/2025',
      'Actual time of departure (ATD)': '01:04:00',
      'Country code of arrival': 'GB',
      'Port code of arrival': 'GBARD',
      'Date of arrival': '3/1/2025',
      'Actual time of arrival (ATA)': '16:04:00',
      'Fuel origin': 'FOSSIL',
      'Fuel type': 'OTHER',
      'Other fuel (O)': 'Custom Fuel 1',
      'Unique emission source name (O)': 'Boiler 1',
      'Methane slip (O)': '0.2',
      Amount: '100',
      'Measuring unit': 'M3',
      'Density (O)': '1',
      'CO2 emissions (t)': null,
      'CH4 emissions (tCO2e)': null,
      'N2O emissions (tCO2e)': null,
    },
    {
      'IMO Number': '1111111',
      'Country code of departure': 'GB',
      'Port code of departure': 'GBABD',
      'Date of departure': '1/1/2025',
      'Actual time of departure (ATD)': '01:04:00',
      'Country code of arrival': 'GB',
      'Port code of arrival': 'GBARD',
      'Date of arrival': '3/1/2025',
      'Actual time of arrival (ATA)': '16:04:00',
      'Fuel origin': null,
      'Fuel type': null,
      'Other fuel (O)': null,
      'Unique emission source name (O)': null,
      'Methane slip (O)': null,
      Amount: null,
      'Measuring unit': null,
      'Density (O)': null,
      'CO2 emissions (t)': '33.333',
      'CH4 emissions (tCO2e)': '44.444',
      'N2O emissions (tCO2e)': '55.555',
    },
  ],
  errors: [],
  meta: {
    fields: Object.values(aerVoyageCsvMap),
  },
} as Papa.ParseResult<any>;

export const mockAerVoyagesCsvErrorPapaResult = {
  data: [
    {
      'IMO Number': null,
      'Country code of departure': null,
      'Port code of departure': null,
      'Date of departure': null,
      'Actual time of departure (ATD)': null,
      'Country code of arrival': null,
      'Port code of arrival': null,
      'Date of arrival': null,
      'Actual time of arrival (ATA)': null,
      'Fuel origin': null,
      'Fuel type': null,
      'Other fuel (O)': null,
      'Unique emission source name': null,
      'Methane slip': null,
      Amount: null,
      'Measuring unit': null,
      Density: null,
      'CO2 emissions (t)': null,
      'CH4 emissions (tCO2e)': null,
      'N2O emissions (tCO2e)': null,
    },
  ],
  errors: [],
  meta: {
    fields: Object.values(aerVoyageCsvMap),
  },
} as Papa.ParseResult<any>;
